"""Roadmap Phase 7 §6 · assemble `title_en` and `instructions_en`.

    python3 tool/recipe_pipeline/translations/build_recipe_en.py \\
        --catalogue <catalogue_en.json> > out.sql

## Only the method steps are translated by hand

`instructions_en` has two halves and only one of them is prose:

    INGREDIENTS:            ← generated from recipe_ingredients.name_en,
    - 100 g quinoa            which the glossary already translated, with
    - 1/2 cucumber            units named by `localizedUnit`

    METHOD:                 ← the only part a human writes
    1. Simmer the quinoa …

That split is the payoff from migration 014, and it is what makes §6.2's
first rule — "never translate a quantity or a unit" — true **by
construction** rather than by review. A number cannot drift in a
translation that never sees it.

## Where the steps come from

`recipes_en.py`, keyed by the recipe's Turkish title. Turkish title
rather than uuid because a uuid tells a reviewer nothing and the titles
are unique — the pipeline's duplicate check enforces that.

A recipe missing from that file is skipped, not guessed. Partial coverage
is the expected state during a translation pass and the audit reports it;
a placeholder English title would look like progress and read like a bug.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from recipes_en import RECIPES_EN  # noqa: E402

# `localizedUnit` from lib/features/nutrition/domain/models/recipe_ingredient.dart,
# mirrored here because this script builds the same line the app renders.
# Kept in sync by `test/tool/unit_glossary_parity_test.dart`, which reads
# both and fails when they disagree — two copies of a mapping is fine as
# long as something proves they agree.
UNITS_EN = {
    "g": "g", "kg": "kg", "ml": "ml", "l": "l",
    "adet": None,
    "yemek kaşığı": "tbsp",
    "çay kaşığı": "tsp",
    "tatlı kaşığı": "dessertspoon",
    "kaşık": ("spoon", "spoons"),
    "su bardağı": ("glass", "glasses"),
    "bardak": ("glass", "glasses"),
    "fincan": ("small cup", "small cups"),
    "dilim": ("slice", "slices"),
    "diş": ("clove", "cloves"),
    "demet": ("bunch", "bunches"),
    "dal": ("sprig", "sprigs"),
    "yaprak": ("leaf", "leaves"),
    "tutam": ("pinch", "pinches"),
    "çimdik": ("pinch", "pinches"),
    "avuç": ("handful", "handfuls"),
    "paket": ("packet", "packets"),
    "kutu": ("can", "cans"),
    "porsiyon": ("portion", "portions"),
    "ölçek": ("scoop", "scoops"),
    "baş": ("head", "heads"),
    "top": ("ball", "balls"),
}


def unit_en(unit, quantity):
    if not unit:
        return None
    if unit not in UNITS_EN:
        return unit          # unknown: render as written, never guess
    mapped = UNITS_EN[unit]
    if mapped is None:
        return None
    if isinstance(mapped, tuple):
        return mapped[1] if (quantity or 0) > 1 else mapped[0]
    return mapped


def format_quantity(value):
    if value is None:
        return None
    number = float(value)
    if number == int(number):
        return str(int(number))
    for target, label in ((0.25, "1/4"), (0.333, "1/3"), (0.5, "1/2"),
                          (0.75, "3/4")):
        whole = int(number)
        if abs(number - target) < 0.005:
            return label
        if whole > 0 and abs(number - whole - target) < 0.005:
            return f"{whole} {label}"
    return f"{number:.2f}".rstrip("0").rstrip(".")


def ingredient_line(row):
    parts = []
    quantity = format_quantity(row.get("quantity"))
    if quantity:
        parts.append(quantity)
    unit = unit_en(row.get("unit"), row.get("quantity"))
    if unit:
        parts.append(unit)
    parts.append(row.get("name_en") or row.get("name_tr") or "")
    line = " ".join(p for p in parts if p)
    note = row.get("note_en")
    return f"- {line} ({note})" if note else f"- {line}"


def esc(value):
    return value.replace("'", "''")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalogue", required=True)
    args = parser.parse_args()

    with open(args.catalogue, encoding="utf-8") as fh:
        catalogue = json.load(fh)

    out = [
        "-- Roadmap Phase 7 · English recipe titles and instructions.",
        "-- Generated by tool/recipe_pipeline/translations/build_recipe_en.py",
        "-- Do not hand-edit; change recipes_en.py and re-run.",
        "--",
        "-- The INGREDIENTS half is generated from recipe_ingredients, so no",
        "-- quantity or unit passes through a translation. Only the METHOD",
        "-- half is authored.",
        "",
        "begin;",
        "",
    ]
    written, skipped = 0, []
    for row in catalogue:
        entry = RECIPES_EN.get(row["title"])
        if entry is None:
            skipped.append(row["title"])
            continue
        title_en, steps_en = entry
        lines = [ingredient_line(i) for i in row["ingredients"]]
        body = "INGREDIENTS:\n" + "\n".join(lines) + "\n\nMETHOD:\n" + \
               "\n".join(f"{i + 1}. {s}" for i, s in enumerate(steps_en))
        out.append(
            "update public.recipes set title_en = '%s', "
            "instructions_en = '%s' where id = '%s';"
            % (esc(title_en), esc(body), row["id"])
        )
        written += 1

    out += ["", "commit;", ""]
    print("\n".join(out))
    print(f"-- translated {written}, skipped {len(skipped)}", file=sys.stderr)
    for title in skipped[:10]:
        print(f"--   not in recipes_en.py: {title}", file=sys.stderr)


if __name__ == "__main__":
    main()
