-- Roadmap Phase 7 · derived dietary flags.
-- Generated by tool/recipe_pipeline/classify_catalogue.dart —
-- do not hand-edit; change the classifier and re-run.
--
-- `halal` never appears here. It cannot be derived from an
-- ingredient list and is authored; see the classifier.

begin;
-- Acılı Domates Çorbası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'c7530a54-0946-41fe-a283-20d70fc067de';
-- Akdeniz Kinoa Salatası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '3971c479-ce32-4b34-9b9c-013dee1df749';
-- Avokadolu Tam Buğday Tost
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'eac3e53c-155b-413f-baac-a9a3e8d1e079';
-- Avokadolu Yumurtalı Tam Buğday Tost
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'dairy_free']::text[] where id = '1fd74b61-7b93-47e9-9de3-111d1bffb6d2';
-- Bademli Süt Pudingi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'a4b2407b-b8c5-42c9-897a-9b278cf09a80';
-- Bahçıvan Salatası
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '8ee45d41-201d-4070-8125-82572e27e368';
-- Bal Soslu Vanilyalı Yoğurt
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '802c2e46-5125-42f5-9587-0b0b3c0f2ce6';
-- Bal-Cevizli Lor Peyniri
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '01115b20-4d27-47af-9ab4-7b7bb0896688';
-- Bal-Cevizli Süzme Yoğurt
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '199c2d0f-6762-4ab5-a8e9-43bf797836ce';
-- Bal-Tarçınlı Ekmek Tatlısı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '954637ff-d82c-4895-b007-f4a07a5be8be';
-- Bazlama Tava Tost
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'f6a99c06-ec20-4ded-ad03-c922b5ce6924';
-- Beyaz Peynirli Bal Tatlısı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'c9033734-c8da-49e0-9171-46d203b0c410';
-- Beyaz Peynirli Krep
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'ead9815b-2916-4f6d-a6a2-ca4da7e063ad';
-- Beyaz Peynirli Sade Makarna
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '1b35914c-3679-4653-ba66-6712fe4580ec';
-- Beyaz Peynirli Tam Buğday Tost
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '3a214fcf-8431-446d-a3c7-c79477ed35c1';
-- Beyaz Pilav ve Etli Sote
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '69fe7821-da0d-4fde-b922-1bff725ba374';
-- Beyaz Pilav ve Sade Yoğurt
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'cfbd5f33-c888-41da-bfff-19dac7bb5464';
-- Bezelye Etli
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '5e07f2d7-d319-49df-9594-27625e023968';
-- Bonfileli Burrito
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '2cdccaa8-2a84-480c-b763-a58f7098a206';
-- Bonfileli Salata
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'c44f3263-ab6b-4199-90bc-56597b5711b4';
-- Cevizli Hurma Topları
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'bf0de0db-b6d4-4097-a476-5e885f7df580';
-- Cevizli Karamelize Muz
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'a0f69eb5-d78f-4343-ac48-2f3887b6cb07';
-- Cevizli Yoğurt Tatlısı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '0a5aa59a-d467-4678-a7ec-88e7d2508a8b';
-- Chia Tohumlu Vegan Pancake
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = '06619310-0964-4c14-b9bd-76e915fc2379';
-- Chia Tohumu Pudingi
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '609271de-0d7b-4936-a958-c036c17ce1dc';
-- Çiğ Sebze Kahvaltı Tabağı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'f7bdb1c2-8d2c-49df-81ea-ad6cd959b8b4';
-- Çiğ Sebze ve Yoğurtlu Sos
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '9ca7c29f-a84c-4eda-857c-0691ae8b3cf8';
-- Çikolatalı Chia Tohumu Pudingi
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '6080c19f-9ab2-4b03-b7bb-58714d7af12e';
-- Çikolatalı Muzlu Protein Shake
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '480dd7a1-fc9b-457f-93d2-2528f0366e9c';
-- Çikolatalı Protein Puding
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '4363943a-3361-421a-8cc3-3307ca0257a2';
-- Çikolatalı Yulaf Topları
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'dairy_free']::text[] where id = '03e58bea-2402-4487-9b18-c3684ba0f036';
-- Çılbır
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '094b6838-66f7-4f54-a67a-6044c70d8407';
-- Çırpılmış Yumurta ve Pastırma
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free']::text[] where id = '3de1e0e6-e7be-4c73-9129-c5ca0af644e8';
-- Çıtır Yumurtalı Sandviç
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '579c99c8-5802-4707-98e7-36fe6438d3d3';
-- Domates Salçalı Bonfile Yemeği
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'dc428047-7628-4933-820e-5748e0865857';
-- Domates Soslu Köfte
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = 'f1a55d77-c62c-4d80-9de1-1c8b1bb8a627';
-- Domates Soslu Sade Makarna
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'cd1b5be6-f027-4811-a26b-e1a1c23bbe61';
-- Domates ve Beyaz Peynir Tabağı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'fe2e091e-d258-4a56-a891-097e722572c4';
-- Domatesli Pirinç Pilavı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '09e92bc4-5133-4776-b5cc-46d748b3a8cd';
-- Domatesli Sade Tavuk
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '41b68050-bc5d-41c7-b3f2-0807a1c525ff';
-- Domatesli Sahanda Yumurta
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '8e695e52-6f78-4f80-86b1-b436b28523d7';
-- Donmuş Muz Dilimleri
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'f85fbb18-3b31-465c-8038-c0ef883487fa';
-- Donmuş Yoğurt Topları
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'c6265b3a-94ed-4ff5-9de5-74705d390730';
-- Elma Dilimleri ve Fıstık Ezmesi
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'be63a065-aebc-4f62-90ab-1fe8a19e275f';
-- Etli Kabak Yemeği
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '31e02a6c-3dd9-42f6-86f2-0e21b7fd1b9f';
-- Etli Kuru Fasulye
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'e2b01ed3-a467-4f2e-bf9d-e01f844ae31c';
-- Etli Nohut
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '92fa47af-0825-4c63-8a35-b30799b3e5b1';
-- Etli Nohutlu Pilav
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free']::text[] where id = '7efe23df-862c-4986-aa7e-34052ee955bf';
-- Etli Pırasa Yemeği
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free']::text[] where id = '469ee18e-bc66-404f-b3b9-f8b58b10ac6a';
-- Etli Sebzeli Çorba
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '5aba127a-cf84-4ddc-91b6-6a3028e46b66';
-- Etli Tarhana Çorbası
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '0509dfaa-cf63-40d9-8290-6f091bd28a18';
-- Ev Yapımı Patates Cipsi
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '5b77fd24-b9e5-49cf-ad54-2f776e45bec9';
-- Ev Yapımı Protein Bar
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'd46c5a04-cc09-4e56-a006-a75a9e98300a';
-- Ezogelin Çorbası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'ad98f215-fac6-4dcc-a7b7-41906f8862f4';
-- Fırın Somonu ve Tatlı Patates Püresi
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '6fe3d2ec-cbae-4325-9af2-36c442ddb89e';
-- Fırın Tarçınlı Elma
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '79b6a605-3578-46b8-b3aa-45c9d5224c14';
-- Fırında Hindi ve Esmer Pirinç
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'b3c75b75-78ec-4cd6-8a8a-9b9b1c7d71f1';
-- Fırında Levrek ve Kuskus
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '15ae600f-6c57-491b-99b5-e2a6a926f0bf';
-- Fırında Somon ve Tatlı Patates
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '0f1fdd30-f916-4c85-964e-aa3e96a8f39b';
-- Fırınlanmış Somon ve Tatlı Patates
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'ec313347-045d-4edf-9c73-653df84e8591';
-- Fıstık Ezmeli Muzlu Vegan Smoothie
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = '265ad055-2146-494e-af57-271ad6154a66';
-- Fıstık Ezmeli Muzlu Yulaf Ezmesi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '061a039b-a898-4991-a058-33e23ac7538f';
-- Fıstık Ezmeli Protein Yulaf Ezmesi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '01370365-605e-4ceb-8e99-c76ae07595bf';
-- Fıstık Ezmeli Yulaf Lapası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '5fa526b5-3cdd-4abb-8ae6-a317870fba61';
-- Hamsi Tava
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'e9b728ed-f7f7-47eb-ba79-27d2921eb6a1';
-- Hardallı Tavuk Salatası
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free']::text[] where id = 'c3e6db2d-8a34-4134-80d1-213707c2db12';
-- Haşlanmış Yumurta ve Domates
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '4a7ce8ad-cc7e-4f69-ba67-3ee2827a4cbf';
-- Hazır Çiğ Köfte
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'c8145ef3-213a-44fe-8f6c-e6bd8e1c66e4';
-- Hellim Peyniri Tava
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '1365f62b-8998-4cb5-af9e-47b2d478c028';
-- Hindi Etli Marul Wrap
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free']::text[] where id = 'd3375cf6-45a4-491a-9003-ad76cb56fe6d';
-- Hindi Etli Pratik Bulgur
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = 'ef148018-5d33-405f-b384-3c5bb3deb675';
-- Hindi Etli Yoğurtlu Köfte
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '14c3b11e-12c0-4df0-9aad-e46a187158ef';
-- Hindi Göğsülü Avokadolu Wrap
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '8228b6bf-ccd5-48a9-ac76-0b460b8705d9';
-- Hindi Köfte ve Izgara Kabak
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '0a65ccaa-a01c-4175-8449-d109e259df39';
-- Hindi Salam Tabağı
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '929cec78-41c6-4e84-8e35-8d99640ee65b';
-- Hindi Salam ve Yumurta
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = 'ae78bbea-cfda-468e-908f-db8ae1d3b49e';
-- Hindi Soslu Makarna
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = 'b2ff317e-fb38-48ed-9412-88d86e852f62';
-- Hindi Yoğurtlu Wrap
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '6a0ce3d2-89f6-4f36-9279-2a8fbcd7923a';
-- Hindistan Cevizli Chia Pudingi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'ab7df82a-8a39-449a-b187-c66ede193752';
-- Hindistan Cevizli Süt Pudingi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '56b3ce28-d009-47be-9ff1-fd5c8a6c32dc';
-- Hızlı İrmik Helvası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '2fe3d9aa-ef47-4b8c-9694-d07190f0ac12';
-- Hızlı Krep ve Reçel
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '8052bba5-2a2a-4167-84f6-71d3743b9711';
-- Hızlı Kuru Fasulye Yemeği
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'c319deb7-b804-4533-af20-736064c529d3';
-- Hızlı Mercimek Köftesi
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'da31c81d-fd52-459a-a8f3-46f8d5a715b5';
-- Hızlı Sade Lokma
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'dairy_free']::text[] where id = '3c296846-e695-48c8-b4ff-8c89a1585d29';
-- Hızlı Tavuk Pirzola
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '99c97c76-6ffa-44d5-b6b3-28e0f0861638';
-- Hızlı Yumurtalı Mercimek Çorbası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'bf56330b-1533-4aac-8a28-1ea1d5e367ad';
-- Ispanaklı Peynirli Omlet
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '3208f001-4786-4e84-b679-203ccc625390';
-- Izgara Bonfile ve Brokoli
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free']::text[] where id = '2412acfb-f68c-47e9-8de0-90571cd2c809';
-- Izgara Bonfile ve Közlenmiş Sebze
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '0a1cf981-c51a-4b61-9d9b-e9693c4a62d7';
-- Izgara Hindi ve Pirinç Kasesi
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'acccd4e0-c701-499e-8292-f75a7e58e357';
-- Izgara Karides ve Roka Salatası
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '60b70292-54c6-4f0f-8433-2d56e2b6c2a8';
-- Izgara Levrek ve Buharda Sebze
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'c93acf1e-8896-41a5-9b38-d85a6786f361';
-- Izgara Sebzeli Ton Balığı Salatası
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '24b0010a-1211-4d6a-b238-8a7e07197328';
-- Izgara Somon & Tatlı Patates
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'b3939d44-6c10-40b9-ac03-02728edb3828';
-- Izgara Tavuk ve Kinoa Kasesi
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'ab7a79b3-fa9c-4976-bd6c-ff44b13f6ca1';
-- Izgara Tavuklu Hafif Sezar Salata
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '4de04113-29b9-49f8-9b7f-9048a096b5a6';
-- Izgara Tavuklu Kinoa Salatası
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free']::text[] where id = 'c8669e27-8430-4b97-b127-902e9d342e71';
-- Kakaolu Hurma Topları
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '5b7da9b2-8a49-41c4-b8de-f33fcc5c8df4';
-- Kakaolu Yulaf Lapası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '5792cbe9-8e95-412b-8dbd-b0efb16dd4ac';
-- Karadeniz Kuymak
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'd9f69821-6787-4c7b-9976-8895e469a101';
-- Karamel Soslu Yoğurt
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'db694232-06a0-4c0d-b6c8-61ec39b5e63e';
-- Karides Stir-Fry ve Yasemin Pirinci
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '3e043a68-54a5-4e15-a471-622ac2197d23';
-- Karışık Zeytin ve Peynir Tabağı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '5cb601b2-1492-459e-bae2-96dfd3e5c4e9';
-- Karpuzlu Beyaz Peynir
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'ed4b6558-6d7b-405b-abf1-1349fdffa231';
-- Kaşar Peynirli Tava Tost
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'de6538aa-fb92-4512-be44-211a0981fe62';
-- Kırmızı Mercimek Çorbası ve Tam Buğday Ekmeği
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = '3d353b52-869a-4200-892e-4167675eb37b';
-- Kıymalı Patates Yemeği
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '0bee4c83-4936-41d5-87d1-64e06b681794';
-- Kıymalı Sade Makarna
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '8b24a4b9-583b-45d8-bb5f-7408699cf0e8';
-- Kıymalı Yüksek Protein Makarna
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '63179697-fa64-4600-b710-a95cd3fb1468';
-- Kıymalı Yumurta Tava
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '019ff752-06ec-4385-ace0-26045a84c75c';
-- Klasik Mercimek Çorbası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'f14a3060-241b-42a5-a2e0-a64afa7f309c';
-- Kuru Kayısı Yulaflı Süt
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'dc5bb5aa-6a6f-4d26-bd43-17f9d831d719';
-- Levrek Tava
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '11153e88-9a29-4068-9be1-ea6928bfac9e';
-- Limon Soslu Roka Salatası
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '51f034fb-777b-49c2-a1a2-2d6628d34216';
-- Limon-Bal Yoğurt
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '1cc4c132-5bdb-47a1-9084-b0f8e97ccdf6';
-- Limonlu Bal Sıcak Süt
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '30e44822-f5c7-4293-9f96-04264e96bdbf';
-- Lor Peynirli Bal Ekmek
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'e50f4425-cdd0-4080-9340-b1768caa560b';
-- Lor Peynirli Domates Tabağı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'd36fcc2b-35ec-476d-89ab-3bdf2d4c4041';
-- Mantarlı Sade Omlet
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '49dd6e39-2146-4ae4-82c8-9ed52c3ad072';
-- Mantarlı Tavuk Sote
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'fe75401a-3a4f-45bb-8fdc-6aa763efe90f';
-- Maydanozlu Sade Omlet
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '2eed26c5-0159-4f1d-8843-ed5630524c06';
-- Maydanozlu Yumurta Salatası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '666cc2d1-aae3-4ccf-9261-d667354b3641';
-- Menemen Klasik
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'c1d7465b-c283-4721-a5f2-fbf45867b9c2';
-- Mercimek Köftesi Wrap
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = '0aaa8b17-b942-4dcd-a0a2-cb8921c4f275';
-- Mercimekli Erişte
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'c6b12acc-1c09-48da-93b7-6e6c1085ff10';
-- Meyveli Süzme Yoğurt
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '2b25384d-8565-4e99-a993-246e1c5fef80';
-- Mikrodalgada Çikolatalı Kek
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '41b4d8b4-ff73-4ec9-9a52-0535f47af768';
-- Mikrodalgada Tarçınlı Elma
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'ba6e9ad9-0f95-40e9-9571-34472de90557';
-- Mısır Gevrekli Süt
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '8a2e1bdd-b0bf-4bbd-bf10-c7666a18bd15';
-- Mücver Tava
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '4d72f57f-5936-49af-9e56-a9a080923c75';
-- Muz-Tahin Sandviç
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = '6a3677c0-2b6b-4526-ada5-24bb323f39de';
-- Muzlu Sıcak Yulaf Lapası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '570d0e8a-a4a5-4bdd-8c1f-23c6428d21eb';
-- Muzlu Vegan Dondurma
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '170064fe-1eea-4b22-a968-18fecb4f161d';
-- Muzlu Yoğurt Tatlısı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'd6c4a12c-5c3a-4e12-806d-fbc8077b2a07';
-- Nohutlu Kinoa Buddha Kasesi
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '6205195a-8a45-4333-b7f0-9d9ff2a4d683';
-- Patates Çorbası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '8072e753-085e-4b97-8ffb-8b869b85eb7e';
-- Patates Pofuduk
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'e9a91b4f-0c2f-4522-b765-1446d58ec699';
-- Pekmezli Hurma Pudingi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '047a97f5-9e60-4d78-995e-5d2dab1d247d';
-- Pekmezli Süt Tatlısı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'b1a414f1-2bc0-41b3-ae76-7a0f34df69b2';
-- Pekmezli Yoğurt Mousse
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'f28008e3-1b55-415f-9e14-50c6c245c0c8';
-- Pırasa Köftesi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'ebc24738-362c-4edb-ba84-248fc0151bfa';
-- Pırasalı Pilav
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'f938dcf2-420a-4813-9f58-c1fc542dfd23';
-- Pratik Aşure
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = '167e3115-61d0-4ac9-a45c-02399a82a35d';
-- Pratik İmam Bayıldı
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '90586a1b-2cb2-4eef-9297-9f4245d244fe';
-- Pratik Karnıyarık
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'd9a488c2-d283-458e-be43-4e94a25ad418';
-- Pratik Muhallebi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'cc950f3e-9659-4aa7-8f16-536b881a9d99';
-- Pratik Nohut Yemeği
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '673bfa52-fad0-487f-8b23-d17b6b34368f';
-- Pratik Patates Köftesi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'fb4f87fa-0565-452b-83e6-18013510e676';
-- Pratik Sütlaç
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '3da89c1b-90cf-4d87-8074-a39cb7780f75';
-- Pratik Yoğurtlu Mantı
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '6cc81770-d660-4bc3-9282-c49dc977a568';
-- Pratik Yumurtalı Pişi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '7678dd73-fb90-4d37-9c04-4456e562b770';
-- Pratik Yumurtalı Salata
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '67a05c1f-cd97-461a-bb15-92fdf4a9a9a2';
-- Protein Omlet & Avokado
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'c7c38e2a-3888-445f-b81b-761e5bf9160b';
-- Protein Pankek Yığını
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '2b644680-9aab-4ef8-924a-f98de8e20bfd';
-- Reçelli Tam Buğday Tost
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '12475f6e-8a3c-4aa7-98ec-daf0112e252b';
-- Roka Salatası ve Izgara Tavuk
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '0bc20be4-ddbf-4dd4-a827-594bf0f85e18';
-- Roka ve Ceviz Salatası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '30485245-515d-4877-808d-0c0ff94d400a';
-- Sade Bonfile Sote
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'a3562212-d561-4919-8694-b802b9ff34d7';
-- Sade Bulgurlu Salata
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = '504aa4fd-edd4-4505-ba63-8d6450e4ad0c';
-- Sade Domates Salatası
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'b32ec536-6f40-4362-b938-1b15dfeb29ba';
-- Sade Hindi Etli Pilav
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free']::text[] where id = 'eaf3c4d2-bb51-427a-a4e8-6e45fe94c6f5';
-- Sade İncir Tatlısı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'db4e3f10-a57f-42b4-adc6-5c8c277ce2e1';
-- Sade Izgara Köfte
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '6e0e1c2d-d21a-4928-9eff-67b247fe737c';
-- Sade Köfte Tava
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = 'ad0a4256-ff49-425e-bbb4-60989c287b41';
-- Sade Köy Ekmeği ve Tereyağı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '2322103e-196c-4b5b-b713-788fc5417120';
-- Sade Mercimek Yemeği
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '9510f877-2385-4eb1-b0a7-3aae49777dd3';
-- Sade Mıhlama
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'be77297d-c9e8-4a4b-a7ba-89e3b24a5e6d';
-- Sade Mısır Salatası
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '69d1e08a-49c2-4cec-babe-aa78e92315a8';
-- Sade Pancar Salatası
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'f614709f-b5d4-4a60-80c3-bb4d36712e8f';
-- Sade Patates Püresi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '6287826c-89c5-451a-aff9-6117db1c50d5';
-- Sade Patates Tavası
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'f882f389-4fa3-4986-a43b-0f55241bd3e9';
-- Sade Pirinç Sütü Tatlısı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '0dcf4be2-3221-4dd3-9d5c-dcc601e0f676';
-- Sade Sucuklu Krep
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '4938d6d8-6911-4375-b4e2-433995df3bab';
-- Sade Süt Helvası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '6c4f8140-93aa-41fb-9676-6a89efabc646';
-- Sade Tahin Mousse
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '76af5ce8-5026-4df9-a10b-04a55e357480';
-- Sade Tahıl Bar
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'dairy_free']::text[] where id = '218d0c15-521b-4bb3-badd-1bd421e8c789';
-- Sade Un Helvası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '926b9c28-b1e3-40e8-868d-f8ec344b7f7b';
-- Sade Yumurtalı Ekmek
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '5a6e1cce-1094-4d5d-aebf-6f5e39fa126d';
-- Sade Yumurtalı Süt Tatlısı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'e64c30b0-41f8-472f-b5ee-648a0282fe5f';
-- Salam ve Sade Tabak
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '57515ce3-6a2b-4092-8f1a-aee0f8e2b341';
-- Salatalık Sticks ve Yoğurt Sosu
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'e65d90b7-1698-4497-a9a6-d538dcca055b';
-- Salatalık ve Beyaz Peynir
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'e02a8717-2d77-46a2-8b36-82c6c927a71c';
-- Salçalı Tavada Yumurta
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '57ef1539-982f-4a31-9d45-144cb8843a14';
-- Salçalı Yumurtalı Köfte
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '2b2d3082-fb93-422a-83fa-6dcc29165aec';
-- Sarımsaklı Cacık
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '0f5d46e9-5d99-4110-97ab-021d545b5e15';
-- Sebzeli Bulgur Pilavı
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = '967afee5-a190-4224-895f-d7cd5cc70d56';
-- Sebzeli Ev Çorbası
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'b068825f-c965-4b78-afc4-bf3a231a7ca1';
-- Sebzeli Mercimek Çorbası
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '23fbcfae-5a2b-45f8-9496-6f6ad78a7f29';
-- Sebzeli Pratik Köfte
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = 'e30b79b4-3f62-40e1-8036-d20c67dd5fe6';
-- Şehriye Çorbası Yumurtalı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '6b43b796-865e-43cf-a678-5c370dc4c570';
-- Şekersiz Çikolatalı Yoğurt Mousse
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '8f406bf5-a009-43f6-a97c-b44dcdd4e370';
-- Şerbetli Yulaf Topları
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'dairy_free']::text[] where id = '13cf5b2f-1cfc-4305-8183-993f1d7b8660';
-- Soğan-Domates Çorbası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '18d40545-b0b2-45bd-ae6e-16e1f935709a';
-- Soğanlı Etli Sote
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '2892d52a-3754-4afb-8d6d-d1005b391fb4';
-- Soğanlı Hızlı Tavuk Sote
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '5af46c91-1243-497b-b956-77d313c763f1';
-- Soğanlı Köfte
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '1e237e15-2a91-488c-ad30-09dd4364b0ac';
-- Soğanlı Marul Salatası
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '3771c575-d15e-479d-99b2-5dbcba096545';
-- Soğanlı Patates Kavurma
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '380efa78-7e00-4038-85e2-d04098a858f8';
-- Soğuk Tavuk Göğsü Dilimleri
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '8c613f1a-fd95-46df-b994-496c4d5b1185';
-- Sucuklu Sade Patates
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'd01efbcc-70aa-47a1-9e4e-3a2478d97e2d';
-- Sucuklu Yumurtalı Bulgur
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '58d43640-2c47-4f30-9cb7-dff3c9e13fe3';
-- Sütlü Yulaf Ezmesi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '66dfb3f4-3e52-480b-95b1-8aa20b8cdde9';
-- Süzme Peynir ve Böğürtlen
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '1bd24999-8e32-4c38-9883-4a2fbe144f63';
-- Süzme Peynirli Avokado
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '4ab3110d-4f84-44d3-979a-b131609c8a5a';
-- Süzme Peynirli Tost
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '7d15cf47-aca0-4111-9e67-0652638b2d62';
-- Süzme Yoğurtlu Beyaz Peynir Tabağı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '79cdb494-b6a5-4b3c-a482-cdb2d59f846b';
-- Süzme Yoğurtlu Protein Kasesi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '966ee5cd-c207-4bed-af4b-d35a3eefc93d';
-- Süzme Yoğurtlu Protein Smoothie
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '9e2132b7-b994-4791-8ce6-b06f2b81ed16';
-- Süzme Yoğurtlu Yer Fıstığı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '4b346b34-6e9a-48cd-90f5-900ad61e6c76';
-- Tahin Pekmez Ekmek
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'e22861f2-b90b-440e-b8d8-a5c9824bee93';
-- Tahin Soslu Havuç Sticks
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '5b81219f-6f9c-4934-8143-c1b32a7a4c76';
-- Tahin Soslu Marul Salatası
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'd427f819-3360-4282-a386-bedfea039db5';
-- Tahin-Pekmez Topları
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'ca57151b-64ff-40be-a7ac-4d08ce00f885';
-- Tahinli Sade Yoğurt
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '10e48528-dff4-41fe-a5a2-2bef4b5c2089';
-- Tarçınlı Süzme Yoğurt
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '4064b55c-a0fb-4f6f-a0a0-3bf31ed21872';
-- Tarçınlı Yulaf Tatlısı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'b742477e-1837-4611-90c3-ad825e7d0f4e';
-- Tarçınlı Yumurta Tostu
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '1e6d1313-bad2-41e4-88eb-8f30ac9b0cfe';
-- Tava Pırasası Yumurtalı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '4be347eb-04c3-4a5c-8eb3-98cd092012b9';
-- Tavada Karnabahar Köftesi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'a92b439c-e426-46e3-8a50-1b37b719ba81';
-- Tavada Sade Sebze Atıştırmalığı
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '0ddb2482-c3f0-4d3f-b5bf-96b5eb925e98';
-- Tavuk Göğsü Marul Sarma
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '96108507-1627-4de5-9ef8-66e1105d506b';
-- Tavuk Göğsü Salatası
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'eff745bb-4187-46e3-a883-44449700ed7d';
-- Tavuk Göğsü Tava
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '5bb75f53-c831-413c-830e-7fe4afa4b44d';
-- Tavuk Göğsülü Sade Sandviç
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = 'de34dfa9-3e83-42f3-9679-5cd1a569da4e';
-- Tavuk Şinitzel
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '895f1c0c-caf8-4911-b64a-5a99d6e3b37d';
-- Tavuk Şiş
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '2660a36f-fe54-44f5-a1ba-9a2ff4bcbc4b';
-- Tavuk Sote ve Pilav
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'c2ce2e7d-4bf1-4cc3-a292-9f05a2e726da';
-- Tavuk Suyu Pirinç Çorbası
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free']::text[] where id = 'd9f725aa-73f9-474d-bd97-13288ba1384f';
-- Tavuk-Patates Tencere
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'e51ebfe0-8a9f-4ecc-9b90-bae1f5892dcd';
-- Tavuklu Bulgur Pilavı
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = 'a2c4a9da-a6dc-4158-a5fb-18e3b5ab99dc';
-- Tavuklu Bulgur Salatası
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '07b866c4-6291-48a7-81cf-127b0cc3c467';
-- Tavuklu Erişte Çorbası
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = 'cf7aa6c1-9c6f-4036-9ace-87d9f8f26e59';
-- Tavuklu Karnabahar Sote
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '412b2c63-d96d-465b-b8bb-fe8a0b5e470e';
-- Tavuklu Karnıyarık
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'ff50cbf4-8a0e-44f2-a058-0bda1e47ce4d';
-- Tavuklu Mantar Sote
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '52e45221-39ed-47c8-b65b-350237332a3e';
-- Tavuklu Patates Salatası
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free']::text[] where id = 'a0978e93-3fec-4361-babf-192a9ff611a2';
-- Tavuklu Sebze Çorbası
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '5b16d059-a49a-4a9e-8a1b-e611ec01e603';
-- Tavuklu Yulaflı Wrap
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '20d9ceab-4c86-460e-8007-033092c595b9';
-- Taze Fasulye Etli
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '18d212ed-568d-4642-89bb-2da2e976db4e';
-- Tencerede Patates Köftesi
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '298a2857-2595-417f-af81-b338b5add691';
-- Tencerede Sebzeli Yumurta
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '7efa29c2-9833-4074-87db-d4f5ba74ec42';
-- Tencerede Tavuk Sote
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '67834090-0185-42a7-8925-492e44b53f59';
-- Tereyağlı Bal Ekmek
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '8f4eb6cc-f675-4723-ba5a-d1e62ea1bce0';
-- Tereyağlı Limonlu Makarna
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'b60d8c64-6d4d-4754-839e-e122280f6693';
-- Tofu Soteli Kahverengi Pirinç
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '2039017c-b2fc-44d3-ac05-a325326d00a4';
-- Ton Balıklı Makarna Salatası
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = 'ed6622d5-b21b-4f28-86f1-154d6ef83cf7';
-- Türlü Sebze Etli
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '4a55cc97-dd46-444f-b962-c1c82660f282';
-- Üzümlü Yulaf
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '7e1dbee0-d866-4a64-90fd-5f9c6bc1b745';
-- Vejetaryen Quinoa Power Bowl
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '22efb9fa-874d-46d8-903b-782ec1e3be41';
-- Yoğurtlu Bulgur Pilavı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '9a482323-a32e-4a11-be56-0f93892aa34c';
-- Yoğurtlu Çikolata Mousse
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '30dd1542-694c-41c6-b366-aa3bcb322c01';
-- Yoğurtlu Çilek Mousse
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '6958c745-30c2-4f24-bad4-17ede84cb2c2';
-- Yoğurtlu Havuç Atıştırması
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '58977a4e-5f05-43ee-a46f-0f5dde8acd25';
-- Yoğurtlu Karnabahar Salatası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '01b44deb-8b04-4002-90f4-48ace32a515c';
-- Yoğurtlu Mercimek Çorbası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '55b6c6b7-35d1-420c-be5e-b4968ce3c530';
-- Yoğurtlu Pancar Salatası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'c1c6d1cf-c67a-4d7b-bc5d-72ad1b6b9a03';
-- Yoğurtlu Patates Salatası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'ab7afeaa-a33a-4e68-85d9-149b89887c8d';
-- Yoğurtlu Patlıcan Ezmesi
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '2a402024-f9a6-4e2e-b035-a00fcc3b52b8';
-- Yoğurtlu Pirinç Çorbası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '438928e0-1c5a-4b8e-9f1c-c50294e2f2eb';
-- Yoğurtlu Pirinç Salatası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = 'e9d5aff9-1f9a-4cb9-a1a4-e32028a59bbd';
-- Yoğurtlu Sade Tavuk Sote
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free']::text[] where id = 'ff397aa1-0a09-4ecc-8238-b97e86884361';
-- Yoğurtlu Salatalık Atıştırması
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '222645a3-d8f9-4eca-b9b5-481c7dfcca05';
-- Yoğurtlu Tavuk Sandviç
update public.recipes set diet_flags = ARRAY['pork_free']::text[] where id = '78feafca-ed22-49b1-8c64-c68d44843708';
-- Yoğurtlu Yumurta Salatası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '098bd57b-7ef4-4efc-9cd0-d18dd4b78050';
-- Yüksek Protein Cheesecake Isırıkları
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '369d92a1-04b8-4a1d-8e05-846308e0ebaf';
-- Yüksek Proteinli Çikolatalı Puding (Sporcu Tatlısı)
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '3d7181e0-2292-41b0-ad95-ffb2aeef7b64';
-- Yulaflı Çikolata Cookie
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '9ba42b13-178c-4fc3-9592-dcebd59090fd';
-- Yulaflı Muzlu Cookie
update public.recipes set diet_flags = ARRAY['vegan', 'vegetarian', 'pork_free', 'dairy_free']::text[] where id = '1ba72b0d-c758-4079-b003-046a53116e0e';
-- Yulaflı Süt Çorbası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'cc93b1d0-d269-4c30-abb1-4b5fecf92cf8';
-- Yulaflı Tarçınlı Smoothie
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'a15821f0-65a7-4cc2-8ccb-75cea69c8665';
-- Yumurta Akı Omleti ve Hindi Eti
update public.recipes set diet_flags = ARRAY['pork_free', 'gluten_free', 'dairy_free']::text[] where id = '686353d1-cb72-47af-ade0-edd250753768';
-- Yumurta Akı ve Sebze Tabağı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '80a4d456-d63c-47a5-9d33-c26834a78b0d';
-- Yumurta-Avokado Tabağı
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'b14140b0-f7a7-47b4-9fcd-65adb196fa7f';
-- Yumurta-Peynirli Sandviç
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '71901285-763d-4e14-985b-f95817427b07';
-- Yumurtalı Domates Sandviç
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'dairy_free']::text[] where id = 'f26ca644-1885-43c5-a598-82d9700694a4';
-- Yumurtalı Erişte
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'ba909998-425f-4e53-b349-cf1fe5ba0f67';
-- Yumurtalı Patates Salatası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free']::text[] where id = '9e8342f0-e081-4c06-a9be-39a18eee8210';
-- Yumurtalı Patates Tava
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = '9ba002a6-d615-4163-bb6a-2448124d5799';
-- Yumurtalı Peynirli Roll
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'c459cbcc-f22f-4d15-964c-7a96e74c2a16';
-- Yumurtalı Sade Krep
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = 'd9bf2b85-3a63-47c5-acdd-91125c95606c';
-- Yumurtalı Sebze Sote
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free', 'gluten_free', 'dairy_free']::text[] where id = 'f38694cd-f14a-4eb3-9f67-5ae004ae5c88';
-- Yumurtalı Sucuklu Tava
update public.recipes set diet_flags = ARRAY['pork_free', 'dairy_free']::text[] where id = '6a9bad45-86a6-4d37-86e2-10e8f37e1de2';
-- Yumurtalı Tarhana Çorbası
update public.recipes set diet_flags = ARRAY['vegetarian', 'pork_free']::text[] where id = '91d0cb99-0c9a-493f-a6b4-d69f44b57be4';

commit;
