-- Roadmap Phase 7 · English recipe titles and instructions.
-- Generated by tool/recipe_pipeline/translations/build_recipe_en.py
-- Do not hand-edit; change recipes_en.py and re-run.
--
-- The INGREDIENTS half is generated from recipe_ingredients, so no
-- quantity or unit passes through a translation. Only the METHOD
-- half is authored.

begin;

update public.recipes set title_en = 'Spicy Tomato Soup', instructions_en = 'INGREDIENTS:
- 4 ripe tomato
- 1 small onion
- 10 ml olive oil
- 1 tsp chilli flakes
- 1 tbsp butter
- salt

METHOD:
1. Fry the onion in the olive oil for 2 minutes.
2. Add the tomatoes and simmer for 6 minutes.
3. Add the salt, chilli flakes and 200 ml of water, then cook for 4 minutes more.
4. Stir the butter into the soup and serve.' where id = 'c7530a54-0946-41fe-a283-20d70fc067de';
update public.recipes set title_en = 'Mediterranean Quinoa Salad', instructions_en = 'INGREDIENTS:
- 100 g quinoa
- 100 g cooked chickpeas
- 1/2 cucumber
- 10 cherry tomatoes
- 30 g low-fat beyaz peynir (Turkish brined white cheese; light feta works)
- 10 olives
- 1 handful parsley
- 15 ml olive oil
- 1 juice of one lemon

METHOD:
1. Boil the quinoa in plenty of water for 15 minutes, then leave it to cool.
2. Dice all the vegetables small.
3. Combine the quinoa, chickpeas, vegetables and cheese.
4. Drizzle with olive oil and lemon juice and serve with parsley.' where id = '3971c479-ce32-4b34-9b9c-013dee1df749';
update public.recipes set title_en = 'Avocado Wholemeal Toast', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 1 ripe avocado
- 2 eggs
- 1 tbsp white vinegar
- 1 tsp lemon juice
- 1 dessertspoon extra virgin olive oil
- chilli flakes, salt and black pepper
- 5 g fresh thyme or parsley

METHOD:
1. Toast the bread in a toaster or dry pan until both sides are golden.
2. Halve the avocado and remove the stone; mash the flesh with a fork and mix in the lemon juice, salt and black pepper.
3. Bring water to the boil in a small pan; once it boils, lower the heat and add the vinegar.
4. Crack each egg into a separate bowl; make a gentle whirlpool in the water and slide the egg in slowly.
5. Poach for 2-3 minutes for a runny yolk, lift out with a slotted spoon and drain on kitchen paper.
6. Spread the mashed avocado generously over the toast and set a poached egg on each slice.
7. Scatter chilli flakes, olive oil and the chopped thyme over the top and serve immediately.' where id = 'eac3e53c-155b-413f-baac-a9a3e8d1e079';
update public.recipes set title_en = 'Avocado and Egg Wholemeal Toast', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 1/2 avocado
- 2 boiled egg
- 1/2 juice of one lemon
- chilli flakes, salt and black pepper
- fresh parsley

METHOD:
1. Toast the bread slices for 2 minutes.
2. Mash the avocado with a fork and mix in the lemon juice and salt.
3. Spread the avocado mixture over the bread.
4. Lay the sliced egg on top and serve with chilli flakes and parsley.' where id = '1fd74b61-7b93-47e9-9de3-111d1bffb6d2';
update public.recipes set title_en = 'Almond Milk Pudding', instructions_en = 'INGREDIENTS:
- 250 ml milk
- 25 g rice flour
- 30 g sugar
- 30 g almonds
- 1 packet vanilla

METHOD:
1. Slake the rice flour with 50 ml of cold milk.
2. Bring the remaining milk to the boil and add the sugar.
3. Add the rice flour mixture and stir for 6 minutes until it thickens.
4. Divide between bowls and finish with vanilla and almonds.' where id = 'a4b2407b-b8c5-42c9-897a-9b278cf09a80';
update public.recipes set title_en = 'Gardener''s Salad', instructions_en = 'INGREDIENTS:
- 2 handfuls lettuce
- 1 tomato
- 1 cucumber
- 1 small green pepper
- 1 small carrot
- 10 ml olive oil

METHOD:
1. Combine all the vegetables in a bowl.
2. Add the olive oil.
3. Season with salt and toss lightly.
4. Serve cold.' where id = '8ee45d41-201d-4070-8125-82572e27e368';
update public.recipes set title_en = 'Vanilla Yogurt with Honey', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 packet vanilla
- 1 tbsp honey
- 15 g walnuts
- 1 pinch cinnamon

METHOD:
1. Stir the vanilla through the yogurt.
2. Spoon into a bowl and drizzle the honey over.
3. Scatter the walnuts.
4. Finish with cinnamon and serve.' where id = '802c2e46-5125-42f5-9587-0b0b3c0f2ce6';
update public.recipes set title_en = 'Lor Cheese with Honey and Walnuts', instructions_en = 'INGREDIENTS:
- 100 g lor cheese (fresh Turkish whey cheese; ricotta is the closest substitute)
- 1 tbsp honey
- 15 g walnuts
- 1 pinch cinnamon
- 1 slice wholemeal bread

METHOD:
1. Spoon the lor cheese into a bowl.
2. Add the walnuts on top.
3. Drizzle the honey over.
4. Finish with cinnamon and serve with bread.' where id = '01115b20-4d27-47af-9ab4-7b7bb0896688';
update public.recipes set title_en = 'Strained Yogurt with Honey and Walnuts', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 tbsp honey
- 15 g walnut halves
- 1 pinch cinnamon

METHOD:
1. Spoon the yogurt into a bowl.
2. Add the honey and walnuts on top.
3. Finish with cinnamon and serve.' where id = '199c2d0f-6762-4ab5-a8e9-43bf797836ce';
update public.recipes set title_en = 'Honey Cinnamon French Toast', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 1 eggs
- 60 ml milk
- 15 g butter
- 2 tbsp honey
- 1 tsp cinnamon

METHOD:
1. Whisk the eggs, milk and cinnamon together.
2. Dip the bread slices in the mixture.
3. Fry each side in the butter for 2 minutes.
4. Drizzle the honey over and serve warm.' where id = '954637ff-d82c-4895-b007-f4a07a5be8be';
update public.recipes set title_en = 'Bazlama Pan Toastie', instructions_en = 'INGREDIENTS:
- 1 bazlama (Turkish flatbread; pita or naan works)
- 40 g beyaz peynir (Turkish brined white cheese; feta works)
- 1 tomato
- 5 olives
- a few fresh mint leaves

METHOD:
1. Split the bazlama through the middle and spread the cheese over the cut face.
2. Add the tomato slices and olives.
3. Heat in a covered pan for 3 minutes.
4. Garnish with mint and serve.' where id = 'f6a99c06-ec20-4ded-ad03-c922b5ce6924';
update public.recipes set title_en = 'Beyaz Peynir with Honey', instructions_en = 'INGREDIENTS:
- 100 g beyaz peynir (Turkish brined white cheese; feta works)
- 1 tbsp honey
- 15 g walnuts
- 1 pinch cinnamon
- 1 slice wholemeal bread

METHOD:
1. Put the beyaz peynir in a bowl and crumble it.
2. Stir in the honey and walnuts.
3. Finish with cinnamon.
4. Serve alongside a slice of bread.' where id = 'c9033734-c8da-49e0-9171-46d203b0c410';
update public.recipes set title_en = 'Beyaz Peynir Crêpes', instructions_en = 'INGREDIENTS:
- 1 eggs
- 60 g flour
- 150 ml milk
- 60 g beyaz peynir (Turkish brined white cheese; feta works)
- 5 g butter
- 1 tbsp chopped parsley

METHOD:
1. Whisk the eggs, flour and milk until smooth.
2. Cook thin crêpes in an oiled pan.
3. Spread the cheese and parsley over half of each crêpe.
4. Fold in half, heat for 1 minute more and serve.' where id = 'ead9815b-2916-4f6d-a6a2-ca4da7e063ad';
update public.recipes set title_en = 'Simple Pasta with Beyaz Peynir', instructions_en = 'INGREDIENTS:
- 100 g pasta
- 60 g beyaz peynir (Turkish brined white cheese; feta works)
- 10 ml olive oil
- 1 tbsp dried mint
- salt

METHOD:
1. Boil the pasta in salted water and drain it.
2. Warm the olive oil in the same pan.
3. Return the pasta, add the cheese and toss together.
4. Garnish with mint and serve hot.' where id = '1b35914c-3679-4653-ba66-6712fe4580ec';
update public.recipes set title_en = 'Wholemeal Toastie with Beyaz Peynir', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 60 g beyaz peynir (Turkish brined white cheese; feta works)
- 1 tomato
- 5 olives
- 1 dessertspoon olive oil
- a few fresh mint leaves

METHOD:
1. Brush one side of each bread slice with olive oil.
2. Crumble the cheese and spread it evenly over the inner faces.
3. Toast in a two-sided sandwich press for 3-4 minutes.
4. Serve with tomato slices, olives and mint.' where id = '3a214fcf-8431-446d-a3c7-c79477ed35c1';
update public.recipes set title_en = 'Rice Pilaf with Beef Sauté', instructions_en = 'INGREDIENTS:
- 60 g rice
- 120 g diced beef
- 1 small onion
- 5 ml olive oil
- 1 tbsp tomato paste
- salt

METHOD:
1. Cook the rice in salted water for 12 minutes and drain.
2. Fry the beef in the olive oil for 4 minutes.
3. Add the onion and tomato paste and cook for 6 minutes more with 100 ml of water.
4. Plate the rice and lay the beef over it.' where id = '69fe7821-da0d-4fde-b922-1bff725ba374';
update public.recipes set title_en = 'Rice Pilaf with Yogurt', instructions_en = 'INGREDIENTS:
- 80 g rice
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 tbsp butter
- salt

METHOD:
1. Rinse the rice and soak it in hot water for 10 minutes.
2. Melt the butter in a pan, add the rice and fry for 1 minute.
3. Add 200 ml of hot water and the salt, cover and cook for 12 minutes.
4. Let the pilaf rest and serve with the yogurt.' where id = 'cfbd5f33-c888-41da-bfff-19dac7bb5464';
update public.recipes set title_en = 'Beef and Pea Stew', instructions_en = 'INGREDIENTS:
- 200 g peas
- 100 g diced beef
- 1 carrot
- 1 small onion
- 5 ml olive oil
- salt

METHOD:
1. Fry the beef in the olive oil for 4 minutes.
2. Add the onion and carrot and cook for 3 minutes more.
3. Add the peas and 150 ml of hot water.
4. Cover, cook for 6 minutes, season with salt and serve.' where id = '5e07f2d7-d319-49df-9594-27625e023968';
update public.recipes set title_en = 'Beef Fillet Burrito', instructions_en = 'INGREDIENTS:
- 1 large wholemeal tortilla
- 160 g grilled beef fillet
- 80 g brown rice
- 80 g kidney beans
- 30 g cheddar cheese
- 1/2 avocado
- 2 tbsp salsa

METHOD:
1. Combine the rice and kidney beans in a bowl.
2. Warm the tortilla lightly in a pan.
3. Lay the rice and bean mixture, beef, cheese, avocado and salsa down the middle.
4. Fold the ends in first, then roll it tightly.
5. Fry each side in a hot pan for 1 minute until golden.' where id = '2cdccaa8-2a84-480c-b763-a58f7098a206';
update public.recipes set title_en = 'Beef Fillet Salad', instructions_en = 'INGREDIENTS:
- 150 g cooked beef fillet
- 2 handfuls rocket (arugula)
- 1 tomato
- 1 cucumber
- 10 ml olive oil
- 1/2 lemon

METHOD:
1. Combine the rocket, tomato and cucumber in a bowl.
2. Lay the beef fillet over the top.
3. Add the olive oil and lemon juice.
4. Season with salt and serve.' where id = 'c44f3263-ab6b-4199-90bc-56597b5711b4';
update public.recipes set title_en = 'Date and Walnut Balls', instructions_en = 'INGREDIENTS:
- 8 dates
- 30 g walnuts
- 15 g desiccated coconut
- 1 tbsp unsweetened cocoa

METHOD:
1. Blitz the dates and walnuts in a food processor.
2. Roll the mixture into walnut-sized balls.
3. Coat the balls first in cocoa, then in desiccated coconut.
4. Chill for 5 minutes and serve.' where id = 'bf0de0db-b6d4-4097-a476-5e885f7df580';
update public.recipes set title_en = 'Caramelised Banana with Walnuts', instructions_en = 'INGREDIENTS:
- 2 banana
- 15 g butter
- 1 tbsp honey
- 20 g walnuts
- 1 pinch cinnamon

METHOD:
1. Melt the butter in a pan and fry the banana slices for 2 minutes a side.
2. Drizzle the honey down the side of the pan.
3. Lift the bananas onto a plate.
4. Scatter the walnuts and cinnamon over and serve warm.' where id = 'a0f69eb5-d78f-4343-ac48-2f3887b6cb07';
update public.recipes set title_en = 'Yogurt Dessert with Walnuts', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 20 g walnuts
- 1 tbsp honey
- 1 pinch cinnamon
- 5 g desiccated coconut

METHOD:
1. Spoon the yogurt into a bowl.
2. Add the honey and walnuts on top.
3. Scatter the cinnamon and desiccated coconut.
4. Serve immediately.' where id = '0a5aa59a-d467-4678-a7ec-88e7d2508a8b';
update public.recipes set title_en = 'Vegan Chia Pancakes', instructions_en = 'INGREDIENTS:
- 80 g wholemeal flour
- 15 g chia seeds
- 200 ml almond milk
- 1 dessertspoon baking powder
- 15 g maple syrup
- 1 dessertspoon vanilla extract
- 80 g fresh blackberries

METHOD:
1. Soak the chia seeds in 45 ml of water for 5 minutes until they swell.
2. Whisk the flour, baking powder, milk, maple syrup, vanilla and the chia gel until smooth.
3. Cook each pancake in a non-stick pan over medium heat for 2 minutes.
4. Stack the pancakes, scatter the blackberries over and serve.' where id = '06619310-0964-4c14-b9bd-76e915fc2379';
update public.recipes set title_en = 'Chia Seed Pudding', instructions_en = 'INGREDIENTS:
- 40 g chia seeds
- 300 ml unsweetened almond milk
- 15 g maple syrup
- 1 dessertspoon vanilla extract
- 80 g fresh strawberries
- 20 g almonds

METHOD:
1. Stir the chia seeds, almond milk, maple syrup and vanilla together in a jar.
2. Refrigerate for at least 4 hours, preferably overnight.
3. In the morning, loosen it with a fork and transfer to a bowl.
4. Scatter the strawberries and almonds over and serve.' where id = '609271de-0d7b-4936-a958-c036c17ce1dc';
update public.recipes set title_en = 'Raw Vegetable Breakfast Plate', instructions_en = 'INGREDIENTS:
- 1 cucumber
- 1 tomato
- 5 olives
- 40 g beyaz peynir (Turkish brined white cheese; feta works)
- 5 ml olive oil
- a few fresh mint leaves

METHOD:
1. Arrange the vegetables on a plate.
2. Set the beyaz peynir and olives to one side.
3. Drizzle olive oil over the top.
4. Garnish with mint and serve.' where id = 'f7bdb1c2-8d2c-49df-81ea-ad6cd959b8b4';
update public.recipes set title_en = 'Crudités with Yogurt Dip', instructions_en = 'INGREDIENTS:
- 1 carrot
- 1 cucumber
- 1 green pepper
- 150 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 clove garlic
- 1 tsp dried mint

METHOD:
1. Cut the vegetables into fingers and arrange them on a plate.
2. Stir the garlic and mint through the yogurt.
3. Put the dip on the plate in a small bowl.
4. Serve immediately.' where id = '9ca7c29f-a84c-4eda-857c-0691ae8b3cf8';
update public.recipes set title_en = 'Chocolate Chia Pudding', instructions_en = 'INGREDIENTS:
- 35 g chia seeds
- 250 ml unsweetened almond milk
- 10 g unsweetened cocoa powder
- 15 g maple syrup
- 1 dessertspoon vanilla extract
- 60 g strawberries

METHOD:
1. Whisk the chia seeds, almond milk, cocoa, maple syrup and vanilla together in a jar.
2. Refrigerate for at least 4 hours, preferably overnight.
3. Loosen it with a fork before serving.
4. Set the strawberries on top and serve.' where id = '6080c19f-9ab2-4b03-b7bb-58714d7af12e';
update public.recipes set title_en = 'Chocolate Banana Protein Shake', instructions_en = 'INGREDIENTS:
- 1 banana
- 300 ml semi-skimmed milk
- 30 g chocolate whey protein powder
- 5 g cocoa powder
- 100 g ice

METHOD:
1. Put all the ingredients in a blender.
2. Blend on high for 45 seconds until smooth.
3. Pour into a tall glass.
4. Dust with cocoa powder if you like and drink immediately.' where id = '480dd7a1-fc9b-457f-93d2-2528f0366e9c';
update public.recipes set title_en = 'Chocolate Protein Pudding', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 25 g chocolate whey protein powder
- 5 g unsweetened cocoa powder
- 15 g honey
- 10 g raw almonds

METHOD:
1. Whisk the yogurt, protein powder and cocoa powder until even.
2. Add the honey and stir again.
3. Transfer to a serving bowl and rest in the fridge for 30 minutes.
4. Scatter the roughly chopped almonds over and serve.' where id = '4363943a-3361-421a-8cc3-3307ca0257a2';
update public.recipes set title_en = 'Chocolate Oat Balls', instructions_en = 'INGREDIENTS:
- 80 g rolled oats
- 2 tbsp unsweetened cocoa
- 2 tbsp honey
- 20 g desiccated coconut
- 15 g peanut butter

METHOD:
1. Knead the oats, cocoa, honey and peanut butter together.
2. Roll the mixture into walnut-sized balls.
3. Coat them in desiccated coconut.
4. Chill for 5 minutes and serve.' where id = '03e58bea-2402-4487-9b18-c3684ba0f036';
update public.recipes set title_en = 'Çılbır — Poached Eggs over Garlic Yogurt', instructions_en = 'INGREDIENTS:
- 2 eggs
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 clove garlic
- 15 g butter
- 1 tsp chilli flakes
- salt

METHOD:
1. Stir the crushed garlic and salt through the yogurt and spread it over a plate.
2. Crack the eggs into boiling water, poach for 3 minutes and drain.
3. Set the eggs on the yogurt.
4. Melt the butter and bloom the chilli flakes in it, then pour it over and serve.' where id = '094b6838-66f7-4f54-a67a-6044c70d8407';
update public.recipes set title_en = 'Scrambled Eggs with Pastırma', instructions_en = 'INGREDIENTS:
- 3 eggs
- 30 g pastırma (air-dried spiced beef; bresaola is the closest substitute)
- 5 ml butter
- 1 tbsp milk
- salt and black pepper

METHOD:
1. Fry the pastırma in a pan for 1 minute.
2. Beat the eggs with the milk and add the seasoning.
3. Pour over the pastırma and scramble for 3 minutes.
4. Plate and serve with the butter.' where id = '3de1e0e6-e7be-4c73-9129-c5ca0af644e8';
update public.recipes set title_en = 'Crispy Fried Egg Sandwich', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 2 eggs
- 5 ml butter
- 1 leaf lettuce
- 1 slice tomato
- salt

METHOD:
1. Fry the eggs in the butter for 3 minutes.
2. Toast the bread slices lightly.
3. Lay the egg, lettuce and tomato on one slice.
4. Season with salt, close with the other slice and serve.' where id = '579c99c8-5802-4707-98e7-36fe6438d3d3';
update public.recipes set title_en = 'Beef Fillet in Tomato Sauce', instructions_en = 'INGREDIENTS:
- 150 g beef fillet
- 2 ripe tomato
- 1 tbsp tomato paste
- 1 small onion
- 10 ml olive oil
- salt

METHOD:
1. Fry the beef fillet in the olive oil for 4 minutes.
2. Add the onion and cook for 2 minutes more.
3. Add the tomato paste and tomatoes and simmer for 5 minutes.
4. Season with salt and serve.' where id = 'dc428047-7628-4933-820e-5748e0865857';
update public.recipes set title_en = 'Köfte in Tomato Sauce', instructions_en = 'INGREDIENTS:
- 200 g köfte mix (packet seasoning mix for Turkish meatballs)
- 2 ripe tomato
- 1 small onion
- 5 ml olive oil
- salt and black pepper

METHOD:
1. Shape the köfte mix into small balls and cook them in a pan for 5 minutes.
2. Fry the onion in olive oil in a separate pan for 2 minutes.
3. Add the tomatoes and simmer for 5 minutes.
4. Add the köfte to the sauce and cook for 2 minutes more.' where id = 'f1a55d77-c62c-4d80-9de1-1c8b1bb8a627';
update public.recipes set title_en = 'Simple Pasta in Tomato Sauce', instructions_en = 'INGREDIENTS:
- 100 g pasta
- 2 tbsp tomato paste
- 1 small onion
- 5 ml olive oil
- salt and black pepper

METHOD:
1. Boil the pasta in salted water according to the packet.
2. Fry the onion in the olive oil for 2 minutes, add the tomato paste and cook for 1 minute more.
3. Loosen the sauce with 100 ml of hot water.
4. Toss the drained pasta through the sauce, season and serve.' where id = 'cd1b5be6-f027-4811-a26b-e1a1c23bbe61';
update public.recipes set title_en = 'Tomato and Beyaz Peynir Plate', instructions_en = 'INGREDIENTS:
- 2 ripe tomato
- 60 g beyaz peynir (Turkish brined white cheese; feta works)
- 5 olives
- 5 ml olive oil
- a few fresh mint leaves

METHOD:
1. Arrange the tomato slices on a plate.
2. Set the beyaz peynir to one side.
3. Add the olives and mint.
4. Drizzle olive oil over and serve.' where id = 'fe2e091e-d258-4a56-a891-097e722572c4';
update public.recipes set title_en = 'Tomato Rice Pilaf', instructions_en = 'INGREDIENTS:
- 80 g rice
- 1 ripe tomato
- 1 small onion
- 1 tbsp butter
- 1 tbsp tomato paste
- salt

METHOD:
1. Fry the onion in the butter for 2 minutes.
2. Add the tomato paste and tomatoes and cook for 2 minutes more.
3. Add the rice and fry for 1 minute.
4. Add 200 ml of hot water and the salt, cover and cook for 12 minutes.' where id = '09e92bc4-5133-4776-b5cc-46d748b3a8cd';
update public.recipes set title_en = 'Simple Chicken with Tomatoes', instructions_en = 'INGREDIENTS:
- 200 g chicken breast
- 2 ripe tomato
- 1 green pepper
- 5 ml olive oil
- salt and black pepper

METHOD:
1. Fry the chicken in the olive oil for 4 minutes.
2. Add the pepper and sauté for 2 minutes.
3. Add the tomatoes and cook for 5 minutes until they release their juice.
4. Season and serve.' where id = '41b68050-bc5d-41c7-b3f2-0807a1c525ff';
update public.recipes set title_en = 'Fried Eggs with Tomato', instructions_en = 'INGREDIENTS:
- 2 eggs
- 1 large ripe tomato
- 5 ml olive oil
- salt and black pepper

METHOD:
1. Warm the olive oil in a pan.
2. Add the chopped tomato and sauté for 2 minutes.
3. Crack the eggs over the top and scatter the seasoning.
4. Cook for 3 minutes until the whites set and serve hot.' where id = '8e695e52-6f78-4f80-86b1-b436b28523d7';
update public.recipes set title_en = 'Frozen Chocolate Banana Slices', instructions_en = 'INGREDIENTS:
- 2 banana
- 40 g dark chocolate
- 15 g desiccated coconut
- 15 g walnuts

METHOD:
1. Melt the chocolate over a bain-marie.
2. Dip the frozen banana slices in the chocolate.
3. Coat them in desiccated coconut and walnuts.
4. Lay them on baking paper and freeze for 3 minutes more.' where id = 'f85fbb18-3b31-465c-8038-c0ef883487fa';
update public.recipes set title_en = 'Frozen Yogurt Bites', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 100 g fresh strawberries
- 1 tbsp honey
- 1 pinch vanilla

METHOD:
1. Mix the yogurt, strawberries, honey and vanilla together.
2. Drop small balls onto baking paper with an ice-cream scoop.
3. Freeze for 5 minutes.
4. Serve immediately.' where id = 'c6265b3a-94ed-4ff5-9de5-74705d390730';
update public.recipes set title_en = 'Apple Slices with Peanut Butter', instructions_en = 'INGREDIENTS:
- 1 medium apple
- 20 g natural peanut butter
- 1 pinch cinnamon

METHOD:
1. Slice the apple thinly.
2. Warm the peanut butter slightly so it runs.
3. Arrange the apple slices on a plate and drizzle the peanut butter over.
4. Scatter cinnamon over and eat straight away.' where id = 'be63a065-aebc-4f62-90ab-1fe8a19e275f';
update public.recipes set title_en = 'Beef and Courgette Stew', instructions_en = 'INGREDIENTS:
- 2 courgette (zucchini)
- 100 g ground beef
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- a few sprigs of fresh dill

METHOD:
1. Fry the ground beef in the olive oil for 4 minutes.
2. Add the onion and tomato paste and cook for 2 minutes more.
3. Add the courgette and 150 ml of hot water.
4. Cover and cook for 6 minutes, then serve with dill.' where id = '31e02a6c-3dd9-42f6-86f2-0e21b7fd1b9f';
update public.recipes set title_en = 'Beef and White Bean Stew', instructions_en = 'INGREDIENTS:
- 200 g cooked white beans
- 100 g diced beef
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- salt

METHOD:
1. Fry the beef in the olive oil for 4 minutes.
2. Add the onion and tomato paste and cook for 2 minutes more.
3. Add the beans and 200 ml of hot water.
4. Cover and simmer for 8 minutes, season with salt and serve.' where id = 'e2b01ed3-a467-4f2e-bf9d-e01f844ae31c';
update public.recipes set title_en = 'Beef and Chickpea Stew', instructions_en = 'INGREDIENTS:
- 200 g cooked chickpeas
- 100 g diced beef
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- salt

METHOD:
1. Fry the beef in the olive oil for 4 minutes.
2. Add the onion and tomato paste and cook for 2 minutes more.
3. Add the chickpeas and 200 ml of hot water.
4. Cover and simmer for 8 minutes, season with salt and serve.' where id = '92fa47af-0825-4c63-8a35-b30799b3e5b1';
update public.recipes set title_en = 'Beef and Chickpea Pilaf', instructions_en = 'INGREDIENTS:
- 80 g rice
- 100 g cooked chickpeas
- 100 g diced beef
- 1 small onion
- 1 tbsp butter
- salt

METHOD:
1. Fry the beef in the butter for 4 minutes.
2. Add the onion and cook for 2 minutes more.
3. Add the rice and chickpeas and fry for 1 minute.
4. Add 250 ml of hot water and the salt, cover and cook for 12 minutes.' where id = '7efe23df-862c-4986-aa7e-34052ee955bf';
update public.recipes set title_en = 'Beef and Leek Stew', instructions_en = 'INGREDIENTS:
- 1 large leek
- 100 g ground beef
- 1 small onion
- 1 tbsp butter
- 1 tbsp tomato paste
- salt

METHOD:
1. Fry the ground beef in the butter for 4 minutes.
2. Add the onion and tomato paste and cook for 2 minutes more.
3. Add the leek and 150 ml of hot water.
4. Cover and simmer for 8 minutes, season with salt and serve.' where id = '469ee18e-bc66-404f-b3b9-f8b58b10ac6a';
update public.recipes set title_en = 'Beef and Vegetable Soup', instructions_en = 'INGREDIENTS:
- 100 g diced beef
- 1 potato
- 1 carrot
- 1 small onion
- 500 ml beef stock
- salt

METHOD:
1. Put the beef in a pan with the stock and simmer for 8 minutes.
2. Add the onion, carrot and potato and cook for 5 minutes more.
3. Season with salt.
4. Serve.' where id = '5aba127a-cf84-4ddc-91b6-6a3028e46b66';
update public.recipes set title_en = 'Tarhana Soup with Beef', instructions_en = 'INGREDIENTS:
- 30 g tarhana (Turkish fermented soup base of wheat, yoghurt and vegetables; sold dried)
- 100 g ground beef
- 1 tbsp tomato paste
- 1 tbsp butter
- 500 ml water
- salt

METHOD:
1. Fry the ground beef in the butter for 4 minutes and add the tomato paste.
2. Slake the tarhana with 100 ml of cold water, add the remaining 400 ml and bring it to the boil.
3. Add the loosened tarhana to the pan with the beef.
4. Cook for 6 minutes more, season with salt and serve.' where id = '0509dfaa-cf63-40d9-8290-6f091bd28a18';
update public.recipes set title_en = 'Homemade Potato Crisps', instructions_en = 'INGREDIENTS:
- 2 potato
- 5 ml olive oil
- 1 tsp chilli flakes
- salt

METHOD:
1. Toss the potato slices with the olive oil, salt and spices.
2. Cook each side for 5 minutes in a non-stick pan.
3. Turn them now and then until crisp.
4. Serve hot.' where id = '5b77fd24-b9e5-49cf-ad54-2f776e45bec9';
update public.recipes set title_en = 'Homemade Protein Bars', instructions_en = 'INGREDIENTS:
- 50 g rolled oats
- 25 g vanilla whey protein powder
- 20 g natural peanut butter
- 15 g honey
- 10 g dark chocolate chips
- 60 ml milk

METHOD:
1. Combine all the dry ingredients in a bowl.
2. Add the peanut butter, honey and milk and work it into an even dough.
3. Press it into a non-stick tin and scatter the chocolate chips over the top.
4. Rest in the fridge for 1 hour, then cut into 4 bars to store.' where id = 'd46c5a04-cc09-4e56-a006-a75a9e98300a';
update public.recipes set title_en = 'Ezogelin Soup', instructions_en = 'INGREDIENTS:
- 60 g red lentils
- 30 g fine bulgur
- 1 tbsp tomato paste
- 1 small onion
- 1 tbsp butter
- 1 tsp dried mint

METHOD:
1. Fry the onion in the butter for 2 minutes and add the tomato paste.
2. Add the lentils, bulgur and 600 ml of water and bring to the boil.
3. Simmer over low heat for 10 minutes.
4. Season with mint and serve.' where id = 'ad98f215-fac6-4dcc-a7b7-41906f8862f4';
update public.recipes set title_en = 'Baked Salmon with Sweet Potato Mash', instructions_en = 'INGREDIENTS:
- 170 g salmon fillet
- 250 g sweet potato
- 80 g spinach
- 10 ml olive oil
- 1 clove garlic
- fresh dill, salt and black pepper

METHOD:
1. Boil the sweet potatoes in salted water for 12 minutes, drain and mash them.
2. Rub the salmon with dill, garlic and salt and bake at 180 degrees for 14 minutes.
3. Sauté the spinach in the olive oil for 2 minutes.
4. Bring the sweet potato mash, spinach and salmon together on the plate and serve.' where id = '6fe3d2ec-cbae-4325-9af2-36c442ddb89e';
update public.recipes set title_en = 'Baked Cinnamon Apples', instructions_en = 'INGREDIENTS:
- 2 medium apple
- 1 dessertspoon cinnamon
- 10 g honey
- 15 g raw walnuts
- 1 pinch nutmeg

METHOD:
1. Core the apples and cut them into 4 pieces.
2. Lay them on baking paper and drizzle the honey and cinnamon over.
3. Bake at 180 degrees for 15 minutes.
4. Serve hot with the walnut pieces and nutmeg.' where id = '79b6a605-3578-46b8-b3aa-45c9d5224c14';
update public.recipes set title_en = 'Baked Turkey with Brown Rice', instructions_en = 'INGREDIENTS:
- 200 g turkey breast fillet
- 90 g brown rice
- 100 g mushrooms
- 1 clove garlic
- 10 ml olive oil
- oregano, salt and black pepper

METHOD:
1. Cook the rice in plenty of water for 25 minutes.
2. Rub the turkey with thyme, garlic and the spices.
3. Transfer to a baking tray and bake at 200 degrees for 20 minutes.
4. Add the mushrooms for the last 6 minutes and cook them together.
5. Plate the rice and lay the turkey and mushrooms over it.' where id = 'b3c75b75-78ec-4cd6-8a8a-9b9b1c7d71f1';
update public.recipes set title_en = 'Baked Sea Bass with Couscous', instructions_en = 'INGREDIENTS:
- 180 g sea bass fillet
- 80 g couscous
- 1 lemon
- 1 clove garlic
- 10 ml olive oil
- fresh dill
- salt and black pepper

METHOD:
1. Set the sea bass on baking paper.
2. Top it with the garlic, dill, lemon slices and a little olive oil.
3. Bake in a preheated 180-degree oven for 15 minutes.
4. Steep the couscous in hot water for 5 minutes and fluff it with a fork.
5. Bring the couscous and sea bass together on the plate and serve.' where id = '15ae600f-6c57-491b-99b5-e2a6a926f0bf';
update public.recipes set title_en = 'Oven-Baked Salmon and Sweet Potato', instructions_en = 'INGREDIENTS:
- 170 g salmon fillet
- 200 g sweet potato
- 100 g broccoli
- 15 ml olive oil
- 1 clove garlic
- fresh dill, salt and black pepper

METHOD:
1. Toss the sweet potatoes with olive oil, salt and black pepper and bake at 200 degrees for 25 minutes.
2. Rub the salmon with dill and crushed garlic and add it to the tray for the last 12 minutes.
3. Steam the broccoli for 4 minutes.
4. Set the potato and broccoli beside the salmon and serve.' where id = '0f1fdd30-f916-4c85-964e-aa3e96a8f39b';
update public.recipes set title_en = 'Roasted Salmon and Sweet Potato', instructions_en = 'INGREDIENTS:
- 180 g salmon fillet
- 250 g sweet potato
- 120 g asparagus
- 1 clove garlic
- 15 ml extra virgin olive oil
- 1/2 lemon
- 1 sprig fresh thyme
- salt, black pepper and chilli flakes

METHOD:
1. Preheat the oven to 200 degrees and line a tray with baking paper.
2. Toss the sweet potato slices with half the olive oil, salt and chilli flakes and spread them in a single layer on one side of the tray; bake for 15 minutes.
3. Take the tray out and add the asparagus to the other side; set the salmon in the middle, skin-side down.
4. Rub the salmon with salt, black pepper and crushed garlic; lay the lemon slices and thyme sprig on top and drizzle the remaining oil over.
5. Return the tray to the oven and bake for 12-14 minutes more (the salmon should still look faintly pink in the middle).
6. Rest for 2 minutes, plate and serve hot.' where id = 'ec313347-045d-4edf-9c73-653df84e8591';
update public.recipes set title_en = 'Vegan Peanut Butter Banana Smoothie', instructions_en = 'INGREDIENTS:
- 1 frozen banana
- 300 ml oat milk
- 20 g natural peanut butter
- 15 g unsweetened cocoa powder
- 10 g plant protein powder
- 5 g date syrup
- 100 g ice

METHOD:
1. Put all the ingredients in a blender.
2. Blend on high for 60 seconds until it is a smooth drink.
3. Pour into a tall glass.
4. Dust a little cocoa powder over if you like and drink immediately.' where id = '265ad055-2146-494e-af57-271ad6154a66';
update public.recipes set title_en = 'Peanut Butter Banana Porridge', instructions_en = 'INGREDIENTS:
- 80 g rolled oats
- 250 ml milk
- 1 banana
- 30 g natural peanut butter
- 20 g chia seeds
- 15 g honey
- cinnamon

METHOD:
1. Cook the oats in the milk over low heat for 6-8 minutes until thick.
2. Transfer to a bowl and lay the sliced banana on top.
3. Swirl the peanut butter through with a spoon.
4. Finish with chia seeds, honey and cinnamon and serve hot.' where id = '061a039b-a898-4991-a058-33e23ac7538f';
update public.recipes set title_en = 'Peanut Butter Protein Porridge', instructions_en = 'INGREDIENTS:
- 60 g rolled oats
- 250 ml semi-skimmed milk
- 30 g vanilla whey protein powder
- 20 g natural peanut butter
- 1/2 banana
- 1 dessertspoon chia seeds
- cinnamon

METHOD:
1. Cook the oats in the milk over low heat for 6 minutes.
2. Take it off the heat and stir the protein powder in once it has cooled slightly.
3. Transfer to a bowl and top with the banana, peanut butter and chia seeds.
4. Scatter cinnamon over and serve hot.' where id = '01370365-605e-4ceb-8e99-c76ae07595bf';
update public.recipes set title_en = 'Peanut Butter Oat Porridge', instructions_en = 'INGREDIENTS:
- 50 g rolled oats
- 250 ml skimmed milk
- 1 tbsp natural peanut butter
- 1 ripe banana
- 10 g walnut halves
- 1 dessertspoon honey or maple syrup
- 1 a pinch of cinnamon
- 1 tsp chia seeds

METHOD:
1. Put the oats and milk in a small pan and bring to the boil over medium heat, stirring occasionally.
2. Once it boils, lower the heat and cook for 4-5 minutes more until creamy.
3. Take the pan off the heat, add the chia seeds and leave it to rest for 1 minute.
4. Transfer to a bowl; add the peanut butter while it is still warm so it melts in.
5. Scatter the sliced banana, walnut pieces and cinnamon, sweeten with honey and serve hot.' where id = '5fa526b5-3cdd-4abb-8ae6-a317870fba61';
update public.recipes set title_en = 'Pan-Fried Anchovies', instructions_en = 'INGREDIENTS:
- 200 g anchovies (fresh Black Sea anchovies; sardines work)
- 50 g cornflour (cornstarch)
- 10 ml sunflower oil
- 1/2 lemon
- salt
- black pepper

METHOD:
1. Season the anchovies with salt and black pepper.
2. Coat them in cornflour.
3. Fry in hot oil for 4 minutes until both sides are golden.
4. Serve with lemon.' where id = 'e9b728ed-f7f7-47eb-ba79-27d2921eb6a1';
update public.recipes set title_en = 'Mustard Chicken Salad', instructions_en = 'INGREDIENTS:
- 120 g cooked chicken breast
- 2 handfuls lettuce
- 1 tbsp strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 tsp mustard
- 5 ml olive oil
- salt

METHOD:
1. Whisk the yogurt, mustard, olive oil and salt together.
2. Put the lettuce in a bowl and lay the chicken over it.
3. Drizzle the dressing over.
4. Toss lightly and serve.' where id = 'c3e6db2d-8a34-4134-80d1-213707c2db12';
update public.recipes set title_en = 'Boiled Eggs and Tomato', instructions_en = 'INGREDIENTS:
- 2 eggs
- 1 tomato
- 5 olives
- 1 pinch black pepper
- 1 pinch salt
- a few sprigs of fresh parsley

METHOD:
1. Put the eggs in cold water and bring to the boil, then cook for 8 minutes more.
2. Cool them in cold water, peel and halve them.
3. Slice the tomato and arrange it on a plate with the olives.
4. Set the eggs on the plate and scatter salt, black pepper and parsley over.' where id = '4a7ce8ad-cc7e-4f69-ba67-3ee2827a4cbf';
update public.recipes set title_en = 'Quick Çiğ Köfte', instructions_en = 'INGREDIENTS:
- 100 g çiğ köfte mix (packet bulgur-and-spice mix; no raw meat in the modern version)
- 2 handfuls lettuce
- 1/2 lemon
- 1 slice bread

METHOD:
1. Knead the çiğ köfte mix according to the packet.
2. Shape it into small balls.
3. Wrap them in lettuce leaves.
4. Serve with lemon.' where id = 'c8145ef3-213a-44fe-8f6c-e6bd8e1c66e4';
update public.recipes set title_en = 'Pan-Fried Halloumi', instructions_en = 'INGREDIENTS:
- 100 g halloumi
- 5 ml olive oil
- 1 slice wholemeal bread
- 5 olives
- a few fresh mint leaves
- 1/2 lemon

METHOD:
1. Warm a pan with the olive oil.
2. Fry the halloumi slices for 2 minutes a side until golden.
3. Plate them alongside the bread, olives and mint.
4. Squeeze the lemon over and serve.' where id = '1365f62b-8998-4cb5-af9e-47b2d478c028';
update public.recipes set title_en = 'Turkey Lettuce Wrap', instructions_en = 'INGREDIENTS:
- 100 g turkey breast
- 4 large lettuce leaf
- 1 tbsp strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 tsp mustard
- 1/4 cucumber
- salt

METHOD:
1. Mix the yogurt and mustard together.
2. Lay the turkey, cucumber and dressing on a lettuce leaf.
3. Season with salt.
4. Roll the lettuce up tightly and serve.' where id = 'd3375cf6-45a4-491a-9003-ad76cb56fe6d';
update public.recipes set title_en = 'Quick Turkey Bulgur', instructions_en = 'INGREDIENTS:
- 80 g coarse bulgur
- 120 g turkey breast
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- salt

METHOD:
1. Fry the onion in the olive oil for 2 minutes.
2. Add the turkey and cook for 4 minutes until it changes colour.
3. Add the tomato paste, bulgur and 200 ml of hot water.
4. Cover, cook for 8 minutes and serve.' where id = 'ef148018-5d33-405f-b384-3c5bb3deb675';
update public.recipes set title_en = 'Turkey Köfte with Yogurt', instructions_en = 'INGREDIENTS:
- 150 g ground turkey
- 30 g breadcrumbs
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 small onion
- 5 ml olive oil
- salt

METHOD:
1. Knead the ground turkey, breadcrumbs, onion and salt together.
2. Shape into balls and cook in the olive oil for 6 minutes.
3. Turn them and cook for 4 minutes more.
4. Set them on the yogurt and serve.' where id = '14c3b11e-12c0-4df0-9aad-e46a187158ef';
update public.recipes set title_en = 'Turkey and Avocado Wrap', instructions_en = 'INGREDIENTS:
- 1 large wholemeal tortilla
- 120 g sliced turkey breast
- 1/2 avocado
- 1 handful rocket (arugula)
- 1 tomato
- 1 tbsp hummus
- 1 dessertspoon lemon juice

METHOD:
1. Warm the tortilla lightly in a pan.
2. Mash the avocado with the lemon juice and spread it on the tortilla.
3. Layer the hummus, turkey, rocket and tomato in turn.
4. Roll it tightly, cut it in half and serve immediately.' where id = '8228b6bf-ccd5-48a9-ac76-0b460b8705d9';
update public.recipes set title_en = 'Turkey Köfte with Grilled Courgette', instructions_en = 'INGREDIENTS:
- 180 g ground turkey
- 1 tbsp wholemeal breadcrumbs
- 1/4 onion
- 1 clove garlic
- 1 large courgette (zucchini)
- 10 ml olive oil
- oregano, cumin, salt and black pepper

METHOD:
1. Knead the ground turkey, breadcrumbs, onion, garlic and spices together and shape 6 köfte.
2. Cook the köfte in a non-stick pan for 4 minutes a side.
3. Grill the courgette slices for 3 minutes.
4. Plate the köfte with the courgette, drizzle with olive oil and serve.' where id = '0a65ccaa-a01c-4175-8449-d109e259df39';
update public.recipes set title_en = 'Turkey Salami Plate', instructions_en = 'INGREDIENTS:
- 80 g turkey salami
- 1 slice wholemeal bread
- 1 slice tomato
- 5 olives
- 30 g beyaz peynir (Turkish brined white cheese; feta works)
- a few fresh mint leaves

METHOD:
1. Arrange the turkey salami slices on a plate.
2. Set the beyaz peynir and olives to one side.
3. Add the tomato and bread.
4. Serve with mint.' where id = '929cec78-41c6-4e84-8e35-8d99640ee65b';
update public.recipes set title_en = 'Turkey Salami and Eggs', instructions_en = 'INGREDIENTS:
- 2 eggs
- 60 g turkey salami
- 5 ml olive oil
- 1 slice wholemeal bread
- a few sprigs of fresh parsley
- salt

METHOD:
1. Fry the salami slices in a pan for 1 minute.
2. Crack the eggs over the top and scatter the salt.
3. Take the pan off the heat once the eggs have set.
4. Serve with bread and parsley.' where id = 'ae78bbea-cfda-468e-908f-db8ae1d3b49e';
update public.recipes set title_en = 'Pasta with Turkey Sauce', instructions_en = 'INGREDIENTS:
- 100 g pasta
- 100 g turkey breast
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- salt

METHOD:
1. Boil the pasta in salted water and drain it.
2. Fry the onion in the olive oil for 2 minutes.
3. Add the turkey and cook for 4 minutes, add the tomato paste and simmer with 100 ml of water for 2 minutes.
4. Toss the pasta through the sauce and serve.' where id = 'b2ff317e-fb38-48ed-9412-88d86e852f62';
update public.recipes set title_en = 'Turkey Yogurt Wrap', instructions_en = 'INGREDIENTS:
- 1 lavash (thin Turkish flatbread; a large tortilla works)
- 100 g cooked turkey breast
- 100 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 2 leaves lettuce
- 1 slice tomato
- salt

METHOD:
1. Lay the lavash out flat.
2. Spread the yogurt over it and season with salt.
3. Lay out the lettuce, tomato and turkey.
4. Roll it up tightly, cut it in half and serve.' where id = '6a0ce3d2-89f6-4f36-9279-2a8fbcd7923a';
update public.recipes set title_en = 'Coconut Chia Pudding', instructions_en = 'INGREDIENTS:
- 25 g chia seeds
- 250 ml coconut milk
- 1 tbsp honey
- 20 g desiccated coconut
- 1 banana

METHOD:
1. Whisk the chia, milk and honey together and rest for 10 minutes.
2. Stir again and divide between bowls.
3. Add the banana slices and desiccated coconut.
4. Serve cold.' where id = 'ab7df82a-8a39-449a-b187-c66ede193752';
update public.recipes set title_en = 'Coconut Milk Pudding', instructions_en = 'INGREDIENTS:
- 250 ml milk
- 25 g rice flour
- 30 g sugar
- 20 g desiccated coconut
- 1 packet vanilla

METHOD:
1. Slake the rice flour with 50 ml of cold milk.
2. Bring the remaining milk to the boil and add the sugar and vanilla.
3. Add the rice flour mixture and stir for 6 minutes until it thickens.
4. Divide between bowls and scatter the coconut over the top.' where id = '56b3ce28-d009-47be-9ff1-fd5c8a6c32dc';
update public.recipes set title_en = 'Quick Semolina Halva', instructions_en = 'INGREDIENTS:
- 100 g semolina
- 50 g butter
- 60 g sugar
- 300 ml milk
- 15 g pine nuts

METHOD:
1. Toast the pine nuts in the butter for 1 minute.
2. Add the semolina and toast for 4 minutes until it turns golden.
3. Add the milk and sugar and stir until it thickens.
4. Take it off the heat, rest for 5 minutes, press into a mould and serve.' where id = '2fe3d9aa-ef47-4b8c-9694-d07190f0ac12';
update public.recipes set title_en = 'Quick Crêpes with Jam', instructions_en = 'INGREDIENTS:
- 2 eggs
- 60 g flour
- 150 ml milk
- 5 ml butter
- 2 tbsp jam

METHOD:
1. Whisk the eggs, flour and milk until smooth.
2. Pour a little batter into an oiled pan and cook thin crêpes (1-2 minutes each).
3. Fill the crêpes with jam and roll them up.
4. Plate and serve.' where id = '8052bba5-2a2a-4167-84f6-71d3743b9711';
update public.recipes set title_en = 'Quick White Bean Stew', instructions_en = 'INGREDIENTS:
- 200 g cooked white beans
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- 1 tsp chilli flakes
- salt

METHOD:
1. Fry the onion in the olive oil for 2 minutes.
2. Add the tomato paste and fry for 1 minute more.
3. Add the beans and 200 ml of hot water and simmer for 8 minutes.
4. Season with chilli flakes and salt and serve.' where id = 'c319deb7-b804-4533-af20-736064c529d3';
update public.recipes set title_en = 'Quick Lentil Köfte', instructions_en = 'INGREDIENTS:
- 200 g cooked red lentils
- 30 g fine bulgur
- 1 small onion
- 1 tsp olive oil
- a pinch of fresh parsley
- 1/2 lemon

METHOD:
1. Chop the onion very fine and sauté it in the olive oil for 2 minutes.
2. Put the hot lentils and bulgur in a bowl, add the sautéed onion and knead together.
3. Rest the mixture for 5 minutes and shape small köfte in your hand.
4. Scatter parsley over and serve with lemon.' where id = 'da31c81d-fd52-459a-a8f3-46f8d5a715b5';
update public.recipes set title_en = 'Quick Lokma', instructions_en = 'INGREDIENTS:
- 80 g flour
- 1 packet yeast
- 200 ml lukewarm water
- 50 g sugar
- 30 ml sunflower oil
- 1 tbsp honey

METHOD:
1. Mix the flour, yeast and water in a bowl and let it prove for 5 minutes.
2. Heat the oil and drop small spoonfuls of the batter in.
3. Fry for 4 minutes until golden.
4. Steep in the sugar and honey syrup and serve.' where id = '3c296846-e695-48c8-b4ff-8c89a1585d29';
update public.recipes set title_en = 'Quick Chicken Cutlets', instructions_en = 'INGREDIENTS:
- 200 g chicken cutlet
- 5 ml olive oil
- 1 clove garlic
- 1/2 lemon
- salt and black pepper

METHOD:
1. Marinate the cutlets in the olive oil, garlic, lemon and spices for 5 minutes.
2. Cook each side for 4 minutes in a hot griddle pan.
3. Cover and rest for 2 minutes.
4. Serve hot.' where id = '99c97c76-6ffa-44d5-b6b3-28e0f0861638';
update public.recipes set title_en = 'Quick Lentil Soup with Egg', instructions_en = 'INGREDIENTS:
- 1 small jar of cooked red lentils
- 1 eggs
- 1/2 lemon
- 1 tbsp butter
- 1 tsp chilli flakes
- 1 pinch salt

METHOD:
1. Put the lentils and their liquid in a pan and bring to the boil.
2. Beat the egg and add it to the pan in a thin stream, stirring constantly.
3. Add the salt and simmer for 2 minutes more.
4. Melt the butter and bloom the chilli flakes in it, pour it over the soup and serve with lemon.' where id = 'bf56330b-1533-4aac-8a28-1ea1d5e367ad';
update public.recipes set title_en = 'Spinach and Cheese Omelette', instructions_en = 'INGREDIENTS:
- 3 whole egg
- 1 handful baby spinach
- 30 g low-fat beyaz peynir (Turkish brined white cheese; light feta works)
- 5 ml olive oil
- salt, black pepper and fresh dill

METHOD:
1. Beat the eggs and add the salt and black pepper.
2. Warm the olive oil in a non-stick pan and sauté the spinach for 1 minute.
3. Pour in the egg mixture and cook over medium heat until the edges set.
4. Scatter the cheese and dill over, fold the omelette in half and serve hot.' where id = '3208f001-4786-4e84-b679-203ccc625390';
update public.recipes set title_en = 'Grilled Beef Fillet with Broccoli', instructions_en = 'INGREDIENTS:
- 200 g beef sirloin
- 200 g broccoli
- 15 g butter
- 2 cloves garlic
- 10 ml olive oil
- 1 sprig fresh rosemary
- salt and black pepper

METHOD:
1. Take the beef out of the fridge 30 minutes before cooking and bring it to room temperature.
2. Sear each side for 3 minutes over high heat in a cast-iron pan.
3. Lower the heat; add the butter, garlic and rosemary and baste the beef with the fat.
4. Sauté the broccoli in olive oil in a separate pan for 4 minutes.
5. Rest the beef for 5 minutes, slice it and serve with the broccoli.' where id = '2412acfb-f68c-47e9-8de0-90571cd2c809';
update public.recipes set title_en = 'Grilled Beef Fillet with Roasted Vegetables', instructions_en = 'INGREDIENTS:
- 180 g beef sirloin
- 1 aubergine (eggplant)
- 1 courgette (zucchini)
- 1 red pepper
- 10 ml olive oil
- 2 cloves garlic
- rosemary, salt and black pepper

METHOD:
1. Toss the vegetables with olive oil, crushed garlic and the spices.
2. Roast at 200 degrees for 18 minutes.
3. Bring the beef to room temperature and sear each side for 3 minutes in a cast-iron pan.
4. Rest for 5 minutes, slice and serve with the vegetables.' where id = '0a1cf981-c51a-4b61-9d9b-e9693c4a62d7';
update public.recipes set title_en = 'Grilled Turkey Rice Bowl', instructions_en = 'INGREDIENTS:
- 160 g turkey breast fillet
- 70 g brown rice
- 100 g grilled courgette (zucchini)
- 100 g roasted red pepper
- 5 ml olive oil
- 1 clove garlic
- oregano, salt and black pepper

METHOD:
1. Cook the rice in plenty of water for 25 minutes.
2. Marinate the turkey with garlic, thyme and the spices and grill each side for 3 minutes.
3. Grill the courgette and pepper for 4 minutes.
4. Combine the rice, vegetables and sliced turkey in a bowl and serve.' where id = 'acccd4e0-c701-499e-8292-f75a7e58e357';
update public.recipes set title_en = 'Grilled Shrimp and Rocket Salad', instructions_en = 'INGREDIENTS:
- 150 g peeled shrimp
- 50 g rocket (arugula)
- 1/2 avocado
- 10 cherry tomatoes
- 10 ml olive oil
- 2 cloves garlic
- 1 grated zest of one lemon
- chilli flakes

METHOD:
1. Marinate the shrimp with garlic, lemon zest and chilli flakes for 10 minutes.
2. Cook them in a dry non-stick pan for 3 minutes, turning.
3. Arrange the rocket, sliced avocado and cherry tomatoes on a plate.
4. Lay the shrimp over the top, drizzle with olive oil and serve.' where id = '60b70292-54c6-4f0f-8433-2d56e2b6c2a8';
update public.recipes set title_en = 'Grilled Sea Bass with Steamed Vegetables', instructions_en = 'INGREDIENTS:
- 180 g sea bass fillet
- 120 g broccoli
- 100 g carrot
- 80 g courgette (zucchini)
- 10 ml olive oil
- 1 lemon
- fresh dill, salt and black pepper

METHOD:
1. Marinate the sea bass with lemon slices and dill.
2. Steam the vegetables for 6 minutes.
3. Griddle the sea bass in a non-stick pan for 3 minutes a side.
4. Drizzle with olive oil and serve with the vegetables.' where id = 'c93acf1e-8896-41a5-9b38-d85a6786f361';
update public.recipes set title_en = 'Tuna Salad with Grilled Vegetables', instructions_en = 'INGREDIENTS:
- 120 g drained canned tuna
- 1 handful lettuce leaf
- 1/2 cucumber
- 1 tomato
- 50 g grilled courgette (zucchini)
- 30 g roasted red pepper
- 10 ml olive oil
- 1 dessertspoon lemon juice

METHOD:
1. Roughly chop the lettuce, cucumber and tomato into a wide bowl.
2. Slice the grilled vegetables and add them.
3. Spread the tuna over the salad.
4. Whisk the olive oil and lemon juice together, drizzle over the salad and serve.' where id = '24b0010a-1211-4d6a-b238-8a7e07197328';
update public.recipes set title_en = 'Grilled Salmon and Sweet Potato', instructions_en = 'INGREDIENTS:
- 150 g salmon
- 200 g sweet potato
- asparagus
- olive oil

METHOD:
1. Bake the sweet potatoes in the oven.
2. Cook the salmon in a pan or in the oven.
3. Sauté the asparagus.
4. Arrange everything on the plate.' where id = 'b3939d44-6c10-40b9-ac03-02728edb3828';
update public.recipes set title_en = 'Grilled Chicken Quinoa Bowl', instructions_en = 'INGREDIENTS:
- 180 g chicken breast fillet
- 60 g quinoa
- 1 handful baby spinach leaves
- 1/2 avocado
- 10 ml olive oil
- 1 dessertspoon lemon juice
- salt, black pepper and cumin

METHOD:
1. Boil the quinoa in three times its volume of water for 15 minutes and drain.
2. Marinate the chicken with salt, black pepper and cumin and cook each side for 3 minutes on a hot griddle.
3. Layer the quinoa, spinach and sliced avocado in a bowl.
4. Slice the chicken over the top, drizzle with the olive oil and lemon dressing and serve.' where id = 'ab7a79b3-fa9c-4976-bd6c-ff44b13f6ca1';
update public.recipes set title_en = 'Grilled Chicken Light Caesar Salad', instructions_en = 'INGREDIENTS:
- 150 g chicken breast fillet
- 1 large handful of lettuce
- 20 g parmesan cheese
- 20 g wholemeal croutons
- 1 tbsp fat-free yogurt
- 1 dessertspoon dijon mustard
- 5 ml olive oil
- salt, black pepper and garlic powder

METHOD:
1. Marinate the chicken with garlic powder, salt and black pepper and grill each side for 4 minutes.
2. Whisk the yogurt, mustard, olive oil and a pinch of salt into a light Caesar dressing.
3. Toss the lettuce through the dressing and add the parmesan and croutons.
4. Slice the rested chicken over the top and serve.' where id = '4de04113-29b9-49f8-9b7f-9048a096b5a6';
update public.recipes set title_en = 'Grilled Chicken Quinoa Salad', instructions_en = 'INGREDIENTS:
- 150 g chicken breast fillet
- 50 g quinoa
- 1 handful rocket (arugula)
- 1/2 cucumber
- 8 cherry tomatoes
- 30 g light beyaz peynir (Turkish brined white cheese; light feta works)
- 10 g sunflower seeds
- 15 ml extra virgin olive oil
- 1 tbsp lemon juice
- salt, black pepper and oregano

METHOD:
1. Rinse the quinoa under running water and cook it in 150 ml of boiling water over low heat for 15 minutes; once the water is absorbed, cover and rest for 5 minutes more.
2. Rub the chicken breast with salt, black pepper and thyme; cook each side for 4 minutes in a hot griddle pan and rest for 2 minutes.
3. Combine the cooked quinoa, rocket, cucumber, cherry tomatoes and cheese cubes in a wide salad bowl.
4. Cut the chicken into thick slices on the diagonal and lay them over the salad.
5. Whisk the olive oil and lemon juice in a small bowl and drizzle it over the salad.
6. Scatter the sunflower seeds and serve immediately.' where id = 'c8669e27-8430-4b97-b127-902e9d342e71';
update public.recipes set title_en = 'Cocoa Date Balls', instructions_en = 'INGREDIENTS:
- 8 dates
- 30 g almonds
- 1 tbsp unsweetened cocoa
- 15 g desiccated coconut
- 1 pinch salt

METHOD:
1. Blitz the dates and almonds in a food processor.
2. Add the salt and knead.
3. Roll into walnut-sized balls and coat them first in cocoa, then in desiccated coconut.
4. Chill for 5 minutes and serve.' where id = '5b7da9b2-8a49-41c4-b8de-f33fcc5c8df4';
update public.recipes set title_en = 'Cocoa Oat Porridge', instructions_en = 'INGREDIENTS:
- 50 g rolled oats
- 250 ml milk
- 1 tbsp unsweetened cocoa
- 1 tbsp honey
- 1 pinch cinnamon

METHOD:
1. Put the milk and oats in a pan and bring to the boil over medium heat.
2. Add the cocoa and stir it in without letting it clump.
3. Cook for 3 minutes more and transfer to a bowl.
4. Finish with honey and cinnamon and serve hot.' where id = '5792cbe9-8e95-412b-8dbd-b0efb16dd4ac';
update public.recipes set title_en = 'Black Sea Kuymak', instructions_en = 'INGREDIENTS:
- 100 g cornflour (cornstarch)
- 80 g fresh cheese
- 30 g butter
- 250 ml water
- salt

METHOD:
1. Melt the butter in a pan.
2. Add the cornflour and toast for 3 minutes.
3. Add the water a little at a time, stirring until it thickens.
4. Add the cheese and serve once it pulls into strands.' where id = 'd9f69821-6787-4c7b-9976-8895e469a101';
update public.recipes set title_en = 'Yogurt with Caramel Sauce', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 30 g sugar
- 15 g butter
- 50 ml milk
- 1 pinch salt

METHOD:
1. Caramelise the sugar in a pan over medium heat.
2. Add the butter, milk and salt and stir until smooth.
3. Let the sauce cool.
4. Drizzle it over the yogurt and serve.' where id = 'db694232-06a0-4c0d-b6c8-61ec39b5e63e';
update public.recipes set title_en = 'Shrimp Stir Fry with Jasmine Rice', instructions_en = 'INGREDIENTS:
- 180 g peeled shrimp
- 80 g jasmine rice
- 1 red pepper
- 1 carrot
- 1 spring onion
- 2 tbsp low-salt soy sauce
- 5 ml sesame oil
- 1 clove garlic and fresh ginger

METHOD:
1. Cook the rice for 12 minutes according to the packet.
2. Sauté the shrimp with the garlic and ginger for 2 minutes.
3. Add the vegetables and toss over high heat for 3 minutes.
4. Add the soy sauce and sesame oil and cook for 1 minute more.
5. Spoon over the rice and serve.' where id = '3e043a68-54a5-4e15-a471-622ac2197d23';
update public.recipes set title_en = 'Mixed Olive and Cheese Plate', instructions_en = 'INGREDIENTS:
- 10 olives
- 60 g beyaz peynir (Turkish brined white cheese; feta works)
- 5 ml olive oil
- 1 tsp dried oregano

METHOD:
1. Arrange the olives on a plate.
2. Set the beyaz peynir to one side.
3. Scatter olive oil and oregano over the top.
4. Serve.' where id = '5cb601b2-1492-459e-bae2-96dfd3e5c4e9';
update public.recipes set title_en = 'Watermelon with Beyaz Peynir', instructions_en = 'INGREDIENTS:
- 200 g watermelon
- 60 g beyaz peynir (Turkish brined white cheese; feta works)
- a few fresh mint leaves

METHOD:
1. Arrange the watermelon cubes on a plate.
2. Set the cubes of beyaz peynir to one side.
3. Garnish with mint and serve.' where id = 'ed4b6558-6d7b-405b-abf1-1349fdffa231';
update public.recipes set title_en = 'Kaşar Pan Toastie', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 40 g kaşar cheese (Turkish semi-hard yellow cheese; mild cheddar or gouda works)
- 5 ml butter
- 1 pinch black pepper

METHOD:
1. Lay the kaşar cheese between the bread slices.
2. Grease one side of the pan with butter.
3. Cook in a covered pan for 3 minutes until both sides are golden.
4. Serve with black pepper.' where id = 'de6538aa-fb92-4512-be44-211a0981fe62';
update public.recipes set title_en = 'Red Lentil Soup with Wholemeal Bread', instructions_en = 'INGREDIENTS:
- 150 g red lentils
- 1 onion
- 1 carrot
- 2 cloves garlic
- 1 l vegetable stock
- 10 ml olive oil
- 2 slices wholemeal bread
- cumin, chilli flakes and salt

METHOD:
1. Fry the onion and garlic in the olive oil for 2 minutes.
2. Add the grated carrot and cook for 2 minutes more.
3. Add the lentils and vegetable stock and simmer over low heat for 20 minutes.
4. Blend it smooth and season with cumin and salt.
5. Serve hot with the bread.' where id = '3d353b52-869a-4200-892e-4167675eb37b';
update public.recipes set title_en = 'Beef and Potato Stew', instructions_en = 'INGREDIENTS:
- 100 g ground beef
- 2 potato
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- salt

METHOD:
1. Fry the ground beef in the olive oil for 4 minutes.
2. Add the onion and potato and cook for 4 minutes more.
3. Add the tomato paste and 150 ml of hot water.
4. Cover, cook for 6 minutes, season with salt and serve.' where id = '0bee4c83-4936-41d5-87d1-64e06b681794';
update public.recipes set title_en = 'Simple Pasta with Ground Beef', instructions_en = 'INGREDIENTS:
- 100 g pasta
- 100 g ground beef
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- salt

METHOD:
1. Boil the pasta in salted water and drain it.
2. Fry the onion in the olive oil for 2 minutes.
3. Add the beef and cook for 4 minutes until it changes colour, then add the tomato paste.
4. Toss the pasta through the sauce and serve.' where id = '8b24a4b9-583b-45d8-bb5f-7408699cf0e8';
update public.recipes set title_en = 'High-Protein Beef Pasta', instructions_en = 'INGREDIENTS:
- 120 g wholemeal pasta
- 150 g lean ground beef
- 200 g unsweetened passata
- 1/2 onion
- 2 cloves garlic
- 30 g parmesan cheese
- 10 ml olive oil
- basil, salt and black pepper

METHOD:
1. Boil the pasta according to the packet.
2. Fry the onion and garlic in the olive oil.
3. Add the beef and cook until it changes colour.
4. Add the tomato sauce and simmer over low heat for 10 minutes.
5. Toss the pasta through the sauce, scatter parmesan and basil over and serve.' where id = '63179697-fa64-4600-b710-a95cd3fb1468';
update public.recipes set title_en = 'Pan Eggs with Ground Beef', instructions_en = 'INGREDIENTS:
- 100 g ground beef
- 2 eggs
- 1 small onion
- 5 ml olive oil
- 1 tbsp tomato paste
- salt

METHOD:
1. Fry the onion in the olive oil for 2 minutes.
2. Add the beef and cook for 4 minutes until it changes colour, then add the tomato paste.
3. Crack the eggs over the top and season with salt.
4. Cook for 4 minutes more until the eggs set.' where id = '019ff752-06ec-4385-ace0-26045a84c75c';
update public.recipes set title_en = 'Classic Lentil Soup', instructions_en = 'INGREDIENTS:
- 100 g cooked red lentils
- 1 small onion
- 1 carrot
- 1 tbsp butter
- 1 tsp chilli flakes
- salt

METHOD:
1. Sauté the onion and carrot in the butter for 3 minutes.
2. Add the lentils and 500 ml of water and bring to the boil.
3. Blend it smooth and add the salt.
4. Finish with chilli flakes and serve.' where id = 'f14a3060-241b-42a5-a2e0-a64afa7f309c';
update public.recipes set title_en = 'Oats with Milk and Dried Apricots', instructions_en = 'INGREDIENTS:
- 50 g rolled oats
- 250 ml milk
- 4 dried apricots
- 1 dessertspoon honey
- 1 pinch cinnamon

METHOD:
1. Bring the oats and milk to the boil in a pan over medium heat.
2. Add the apricots and cook for 4 minutes more.
3. Transfer to a bowl and drizzle the honey over.
4. Finish with cinnamon and serve hot.' where id = 'dc5bb5aa-6a6f-4d26-bd43-17f9d831d719';
update public.recipes set title_en = 'Pan-Fried Sea Bass', instructions_en = 'INGREDIENTS:
- 200 g sea bass fillet
- 30 g flour
- 10 ml olive oil
- 1/2 lemon
- a few sprigs of fresh parsley
- salt

METHOD:
1. Season the sea bass with salt and dust it in flour.
2. Warm the olive oil in a pan.
3. Fry the sea bass for 4 minutes until both sides are golden.
4. Serve with lemon and parsley.' where id = '11153e88-9a29-4068-9be1-ea6928bfac9e';
update public.recipes set title_en = 'Rocket Salad with Lemon Dressing', instructions_en = 'INGREDIENTS:
- 2 handfuls rocket (arugula)
- 1/2 lemon
- 10 ml olive oil
- 30 g walnuts
- a few fresh mint leaves
- salt

METHOD:
1. Put the rocket in a bowl.
2. Whisk the lemon, olive oil and salt together.
3. Drizzle the dressing over the rocket.
4. Finish with walnuts and mint and serve.' where id = '51f034fb-777b-49c2-a1a2-2d6628d34216';
update public.recipes set title_en = 'Lemon Honey Yogurt', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1/2 lemon
- 1 tbsp honey
- 1 pinch grated lemon zest

METHOD:
1. Add the lemon juice to the yogurt and whisk.
2. Stir the honey through.
3. Finish with grated lemon zest and serve.' where id = '1cc4c132-5bdb-47a1-9084-b0f8e97ccdf6';
update public.recipes set title_en = 'Hot Milk with Honey and Lemon', instructions_en = 'INGREDIENTS:
- 250 ml milk
- 1 tbsp honey
- 1/2 lemon
- 1 pinch cinnamon

METHOD:
1. Warm the milk over medium heat without letting it boil.
2. Add the honey and lemon juice.
3. Stir and pour into a glass.
4. Finish with cinnamon and serve hot.' where id = '30e44822-f5c7-4293-9f96-04264e96bdbf';
update public.recipes set title_en = 'Frozen Lemon Yogurt Bars', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1/2 lemon
- 1 tbsp honey
- 15 g granola

METHOD:
1. Stir the lemon zest, juice and honey through the yogurt.
2. Spread it into a flat dish.
3. Scatter the granola over the top.
4. Freeze for 5 minutes and serve as bars.' where id = 'fb46a080-c87b-4321-9f41-fb0bd6ac52ac';
update public.recipes set title_en = 'Lor Cheese and Honey on Bread', instructions_en = 'INGREDIENTS:
- 80 g lor cheese (fresh Turkish whey cheese; ricotta is the closest substitute)
- 1 tbsp honey
- 2 slices wholemeal bread
- 1 pinch cinnamon

METHOD:
1. Mash the lor cheese in a bowl with a fork.
2. Add the honey and cinnamon and mix.
3. Spread the mixture over the bread slices.
4. Serve immediately.' where id = 'e50f4425-cdd0-4080-9340-b1768caa560b';
update public.recipes set title_en = 'Tomato and Lor Cheese Plate', instructions_en = 'INGREDIENTS:
- 100 g lor cheese (fresh Turkish whey cheese; ricotta is the closest substitute)
- 2 ripe tomato
- 5 olives
- 5 ml olive oil
- 1 tsp dried oregano
- salt

METHOD:
1. Arrange the tomato slices on a plate.
2. Set the lor cheese in the middle.
3. Add the olives and drizzle olive oil over.
4. Serve with oregano and salt.' where id = 'd36fcc2b-35ec-476d-89ab-3bdf2d4c4041';
update public.recipes set title_en = 'Simple Mushroom Omelette', instructions_en = 'INGREDIENTS:
- 3 eggs
- 80 g mushrooms
- 5 ml butter
- 1 tbsp milk
- salt and black pepper

METHOD:
1. Sauté the mushrooms in the butter for 3 minutes.
2. Beat the eggs with the milk and add the seasoning.
3. Pour the mixture over the mushrooms.
4. Cook for 3 minutes until the eggs set.' where id = '49dd6e39-2146-4ae4-82c8-9ed52c3ad072';
update public.recipes set title_en = 'Chicken and Mushroom Sauté', instructions_en = 'INGREDIENTS:
- 150 g chicken breast
- 200 g mushrooms
- 1 small onion
- 10 ml olive oil
- 1 tbsp tomato paste
- salt

METHOD:
1. Fry the chicken in the olive oil for 4 minutes.
2. Add the onion and mushrooms and cook for 4 minutes more.
3. Add the tomato paste and 50 ml of water.
4. Cover, cook for 4 minutes, season with salt and serve.' where id = 'fe75401a-3a4f-45bb-8fdc-6aa763efe90f';
update public.recipes set title_en = 'Simple Parsley Omelette', instructions_en = 'INGREDIENTS:
- 3 eggs
- 1 tbsp milk
- 1 tbsp chopped parsley
- 5 ml olive oil
- salt and black pepper

METHOD:
1. Beat the eggs with the milk and add the seasoning and parsley.
2. Warm the olive oil in a pan.
3. Pour the mixture in, drawing the set edges into the middle as they cook.
4. Fold in half once the eggs have set and serve.' where id = '2eed26c5-0159-4f1d-8843-ed5630524c06';
update public.recipes set title_en = 'Egg Salad with Parsley', instructions_en = 'INGREDIENTS:
- 3 boiled egg
- 100 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 tbsp chopped parsley
- 1 tsp vinegar
- 5 ml olive oil
- salt

METHOD:
1. Put the eggs in a bowl.
2. Add the yogurt, vinegar, olive oil and salt and mix.
3. Fold the parsley through.
4. Serve cold.' where id = '666cc2d1-aae3-4ccf-9261-d667354b3641';
update public.recipes set title_en = 'Classic Menemen', instructions_en = 'INGREDIENTS:
- 3 eggs
- 2 ripe tomato
- 1 long green pepper (Turkish sivri; any mild long pepper works)
- 1 small onion
- 10 ml olive oil
- salt and black pepper

METHOD:
1. Sauté the onion and pepper in the olive oil for 2 minutes.
2. Add the grated tomato and cook for 4 minutes until the liquid reduces.
3. Crack the eggs in without beating them and scatter the seasoning.
4. Serve immediately once the eggs have set.' where id = 'c1d7465b-c283-4721-a5f2-fbf45867b9c2';
update public.recipes set title_en = 'Lentil Köfte Wrap', instructions_en = 'INGREDIENTS:
- 2 wholemeal lavash (thin flatbread; a wholemeal tortilla works)
- 150 g homemade lentil köfte (Turkish lentil-and-bulgur patties)
- 1 handful lettuce leaf
- 1 tomato
- 1/4 red onion
- 1 tbsp hummus
- fresh parsley and lemon juice

METHOD:
1. Warm the lavash lightly in a pan.
2. Spread a layer of hummus over each one.
3. Lay out the lettuce, tomato, onion and lentil köfte.
4. Finish with parsley and lemon juice, roll tightly and serve.' where id = '0aaa8b17-b942-4dcd-a0a2-cb8921c4f275';
update public.recipes set title_en = 'Erişte with Lentils', instructions_en = 'INGREDIENTS:
- 80 g erişte (Turkish egg noodles; tagliatelle works)
- 100 g cooked red lentils
- 1 small onion
- 5 ml olive oil
- 1 tbsp dried mint
- salt

METHOD:
1. Boil the erişte in salted water and drain it.
2. Fry the onion in the olive oil for 2 minutes.
3. Add the lentils and warm for 2 minutes, then fold in the erişte.
4. Season with mint and serve.' where id = 'c6b12acc-1c09-48da-93b7-6e6c1085ff10';
update public.recipes set title_en = 'Strained Yogurt with Fruit', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 100 g fresh blackberries
- 50 g kiwi
- 10 g honey
- 5 g rolled oats

METHOD:
1. Spread the yogurt over the base of a wide bowl.
2. Arrange the fruit over the yogurt.
3. Drizzle the honey in a thin ribbon.
4. Scatter the oats over and serve immediately.' where id = '2b25384d-8565-4e99-a993-246e1c5fef80';
update public.recipes set title_en = 'Vegan Fruit Smoothie Bowl', instructions_en = 'INGREDIENTS:
- 1 frozen banana
- 100 g frozen mixed berries
- 200 ml almond milk
- 15 g plant protein powder
- 10 g chia seeds
- 15 g granola
- 5 g desiccated coconut

METHOD:
1. Blend the banana, blackberries, almond milk and protein powder until smooth.
2. Transfer to a wide bowl.
3. Scatter the chia seeds, granola and coconut over the top.
4. Add more fresh fruit if you like and serve immediately.' where id = 'd5944710-1dcc-4195-adf6-39d05c2bbc91';
update public.recipes set title_en = 'Microwave Chocolate Mug Cake', instructions_en = 'INGREDIENTS:
- 4 tbsp flour
- 2 tbsp cocoa
- 3 tbsp sugar
- 1 eggs
- 60 ml milk
- 15 g butter

METHOD:
1. Mix all the ingredients in a mug.
2. Work it into a smooth batter.
3. Microwave at 800 W for 2 minutes.
4. Rest for 1 minute and serve.' where id = '41b4d8b4-ff73-4ec9-9a52-0535f47af768';
update public.recipes set title_en = 'Microwave Cinnamon Apple', instructions_en = 'INGREDIENTS:
- 2 apple
- 1 tbsp honey
- 1 tsp cinnamon
- 5 g butter

METHOD:
1. Put the apple cubes in a microwave-safe bowl.
2. Add the honey, cinnamon and butter.
3. Cook at 800 W for 4 minutes.
4. Stir and serve.' where id = 'ba6e9ad9-0f95-40e9-9571-34472de90557';
update public.recipes set title_en = 'Corn Flakes with Milk', instructions_en = 'INGREDIENTS:
- 50 g corn flakes
- 250 ml milk
- 1 banana

METHOD:
1. Put the corn flakes in a bowl.
2. Pour the cold milk over.
3. Add the banana slices and serve immediately.' where id = '8a2e1bdd-b0bf-4bbd-bf10-c7666a18bd15';
update public.recipes set title_en = 'Courgette Fritters', instructions_en = 'INGREDIENTS:
- 1 large courgette (zucchini)
- 50 g flour
- 2 eggs
- 30 g beyaz peynir (Turkish brined white cheese; feta works)
- 5 ml olive oil
- a few sprigs of fresh dill

METHOD:
1. Squeeze the liquid out of the grated courgette.
2. Knead it with the flour, egg, cheese and dill.
3. Spoon the batter into an oiled pan and shape the fritters.
4. Cook each side for 3 minutes and serve.' where id = '4d72f57f-5936-49af-9e56-a9a080923c75';
update public.recipes set title_en = 'Banana Tahini Sandwich', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 1 banana
- 2 tbsp tahini
- 1 tbsp grape molasses (Turkish pekmez; date or pomegranate molasses substitute)

METHOD:
1. Spread the tahini over the bread slices.
2. Lay the banana slices on.
3. Drizzle the grape molasses over.
4. Close, cut in half and serve.' where id = '6a3677c0-2b6b-4526-ada5-24bb323f39de';
update public.recipes set title_en = 'Hot Banana Porridge', instructions_en = 'INGREDIENTS:
- 50 g rolled oats
- 250 ml milk
- 1 ripe banana
- 1 dessertspoon honey
- 1 pinch cinnamon

METHOD:
1. Bring the oats and milk to the boil in a pan over medium heat.
2. Stir for 3 minutes until it thickens.
3. Transfer to a bowl and lay the banana on top.
4. Finish with honey and cinnamon and serve hot.' where id = '570d0e8a-a4a5-4bdd-8c1f-23c6428d21eb';
update public.recipes set title_en = 'Vegan Banana Ice Cream', instructions_en = 'INGREDIENTS:
- 2 frozen banana
- 5 g unsweetened cocoa powder
- 5 g desiccated coconut
- 1 dessertspoon vanilla extract

METHOD:
1. Blend the frozen banana slices until creamy.
2. Add the cocoa powder and vanilla and blend for 15 seconds more.
3. Transfer to a serving bowl.
4. Scatter the desiccated coconut over and serve immediately.' where id = '170064fe-1eea-4b22-a968-18fecb4f161d';
update public.recipes set title_en = 'Banana Yogurt Dessert', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 ripe banana
- 1 tbsp honey
- 15 g walnuts
- 1 pinch cinnamon

METHOD:
1. Spoon the yogurt into a bowl.
2. Lay the banana slices on top.
3. Add the honey and walnuts.
4. Finish with cinnamon and serve cold.' where id = 'd6c4a12c-5c3a-4e12-806d-fbc8077b2a07';
update public.recipes set title_en = 'Chickpea Quinoa Buddha Bowl', instructions_en = 'INGREDIENTS:
- 80 g quinoa
- 150 g cooked chickpeas
- 1 carrot
- 50 g red cabbage
- 1/2 avocado
- 15 ml tahini
- 1 juice of one lemon
- salt and black pepper

METHOD:
1. Boil the quinoa and cool it.
2. Make a dressing with the tahini, lemon juice and 2 tbsp of water.
3. Layer the quinoa, chickpeas, carrot, cabbage and avocado in a bowl.
4. Drizzle the tahini dressing over and serve.' where id = '6205195a-8a45-4333-b7f0-9d9ff2a4d683';
update public.recipes set title_en = 'Potato Soup', instructions_en = 'INGREDIENTS:
- 2 potato
- 1 small onion
- 1 carrot
- 1 tbsp butter
- 500 ml water
- salt

METHOD:
1. Fry the onion and carrot in the butter for 2 minutes.
2. Add the potato and water and simmer for 10 minutes.
3. Blend it smooth.
4. Season with salt and serve.' where id = '8072e753-085e-4b97-8ffb-8b869b85eb7e';
update public.recipes set title_en = 'Fluffy Potato Cakes', instructions_en = 'INGREDIENTS:
- 2 boiled potato
- 40 g flour
- 1 eggs
- 1 small onion
- 5 ml olive oil
- salt

METHOD:
1. Knead the potato, flour, egg, onion and salt together.
2. Shape the mixture into small rounds.
3. Cook each side for 4 minutes in a non-stick pan.
4. Serve hot.' where id = 'e9a91b4f-0c2f-4522-b765-1446d58ec699';
update public.recipes set title_en = 'Date Pudding with Grape Molasses', instructions_en = 'INGREDIENTS:
- 250 ml milk
- 25 g rice flour
- 4 dates
- 2 tbsp grape molasses (Turkish pekmez; date or pomegranate molasses substitute)
- 15 g walnuts

METHOD:
1. Slake the rice flour with 50 ml of cold milk.
2. Bring the remaining milk to the boil and add the dates.
3. Add the rice flour mixture and stir for 6 minutes until it thickens.
4. Divide between bowls and finish with grape molasses and walnuts.' where id = '047a97f5-9e60-4d78-995e-5d2dab1d247d';
update public.recipes set title_en = 'Milk Pudding with Grape Molasses', instructions_en = 'INGREDIENTS:
- 250 ml milk
- 1 tbsp cornstarch
- 2 tbsp grape molasses (Turkish pekmez; date or pomegranate molasses substitute)
- 15 g walnuts
- 1 pinch cinnamon

METHOD:
1. Slake the cornstarch with 50 ml of cold milk.
2. Bring the remaining milk to the boil in a pan, add the starch mixture and cook for 4 minutes until it thickens.
3. Divide between bowls and drizzle the grape molasses over.
4. Finish with walnuts and cinnamon.' where id = 'b1a414f1-2bc0-41b3-ae76-7a0f34df69b2';
update public.recipes set title_en = 'Yogurt Mousse with Grape Molasses', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 2 tbsp grape molasses (Turkish pekmez; date or pomegranate molasses substitute)
- 10 g sugar
- 15 g walnuts

METHOD:
1. Add the sugar to the yogurt and whisk.
2. Fold the grape molasses through.
3. Marble it in the bowl.
4. Finish with walnuts and serve cold.' where id = 'f28008e3-1b55-415f-9e14-50c6c245c0c8';
update public.recipes set title_en = 'Leek Fritters', instructions_en = 'INGREDIENTS:
- 1 large leek
- 50 g flour
- 1 eggs
- 30 g beyaz peynir (Turkish brined white cheese; feta works)
- 5 ml olive oil
- salt

METHOD:
1. Squeeze the liquid out of the leek.
2. Knead it with the flour, egg, cheese and salt.
3. Spoon the batter into an oiled pan and shape the fritters.
4. Cook each side for 3 minutes and serve.' where id = 'ebc24738-362c-4edb-ba84-248fc0151bfa';
update public.recipes set title_en = 'Leek Pilaf', instructions_en = 'INGREDIENTS:
- 80 g rice
- 1 large leek
- 1 tbsp butter
- 5 ml olive oil
- salt
- black pepper

METHOD:
1. Sauté the leek in the butter for 4 minutes.
2. Add the rice with the olive oil and fry for 1 minute.
3. Add 200 ml of hot water and the salt and cover.
4. Cook over low heat for 12 minutes and serve with black pepper.' where id = 'f938dcf2-420a-4813-9f58-c1fc542dfd23';
update public.recipes set title_en = 'Quick Aşure', instructions_en = 'INGREDIENTS:
- 60 g cooked wheat berries
- 30 g cooked chickpeas
- 30 g cooked white beans
- 30 g raisins
- 30 g sugar
- 1 pinch cinnamon

METHOD:
1. Put all the ingredients in a pan with 200 ml of water.
2. Add the sugar and simmer over medium heat for 8 minutes.
3. Divide between bowls.
4. Finish with cinnamon and serve once cooled.' where id = '167e3115-61d0-4ac9-a45c-02399a82a35d';
update public.recipes set title_en = 'Quick İmam Bayıldı', instructions_en = 'INGREDIENTS:
- 2 aubergine (eggplant)
- 1 large onion
- 2 ripe tomato
- 10 ml olive oil
- 2 cloves garlic
- a few sprigs of fresh parsley

METHOD:
1. Fry the aubergines in the olive oil for 4 minutes and lift them out.
2. Sauté the onion and garlic in the same pan for 3 minutes and add the tomato.
3. Return the aubergines and cook for 4 minutes more.
4. Garnish with parsley and serve.' where id = '90586a1b-2cb2-4eef-9297-9f4245d244fe';
update public.recipes set title_en = 'Quick Karnıyarık', instructions_en = 'INGREDIENTS:
- 2 aubergine (eggplant)
- 100 g ground beef
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- a few sprigs of fresh parsley

METHOD:
1. Fry the ground beef in the olive oil for 4 minutes.
2. Add the onion and tomato paste and cook for 3 minutes more.
3. Split the aubergines open and fill them with the mixture.
4. Cook covered in 200 ml of hot water for 5 minutes and serve with parsley.' where id = 'd9a488c2-d283-458e-be43-4e94a25ad418';
update public.recipes set title_en = 'Quick Muhallebi', instructions_en = 'INGREDIENTS:
- 400 ml milk
- 40 g sugar
- 20 g rice flour
- 1 packet vanilla
- 1 pinch cinnamon

METHOD:
1. Slake the rice flour with 50 ml of cold milk.
2. Warm the remaining milk in a pan and add the sugar.
3. Add the rice flour mixture and stir for 6 minutes until it thickens.
4. Add the vanilla, divide between bowls and finish with cinnamon.' where id = 'cc950f3e-9659-4aa7-8f16-536b881a9d99';
update public.recipes set title_en = 'Quick Chickpea Stew', instructions_en = 'INGREDIENTS:
- 200 g cooked chickpeas
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- 1 tsp cumin
- salt

METHOD:
1. Fry the onion in the olive oil for 2 minutes.
2. Add the tomato paste and fry for 1 minute.
3. Add the chickpeas and 200 ml of hot water and simmer for 8 minutes.
4. Season with cumin and salt and serve.' where id = '673bfa52-fad0-487f-8b23-d17b6b34368f';
update public.recipes set title_en = 'Quick Potato Patties', instructions_en = 'INGREDIENTS:
- 2 boiled potato
- 50 g flour
- 1 eggs
- 1 small onion
- 5 ml olive oil
- salt

METHOD:
1. Knead the potato, flour, egg and onion together.
2. Shape the mixture into walnut-sized patties.
3. Cook in an oiled pan for 5 minutes until golden all over.
4. Serve hot.' where id = 'fb4f87fa-0565-452b-83e6-18013510e676';
update public.recipes set title_en = 'Quick Sütlaç', instructions_en = 'INGREDIENTS:
- 100 g cooked rice
- 300 ml milk
- 40 g sugar
- 1 tbsp rice flour
- 1 pinch cinnamon

METHOD:
1. Bring the rice and milk to the boil in a pan over medium heat.
2. Slake the rice flour with a little water and add it.
3. Add the sugar and stir for 6 minutes until it thickens.
4. Divide between bowls and finish with cinnamon.' where id = '3da89c1b-90cf-4d87-8074-a39cb7780f75';
update public.recipes set title_en = 'Quick Mantı with Yogurt', instructions_en = 'INGREDIENTS:
- 150 g cooked mantı (small Turkish meat dumplings; any small filled pasta works)
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 clove garlic
- 15 g butter
- 1 tsp chilli flakes
- salt

METHOD:
1. Boil the mantı in salted water according to the packet.
2. Stir the garlic and salt through the yogurt.
3. Melt the butter and bloom the chilli flakes in it.
4. Plate the mantı and pour the yogurt and butter sauce over.' where id = '6cc81770-d660-4bc3-9282-c49dc977a568';
update public.recipes set title_en = 'Quick Pişi with Egg', instructions_en = 'INGREDIENTS:
- 100 g pişi dough (Turkish fried-bread dough; any enriched bread dough works)
- 2 eggs
- 5 ml olive oil
- 40 g beyaz peynir (Turkish brined white cheese; feta works)
- salt

METHOD:
1. Cook the pişi dough in an oiled pan for 4 minutes until both sides are golden.
2. Crack the eggs into the same pan and season with salt.
3. Split the pişi open and fill it with the cheese and egg.
4. Serve hot.' where id = '7678dd73-fb90-4d37-9c04-4456e562b770';
update public.recipes set title_en = 'Quick Egg Salad', instructions_en = 'INGREDIENTS:
- 2 boiled egg
- 2 handfuls lettuce
- 1 tomato
- 5 ml olive oil
- 1/2 lemon
- salt

METHOD:
1. Put the lettuce and tomato in a bowl.
2. Lay the egg slices over the top.
3. Add the olive oil, lemon and salt.
4. Toss lightly and serve.' where id = '67a05c1f-cd97-461a-bb15-92fdf4a9a9a2';
update public.recipes set title_en = 'Protein Omelette with Avocado', instructions_en = 'INGREDIENTS:
- 3 eggs
- 50 g lor cheese (fresh Turkish whey cheese; ricotta is the closest substitute)
- spinach
- 1/2 avocado

METHOD:
1. Beat the eggs.
2. Add the spinach and cheese and make an omelette.
3. Serve with sliced avocado alongside.' where id = 'c7c38e2a-3888-445f-b81b-761e5bf9160b';
update public.recipes set title_en = 'Protein Pancake Stack', instructions_en = 'INGREDIENTS:
- 60 g oat flour
- 30 g vanilla whey protein powder
- 1 whole egg
- 2 egg whites
- 1 banana
- 200 ml skimmed milk
- 1 dessertspoon baking powder
- 20 g honey
- 80 g blueberries

METHOD:
1. Blend all the ingredients until smooth.
2. Cook each pancake in a non-stick pan over medium heat for 2 minutes a side.
3. Stack the pancakes.
4. Top with blueberries and honey and serve.' where id = '2b644680-9aab-4ef8-924a-f98de8e20bfd';
update public.recipes set title_en = 'Wholemeal Toast with Jam', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 2 tbsp fruit jam
- 5 ml butter

METHOD:
1. Toast the bread slices.
2. Spread the butter on while they are hot.
3. Spread the jam over and serve immediately.' where id = '12475f6e-8a3c-4aa7-98ec-daf0112e252b';
update public.recipes set title_en = 'Yogurt Bowl with Jam', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 2 tbsp fruit jam
- 15 g granola

METHOD:
1. Spoon the yogurt into a bowl.
2. Set the jam on top.
3. Scatter the granola over and serve immediately.' where id = 'a173b39d-c647-4090-9f47-154befd714f7';
update public.recipes set title_en = 'Rocket Salad with Grilled Chicken', instructions_en = 'INGREDIENTS:
- 150 g chicken breast
- 2 handfuls rocket (arugula)
- 1 tomato
- 10 ml olive oil
- 1/2 lemon
- salt

METHOD:
1. Season the chicken with salt and black pepper.
2. Cook each side for 4 minutes in a hot griddle pan.
3. Arrange the rocket and tomato on a plate.
4. Slice the chicken over the top and serve with olive oil and lemon.' where id = '0bc20be4-ddbf-4dd4-a827-594bf0f85e18';
update public.recipes set title_en = 'Rocket and Walnut Salad', instructions_en = 'INGREDIENTS:
- 2 handfuls rocket (arugula)
- 30 g walnuts
- 5 ml olive oil
- 1/2 lemon
- 30 g beyaz peynir (Turkish brined white cheese; feta works)
- salt

METHOD:
1. Put the rocket in a bowl.
2. Add the walnuts and cheese on top.
3. Drizzle the olive oil and lemon over.
4. Season with salt and serve.' where id = '30485245-515d-4877-808d-0c0ff94d400a';
update public.recipes set title_en = 'Simple Beef Fillet Sauté', instructions_en = 'INGREDIENTS:
- 150 g beef fillet
- 1 small onion
- 5 ml olive oil
- 1 tbsp tomato paste
- salt
- black pepper

METHOD:
1. Fry the beef fillet in the olive oil for 4 minutes.
2. Add the onion and cook for 2 minutes more.
3. Add the tomato paste and fry for 1 minute.
4. Season with salt and black pepper and serve.' where id = 'a3562212-d561-4919-8694-b802b9ff34d7';
update public.recipes set title_en = 'Simple Bulgur Salad', instructions_en = 'INGREDIENTS:
- 80 g fine bulgur
- 1 tomato
- 1 cucumber
- 1 small onion
- 5 ml olive oil
- 1 tbsp chopped parsley

METHOD:
1. Soak the bulgur in hot water for 10 minutes and drain it.
2. Combine the vegetables and parsley in a bowl.
3. Add the bulgur and toss with the olive oil.
4. Season with salt and serve.' where id = '504aa4fd-edd4-4505-ba63-8d6450e4ad0c';
update public.recipes set title_en = 'Simple Tomato Salad', instructions_en = 'INGREDIENTS:
- 2 ripe tomato
- 1 small onion
- 5 ml olive oil
- 1 tsp dried oregano
- salt

METHOD:
1. Combine the tomato and onion in a bowl.
2. Add the olive oil and the seasoning.
3. Toss lightly and serve.' where id = 'b32ec536-6f40-4362-b938-1b15dfeb29ba';
update public.recipes set title_en = 'Simple Turkey Pilaf', instructions_en = 'INGREDIENTS:
- 80 g rice
- 100 g turkey breast
- 1 small onion
- 1 tbsp butter
- 5 ml olive oil
- salt

METHOD:
1. Fry the turkey in the olive oil for 4 minutes, add the onion and cook for 2 minutes more.
2. Fry the rice in the butter for 1 minute.
3. Add 200 ml of hot water and the salt and cover.
4. Cook over low heat for 12 minutes and let it rest.' where id = 'eaf3c4d2-bb51-427a-a4e8-6e45fe94c6f5';
update public.recipes set title_en = 'Simple Fig Dessert', instructions_en = 'INGREDIENTS:
- 4 dried figs
- 250 ml milk
- 15 g walnuts
- 1 tbsp honey
- 1 pinch cinnamon

METHOD:
1. Simmer the figs in the milk for 6 minutes.
2. Lift the figs onto a plate.
3. Reduce the milk for 2 minutes more and pour it over the figs.
4. Finish with walnuts, honey and cinnamon and serve.' where id = 'db4e3f10-a57f-42b4-adc6-5c8c277ce2e1';
update public.recipes set title_en = 'Simple Grilled Köfte', instructions_en = 'INGREDIENTS:
- 200 g ground beef
- 1 small onion
- 1 tsp cumin
- 5 ml olive oil
- salt
- black pepper

METHOD:
1. Knead the ground beef, onion and spices together.
2. Shape the köfte.
3. Grease a hot griddle pan with the olive oil.
4. Cook each side for 4 minutes and serve.' where id = '6e0e1c2d-d21a-4928-9eff-67b247fe737c';
update public.recipes set title_en = 'Simple Pan Köfte', instructions_en = 'INGREDIENTS:
- 200 g köfte mix (packet seasoning mix for Turkish meatballs)
- 5 ml olive oil
- 1 tsp cumin
- salt and black pepper

METHOD:
1. Roll the köfte and toss them in the spices.
2. Cook each side for 4 minutes in an oiled pan.
3. Cover and rest for 2 minutes.
4. Serve hot.' where id = 'ad0a4256-ff49-425e-bbb4-60989c287b41';
update public.recipes set title_en = 'Village Bread with Butter', instructions_en = 'INGREDIENTS:
- 2 slices village bread (rustic sourdough-style loaf)
- 15 g butter
- salt

METHOD:
1. Warm the bread slices lightly.
2. Spread the butter on while they are hot.
3. Scatter a pinch of salt over and serve.' where id = '2322103e-196c-4b5b-b713-788fc5417120';
update public.recipes set title_en = 'Simple Lentil Stew', instructions_en = 'INGREDIENTS:
- 200 g cooked red lentils
- 1 small onion
- 1 tbsp olive oil
- 1 tbsp tomato paste
- 1 tsp cumin
- salt

METHOD:
1. Fry the onion in the olive oil for 2 minutes.
2. Add the tomato paste and fry for 1 minute more.
3. Add the lentils and 200 ml of water and simmer for 8 minutes.
4. Season with cumin and salt.' where id = '9510f877-2385-4eb1-b0a7-3aae49777dd3';
update public.recipes set title_en = 'Simple Mıhlama', instructions_en = 'INGREDIENTS:
- 100 g kaşar cheese (Turkish semi-hard yellow cheese; mild cheddar or gouda works)
- 30 g cornflour (cornstarch)
- 30 g butter
- 200 ml water
- salt

METHOD:
1. Melt the butter in a pan, add the cornflour and toast for 2 minutes.
2. Add the water slowly, stirring constantly.
3. Add the cheese and cook for 3 minutes more until it melts.
4. Serve hot.' where id = 'be77297d-c9e8-4a4b-a7ba-89e3b24a5e6d';
update public.recipes set title_en = 'Simple Sweetcorn Salad', instructions_en = 'INGREDIENTS:
- 1 can sweetcorn
- 1 green pepper
- 1 small onion
- 5 ml olive oil
- 1/2 lemon
- salt

METHOD:
1. Combine the sweetcorn, pepper and onion in a bowl.
2. Add the olive oil and lemon juice.
3. Toss with salt.
4. Serve cold.' where id = '69d1e08a-49c2-4cec-babe-aa78e92315a8';
update public.recipes set title_en = 'Simple Beetroot Salad', instructions_en = 'INGREDIENTS:
- 1 cooked beetroot
- 5 ml olive oil
- 1/2 lemon
- 1 small onion
- a few sprigs of fresh parsley
- salt

METHOD:
1. Arrange the beetroot slices on a plate.
2. Lay the onions over them.
3. Drizzle the olive oil and lemon over.
4. Serve with parsley and salt.' where id = 'f614709f-b5d4-4a60-80c3-bb4d36712e8f';
update public.recipes set title_en = 'Simple Mashed Potato', instructions_en = 'INGREDIENTS:
- 3 potato
- 60 ml milk
- 10 g butter
- salt and black pepper

METHOD:
1. Boil the potatoes and drain them.
2. Add the butter and milk.
3. Mash until smooth.
4. Serve with salt and black pepper.' where id = '6287826c-89c5-451a-aff9-6117db1c50d5';
update public.recipes set title_en = 'Simple Pan-Fried Potatoes', instructions_en = 'INGREDIENTS:
- 3 potato
- 10 ml olive oil
- 1 tsp chilli flakes
- 1 tsp dried oregano
- salt

METHOD:
1. Fry the potatoes in an oiled pan for 8 minutes.
2. Turn them and cook for 4 minutes more.
3. Scatter salt, chilli flakes and oregano over.
4. Serve hot.' where id = 'f882f389-4fa3-4986-a43b-0f55241bd3e9';
update public.recipes set title_en = 'Simple Rice Milk Pudding', instructions_en = 'INGREDIENTS:
- 50 g cooked rice
- 400 ml milk
- 30 g sugar
- 1 packet vanilla
- 1 pinch cinnamon

METHOD:
1. Bring the rice and milk to the boil in a pan over medium heat.
2. Add the sugar and vanilla.
3. Stir for 8 minutes until it thickens.
4. Divide between bowls and finish with cinnamon.' where id = '0dcf4be2-3221-4dd3-9d5c-dcc601e0f676';
update public.recipes set title_en = 'Simple Sucuk Crêpes', instructions_en = 'INGREDIENTS:
- 1 eggs
- 60 g flour
- 150 ml milk
- 50 g sucuk (Turkish beef sausage; chorizo or any cured spiced sausage works)
- 5 g butter
- salt

METHOD:
1. Whisk the eggs, flour, milk and salt together.
2. Fry the sucuk slices in a pan for 1 minute and lift them out.
3. Cook the crêpes in an oiled pan and lay the sucuk on top.
4. Roll the crêpe up and serve.' where id = '4938d6d8-6911-4375-b4e2-433995df3bab';
update public.recipes set title_en = 'Simple Milk Halva', instructions_en = 'INGREDIENTS:
- 80 g flour
- 30 g butter
- 40 g sugar
- 200 ml milk
- 15 g walnuts

METHOD:
1. Toast the flour in the butter for 5 minutes until golden.
2. Warm the milk and sugar in a separate pan and add them to the flour.
3. Stir for 4 minutes until it thickens.
4. Press into a mould, scatter walnuts over and serve.' where id = '6c4f8140-93aa-41fb-9676-6a89efabc646';
update public.recipes set title_en = 'Simple Tahini Mousse', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 2 tbsp tahini
- 1 tbsp grape molasses (Turkish pekmez; date or pomegranate molasses substitute)
- 1 pinch cinnamon
- 15 g walnuts

METHOD:
1. Whisk the tahini into the yogurt.
2. Fold the grape molasses through and marble it.
3. Transfer to a bowl.
4. Finish with walnuts and cinnamon and serve.' where id = '76af5ce8-5026-4df9-a10b-04a55e357480';
update public.recipes set title_en = 'Simple Grain Bars', instructions_en = 'INGREDIENTS:
- 60 g rolled oats
- 1 tbsp honey
- 1 tbsp tahini
- 15 g raisins
- 15 g walnuts

METHOD:
1. Combine all the ingredients in a bowl.
2. Spread the mixture onto a flat dish and press it to 1 cm thick.
3. Rest in the fridge for 5 minutes.
4. Cut into bars and serve.' where id = '218d0c15-521b-4bb3-badd-1bd421e8c789';
update public.recipes set title_en = 'Simple Flour Halva', instructions_en = 'INGREDIENTS:
- 80 g flour
- 40 g butter
- 50 g sugar
- 300 ml water
- 15 g pine nuts

METHOD:
1. Toast the pine nuts in the butter for 1 minute.
2. Add the flour and toast for 5 minutes until golden.
3. Warm the water and sugar in a separate pan and stir them into the halva.
4. Rest once it thickens, press into a mould and serve.' where id = '926b9c28-b1e3-40e8-868d-f8ec344b7f7b';
update public.recipes set title_en = 'Simple Eggs with Bread', instructions_en = 'INGREDIENTS:
- 2 eggs
- 2 slices wholemeal bread
- 5 ml butter
- 1 pinch salt and black pepper

METHOD:
1. Melt the butter in a pan.
2. Crack the eggs in and cook over medium heat for 3 minutes.
3. Scatter the salt and black pepper.
4. Serve with the bread.' where id = '5a6e1cce-1094-4d5d-aebf-6f5e39fa126d';
update public.recipes set title_en = 'Simple Egg Custard', instructions_en = 'INGREDIENTS:
- 250 ml milk
- 1 eggs
- 30 g sugar
- 1 packet vanilla
- 1 pinch cinnamon

METHOD:
1. Whisk the egg with the sugar and vanilla.
2. Warm the milk and add it slowly to the egg mixture.
3. Return it to the pan and stir over medium heat for 6 minutes until it thickens.
4. Divide between bowls and finish with cinnamon.' where id = 'e64c30b0-41f8-472f-b5ee-648a0282fe5f';
update public.recipes set title_en = 'Salami Plate', instructions_en = 'INGREDIENTS:
- 60 g turkey salami
- 40 g kaşar cheese (Turkish semi-hard yellow cheese; mild cheddar or gouda works)
- 1 slice wholemeal bread
- 1 tomato
- 5 olives

METHOD:
1. Arrange the salami and cheese on a plate.
2. Slice the tomato and set it to one side.
3. Add the olives and put the slice of bread in the middle.
4. Serve immediately.' where id = '57515ce3-6a2b-4092-8f1a-aee0f8e2b341';
update public.recipes set title_en = 'Cucumber Sticks with Yogurt Dip', instructions_en = 'INGREDIENTS:
- 1 cucumber
- 150 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 clove garlic
- 1 tsp dried mint
- salt

METHOD:
1. Stir the garlic, mint and salt through the yogurt.
2. Arrange the cucumber sticks on a plate.
3. Put the dip in the middle and serve immediately.' where id = 'e65d90b7-1698-4497-a9a6-d538dcca055b';
update public.recipes set title_en = 'Cucumber and Beyaz Peynir', instructions_en = 'INGREDIENTS:
- 1 cucumber
- 60 g beyaz peynir (Turkish brined white cheese; feta works)
- 5 ml olive oil
- a few fresh mint leaves

METHOD:
1. Arrange the cucumber slices on a plate.
2. Set the beyaz peynir to one side.
3. Drizzle the olive oil over.
4. Garnish with mint and serve.' where id = 'e02a8717-2d77-46a2-8b36-82c6c927a71c';
update public.recipes set title_en = 'Pan Eggs in Tomato Paste Sauce', instructions_en = 'INGREDIENTS:
- 3 eggs
- 2 tbsp tomato paste
- 1 small onion
- 10 ml olive oil
- 1 tsp chilli flakes
- salt

METHOD:
1. Fry the onion in the olive oil for 2 minutes.
2. Add the tomato paste and 50 ml of water and cook for 2 minutes more.
3. Crack the eggs over the top and scatter the seasoning.
4. Cover, cook for 3 minutes and serve.' where id = '57ef1539-982f-4a31-9d45-144cb8843a14';
update public.recipes set title_en = 'Köfte and Eggs in Tomato Sauce', instructions_en = 'INGREDIENTS:
- 150 g köfte mix (packet seasoning mix for Turkish meatballs)
- 2 eggs
- 2 tbsp tomato paste
- 1 small onion
- 5 ml olive oil
- salt

METHOD:
1. Roll the köfte into balls and fry them in a pan for 4 minutes.
2. Add the onion and tomato paste and cook with 100 ml of water.
3. Crack the eggs onto the sauce and season.
4. Cover and cook for 3 minutes until the eggs set.' where id = '2b2d3082-fb93-422a-83fa-6dcc29165aec';
update public.recipes set title_en = 'Garlic Cacık', instructions_en = 'INGREDIENTS:
- 200 g yogurt
- 1 cucumber
- 1 clove garlic
- 100 ml cold water
- 1 tsp dried mint
- salt

METHOD:
1. Drain the liquid from the cucumber.
2. Stir the cucumber, garlic, cold water, mint and salt through the yogurt.
3. Rest in the fridge for 5 minutes.
4. Serve cold.' where id = '0f5d46e9-5d99-4110-97ab-021d545b5e15';
update public.recipes set title_en = 'Bulgur Pilaf with Vegetables', instructions_en = 'INGREDIENTS:
- 80 g coarse bulgur
- 1 small onion
- 1 carrot
- 1 green pepper
- 10 ml olive oil
- salt

METHOD:
1. Sauté the vegetables in the olive oil for 3 minutes.
2. Add the bulgur and fry for 1 minute.
3. Add 200 ml of hot water and the salt and cover.
4. Cook over low heat for 12 minutes and let it rest.' where id = '967afee5-a190-4224-895f-d7cd5cc70d56';
update public.recipes set title_en = 'Homestyle Vegetable Soup', instructions_en = 'INGREDIENTS:
- 1 carrot
- 1 courgette (zucchini)
- 100 g celery stick
- 1/2 onion
- 1 clove garlic
- 800 ml vegetable stock
- 10 ml olive oil
- salt, black pepper and oregano

METHOD:
1. Sauté the onion and garlic in the olive oil for 2 minutes until they colour.
2. Add the diced carrot, courgette and celery and fry for 3 minutes more.
3. Add the vegetable stock and cook over low heat for 20 minutes.
4. Add the thyme, salt and black pepper and serve hot.' where id = 'b068825f-c965-4b78-afc4-bf3a231a7ca1';
update public.recipes set title_en = 'Lentil Soup with Vegetables', instructions_en = 'INGREDIENTS:
- 120 g red lentils
- 1 onion
- 1 carrot
- 1 courgette (zucchini)
- 2 cloves garlic
- 1.2 l vegetable stock
- 10 ml olive oil
- cumin, salt and black pepper

METHOD:
1. Fry the onion and garlic in the olive oil for 2 minutes.
2. Add the diced carrot and courgette and cook for 3 minutes.
3. Add the lentils and vegetable stock and simmer over low heat for 25 minutes.
4. Blend it smooth, season with cumin and salt and serve hot.' where id = '23fbcfae-5a2b-45f8-9496-6f6ad78a7f29';
update public.recipes set title_en = 'Quick Vegetable Köfte', instructions_en = 'INGREDIENTS:
- 200 g köfte mix (packet seasoning mix for Turkish meatballs)
- 1 small onion
- 1 green pepper
- 1 carrot
- 5 ml olive oil
- salt

METHOD:
1. Knead the köfte mix and the vegetables together.
2. Shape into balls and cook in the olive oil for 6 minutes.
3. Turn them and cook for 4 minutes more.
4. Serve hot.' where id = 'e30b79b4-3f62-40e1-8036-d20c67dd5fe6';
update public.recipes set title_en = 'Orzo Soup with Egg', instructions_en = 'INGREDIENTS:
- 60 g orzo
- 1 eggs
- 1/2 lemon
- 1 tbsp butter
- 1 tsp dried mint
- salt

METHOD:
1. Toast the orzo in the butter for 1 minute.
2. Add 600 ml of water and simmer for 8 minutes.
3. Beat the egg with the lemon juice and add it to the soup in a thin stream, stirring constantly.
4. Season with salt and mint and serve.' where id = '6b43b796-865e-43cf-a678-5c370dc4c570';

commit;

