-- Roadmap Phase 7 · English recipe titles and instructions.
-- Generated by tool/recipe_pipeline/translations/build_recipe_en.py
-- Do not hand-edit; change recipes_en.py and re-run.
--
-- The INGREDIENTS half is generated from recipe_ingredients, so no
-- quantity or unit passes through a translation. Only the METHOD
-- half is authored.

begin;

update public.recipes set title_en = 'Spicy Tomato Soup', instructions_en = 'INGREDIENTS:
- 4 ripe tomato
- 1 small onion
- 10 ml olive oil
- 1 tsp chilli flakes
- 1 tbsp butter
- salt

METHOD:
1. Fry the onion in the olive oil for 2 minutes.
2. Add the tomatoes and simmer for 6 minutes.
3. Add the salt, chilli flakes and 200 ml of water, then cook for 4 minutes more.
4. Stir the butter into the soup and serve.' where id = 'c7530a54-0946-41fe-a283-20d70fc067de';
update public.recipes set title_en = 'Mediterranean Quinoa Salad', instructions_en = 'INGREDIENTS:
- 100 g quinoa
- 100 g cooked chickpeas
- 1/2 cucumber
- 10 cherry tomatoes
- 30 g low-fat beyaz peynir (Turkish brined white cheese; light feta works)
- 10 olives
- 1 handful parsley
- 15 ml olive oil
- 1 juice of one lemon

METHOD:
1. Boil the quinoa in plenty of water for 15 minutes, then leave it to cool.
2. Dice all the vegetables small.
3. Combine the quinoa, chickpeas, vegetables and cheese.
4. Drizzle with olive oil and lemon juice and serve with parsley.' where id = '3971c479-ce32-4b34-9b9c-013dee1df749';
update public.recipes set title_en = 'Avocado Wholemeal Toast', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 1 ripe avocado
- 2 eggs
- 1 tbsp white vinegar
- 1 tsp lemon juice
- 1 dessertspoon extra virgin olive oil
- chilli flakes, salt and black pepper
- 5 g fresh thyme or parsley

METHOD:
1. Toast the bread in a toaster or dry pan until both sides are golden.
2. Halve the avocado and remove the stone; mash the flesh with a fork and mix in the lemon juice, salt and black pepper.
3. Bring water to the boil in a small pan; once it boils, lower the heat and add the vinegar.
4. Crack each egg into a separate bowl; make a gentle whirlpool in the water and slide the egg in slowly.
5. Poach for 2-3 minutes for a runny yolk, lift out with a slotted spoon and drain on kitchen paper.
6. Spread the mashed avocado generously over the toast and set a poached egg on each slice.
7. Scatter chilli flakes, olive oil and the chopped thyme over the top and serve immediately.' where id = 'eac3e53c-155b-413f-baac-a9a3e8d1e079';
update public.recipes set title_en = 'Avocado and Egg Wholemeal Toast', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 1/2 avocado
- 2 boiled egg
- 1/2 juice of one lemon
- chilli flakes, salt and black pepper
- fresh parsley

METHOD:
1. Toast the bread slices for 2 minutes.
2. Mash the avocado with a fork and mix in the lemon juice and salt.
3. Spread the avocado mixture over the bread.
4. Lay the sliced egg on top and serve with chilli flakes and parsley.' where id = '1fd74b61-7b93-47e9-9de3-111d1bffb6d2';
update public.recipes set title_en = 'Almond Milk Pudding', instructions_en = 'INGREDIENTS:
- 250 ml milk
- 25 g rice flour
- 30 g sugar
- 30 g almonds
- 1 packet vanilla

METHOD:
1. Slake the rice flour with 50 ml of cold milk.
2. Bring the remaining milk to the boil and add the sugar.
3. Add the rice flour mixture and stir for 6 minutes until it thickens.
4. Divide between bowls and finish with vanilla and almonds.' where id = 'a4b2407b-b8c5-42c9-897a-9b278cf09a80';
update public.recipes set title_en = 'Gardener''s Salad', instructions_en = 'INGREDIENTS:
- 2 handfuls lettuce
- 1 tomato
- 1 cucumber
- 1 small green pepper
- 1 small carrot
- 10 ml olive oil

METHOD:
1. Combine all the vegetables in a bowl.
2. Add the olive oil.
3. Season with salt and toss lightly.
4. Serve cold.' where id = '8ee45d41-201d-4070-8125-82572e27e368';
update public.recipes set title_en = 'Vanilla Yogurt with Honey', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 packet vanilla
- 1 tbsp honey
- 15 g walnuts
- 1 pinch cinnamon

METHOD:
1. Stir the vanilla through the yogurt.
2. Spoon into a bowl and drizzle the honey over.
3. Scatter the walnuts.
4. Finish with cinnamon and serve.' where id = '802c2e46-5125-42f5-9587-0b0b3c0f2ce6';
update public.recipes set title_en = 'Lor Cheese with Honey and Walnuts', instructions_en = 'INGREDIENTS:
- 100 g lor cheese (fresh Turkish whey cheese; ricotta is the closest substitute)
- 1 tbsp honey
- 15 g walnuts
- 1 pinch cinnamon
- 1 slice wholemeal bread

METHOD:
1. Spoon the lor cheese into a bowl.
2. Add the walnuts on top.
3. Drizzle the honey over.
4. Finish with cinnamon and serve with bread.' where id = '01115b20-4d27-47af-9ab4-7b7bb0896688';
update public.recipes set title_en = 'Strained Yogurt with Honey and Walnuts', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 tbsp honey
- 15 g walnut halves
- 1 pinch cinnamon

METHOD:
1. Spoon the yogurt into a bowl.
2. Add the honey and walnuts on top.
3. Finish with cinnamon and serve.' where id = '199c2d0f-6762-4ab5-a8e9-43bf797836ce';
update public.recipes set title_en = 'Honey Cinnamon French Toast', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 1 eggs
- 60 ml milk
- 15 g butter
- 2 tbsp honey
- 1 tsp cinnamon

METHOD:
1. Whisk the eggs, milk and cinnamon together.
2. Dip the bread slices in the mixture.
3. Fry each side in the butter for 2 minutes.
4. Drizzle the honey over and serve warm.' where id = '954637ff-d82c-4895-b007-f4a07a5be8be';
update public.recipes set title_en = 'Bazlama Pan Toastie', instructions_en = 'INGREDIENTS:
- 1 bazlama (Turkish flatbread; pita or naan works)
- 40 g beyaz peynir (Turkish brined white cheese; feta works)
- 1 tomato
- 5 olives
- a few fresh mint leaves

METHOD:
1. Split the bazlama through the middle and spread the cheese over the cut face.
2. Add the tomato slices and olives.
3. Heat in a covered pan for 3 minutes.
4. Garnish with mint and serve.' where id = 'f6a99c06-ec20-4ded-ad03-c922b5ce6924';
update public.recipes set title_en = 'Beyaz Peynir with Honey', instructions_en = 'INGREDIENTS:
- 100 g beyaz peynir (Turkish brined white cheese; feta works)
- 1 tbsp honey
- 15 g walnuts
- 1 pinch cinnamon
- 1 slice wholemeal bread

METHOD:
1. Put the beyaz peynir in a bowl and crumble it.
2. Stir in the honey and walnuts.
3. Finish with cinnamon.
4. Serve alongside a slice of bread.' where id = 'c9033734-c8da-49e0-9171-46d203b0c410';
update public.recipes set title_en = 'Beyaz Peynir Crêpes', instructions_en = 'INGREDIENTS:
- 1 eggs
- 60 g flour
- 150 ml milk
- 60 g beyaz peynir (Turkish brined white cheese; feta works)
- 5 g butter
- 1 tbsp chopped parsley

METHOD:
1. Whisk the eggs, flour and milk until smooth.
2. Cook thin crêpes in an oiled pan.
3. Spread the cheese and parsley over half of each crêpe.
4. Fold in half, heat for 1 minute more and serve.' where id = 'ead9815b-2916-4f6d-a6a2-ca4da7e063ad';
update public.recipes set title_en = 'Simple Pasta with Beyaz Peynir', instructions_en = 'INGREDIENTS:
- 100 g pasta
- 60 g beyaz peynir (Turkish brined white cheese; feta works)
- 10 ml olive oil
- 1 tbsp dried mint
- salt

METHOD:
1. Boil the pasta in salted water and drain it.
2. Warm the olive oil in the same pan.
3. Return the pasta, add the cheese and toss together.
4. Garnish with mint and serve hot.' where id = '1b35914c-3679-4653-ba66-6712fe4580ec';
update public.recipes set title_en = 'Wholemeal Toastie with Beyaz Peynir', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 60 g beyaz peynir (Turkish brined white cheese; feta works)
- 1 tomato
- 5 olives
- 1 dessertspoon olive oil
- a few fresh mint leaves

METHOD:
1. Brush one side of each bread slice with olive oil.
2. Crumble the cheese and spread it evenly over the inner faces.
3. Toast in a two-sided sandwich press for 3-4 minutes.
4. Serve with tomato slices, olives and mint.' where id = '3a214fcf-8431-446d-a3c7-c79477ed35c1';
update public.recipes set title_en = 'Rice Pilaf with Beef Sauté', instructions_en = 'INGREDIENTS:
- 60 g rice
- 120 g diced beef
- 1 small onion
- 5 ml olive oil
- 1 tbsp tomato paste
- salt

METHOD:
1. Cook the rice in salted water for 12 minutes and drain.
2. Fry the beef in the olive oil for 4 minutes.
3. Add the onion and tomato paste and cook for 6 minutes more with 100 ml of water.
4. Plate the rice and lay the beef over it.' where id = '69fe7821-da0d-4fde-b922-1bff725ba374';
update public.recipes set title_en = 'Rice Pilaf with Yogurt', instructions_en = 'INGREDIENTS:
- 80 g rice
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 tbsp butter
- salt

METHOD:
1. Rinse the rice and soak it in hot water for 10 minutes.
2. Melt the butter in a pan, add the rice and fry for 1 minute.
3. Add 200 ml of hot water and the salt, cover and cook for 12 minutes.
4. Let the pilaf rest and serve with the yogurt.' where id = 'cfbd5f33-c888-41da-bfff-19dac7bb5464';
update public.recipes set title_en = 'Beef and Pea Stew', instructions_en = 'INGREDIENTS:
- 200 g peas
- 100 g diced beef
- 1 carrot
- 1 small onion
- 5 ml olive oil
- salt

METHOD:
1. Fry the beef in the olive oil for 4 minutes.
2. Add the onion and carrot and cook for 3 minutes more.
3. Add the peas and 150 ml of hot water.
4. Cover, cook for 6 minutes, season with salt and serve.' where id = '5e07f2d7-d319-49df-9594-27625e023968';
update public.recipes set title_en = 'Beef Fillet Burrito', instructions_en = 'INGREDIENTS:
- 1 large wholemeal tortilla
- 160 g grilled beef fillet
- 80 g brown rice
- 80 g kidney beans
- 30 g cheddar cheese
- 1/2 avocado
- 2 tbsp salsa

METHOD:
1. Combine the rice and kidney beans in a bowl.
2. Warm the tortilla lightly in a pan.
3. Lay the rice and bean mixture, beef, cheese, avocado and salsa down the middle.
4. Fold the ends in first, then roll it tightly.
5. Fry each side in a hot pan for 1 minute until golden.' where id = '2cdccaa8-2a84-480c-b763-a58f7098a206';
update public.recipes set title_en = 'Date and Walnut Balls', instructions_en = 'INGREDIENTS:
- 8 dates
- 30 g walnuts
- 15 g desiccated coconut
- 1 tbsp unsweetened cocoa

METHOD:
1. Blitz the dates and walnuts in a food processor.
2. Roll the mixture into walnut-sized balls.
3. Coat the balls first in cocoa, then in desiccated coconut.
4. Chill for 5 minutes and serve.' where id = 'bf0de0db-b6d4-4097-a476-5e885f7df580';
update public.recipes set title_en = 'Caramelised Banana with Walnuts', instructions_en = 'INGREDIENTS:
- 2 banana
- 15 g butter
- 1 tbsp honey
- 20 g walnuts
- 1 pinch cinnamon

METHOD:
1. Melt the butter in a pan and fry the banana slices for 2 minutes a side.
2. Drizzle the honey down the side of the pan.
3. Lift the bananas onto a plate.
4. Scatter the walnuts and cinnamon over and serve warm.' where id = 'a0f69eb5-d78f-4343-ac48-2f3887b6cb07';
update public.recipes set title_en = 'Yogurt Dessert with Walnuts', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 20 g walnuts
- 1 tbsp honey
- 1 pinch cinnamon
- 5 g desiccated coconut

METHOD:
1. Spoon the yogurt into a bowl.
2. Add the honey and walnuts on top.
3. Scatter the cinnamon and desiccated coconut.
4. Serve immediately.' where id = '0a5aa59a-d467-4678-a7ec-88e7d2508a8b';
update public.recipes set title_en = 'Vegan Chia Pancakes', instructions_en = 'INGREDIENTS:
- 80 g wholemeal flour
- 15 g chia seeds
- 200 ml almond milk
- 1 dessertspoon baking powder
- 15 g maple syrup
- 1 dessertspoon vanilla extract
- 80 g fresh blackberries

METHOD:
1. Soak the chia seeds in 45 ml of water for 5 minutes until they swell.
2. Whisk the flour, baking powder, milk, maple syrup, vanilla and the chia gel until smooth.
3. Cook each pancake in a non-stick pan over medium heat for 2 minutes.
4. Stack the pancakes, scatter the blackberries over and serve.' where id = '06619310-0964-4c14-b9bd-76e915fc2379';
update public.recipes set title_en = 'Chia Seed Pudding', instructions_en = 'INGREDIENTS:
- 40 g chia seeds
- 300 ml unsweetened almond milk
- 15 g maple syrup
- 1 dessertspoon vanilla extract
- 80 g fresh strawberries
- 20 g almonds

METHOD:
1. Stir the chia seeds, almond milk, maple syrup and vanilla together in a jar.
2. Refrigerate for at least 4 hours, preferably overnight.
3. In the morning, loosen it with a fork and transfer to a bowl.
4. Scatter the strawberries and almonds over and serve.' where id = '609271de-0d7b-4936-a958-c036c17ce1dc';
update public.recipes set title_en = 'Raw Vegetable Breakfast Plate', instructions_en = 'INGREDIENTS:
- 1 cucumber
- 1 tomato
- 5 olives
- 40 g beyaz peynir (Turkish brined white cheese; feta works)
- 5 ml olive oil
- a few fresh mint leaves

METHOD:
1. Arrange the vegetables on a plate.
2. Set the beyaz peynir and olives to one side.
3. Drizzle olive oil over the top.
4. Garnish with mint and serve.' where id = 'f7bdb1c2-8d2c-49df-81ea-ad6cd959b8b4';
update public.recipes set title_en = 'Crudités with Yogurt Dip', instructions_en = 'INGREDIENTS:
- 1 carrot
- 1 cucumber
- 1 green pepper
- 150 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 clove garlic
- 1 tsp dried mint

METHOD:
1. Cut the vegetables into fingers and arrange them on a plate.
2. Stir the garlic and mint through the yogurt.
3. Put the dip on the plate in a small bowl.
4. Serve immediately.' where id = '9ca7c29f-a84c-4eda-857c-0691ae8b3cf8';
update public.recipes set title_en = 'Chocolate Chia Pudding', instructions_en = 'INGREDIENTS:
- 35 g chia seeds
- 250 ml unsweetened almond milk
- 10 g unsweetened cocoa powder
- 15 g maple syrup
- 1 dessertspoon vanilla extract
- 60 g strawberries

METHOD:
1. Whisk the chia seeds, almond milk, cocoa, maple syrup and vanilla together in a jar.
2. Refrigerate for at least 4 hours, preferably overnight.
3. Loosen it with a fork before serving.
4. Set the strawberries on top and serve.' where id = '6080c19f-9ab2-4b03-b7bb-58714d7af12e';
update public.recipes set title_en = 'Chocolate Banana Protein Shake', instructions_en = 'INGREDIENTS:
- 1 banana
- 300 ml semi-skimmed milk
- 30 g chocolate whey protein powder
- 5 g cocoa powder
- 100 g ice

METHOD:
1. Put all the ingredients in a blender.
2. Blend on high for 45 seconds until smooth.
3. Pour into a tall glass.
4. Dust with cocoa powder if you like and drink immediately.' where id = '480dd7a1-fc9b-457f-93d2-2528f0366e9c';
update public.recipes set title_en = 'Chocolate Protein Pudding', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 25 g chocolate whey protein powder
- 5 g unsweetened cocoa powder
- 15 g honey
- 10 g raw almonds

METHOD:
1. Whisk the yogurt, protein powder and cocoa powder until even.
2. Add the honey and stir again.
3. Transfer to a serving bowl and rest in the fridge for 30 minutes.
4. Scatter the roughly chopped almonds over and serve.' where id = '4363943a-3361-421a-8cc3-3307ca0257a2';
update public.recipes set title_en = 'Chocolate Oat Balls', instructions_en = 'INGREDIENTS:
- 80 g rolled oats
- 2 tbsp unsweetened cocoa
- 2 tbsp honey
- 20 g desiccated coconut
- 15 g peanut butter

METHOD:
1. Knead the oats, cocoa, honey and peanut butter together.
2. Roll the mixture into walnut-sized balls.
3. Coat them in desiccated coconut.
4. Chill for 5 minutes and serve.' where id = '03e58bea-2402-4487-9b18-c3684ba0f036';
update public.recipes set title_en = 'Çılbır — Poached Eggs over Garlic Yogurt', instructions_en = 'INGREDIENTS:
- 2 eggs
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 clove garlic
- 15 g butter
- 1 tsp chilli flakes
- salt

METHOD:
1. Stir the crushed garlic and salt through the yogurt and spread it over a plate.
2. Crack the eggs into boiling water, poach for 3 minutes and drain.
3. Set the eggs on the yogurt.
4. Melt the butter and bloom the chilli flakes in it, then pour it over and serve.' where id = '094b6838-66f7-4f54-a67a-6044c70d8407';
update public.recipes set title_en = 'Scrambled Eggs with Pastırma', instructions_en = 'INGREDIENTS:
- 3 eggs
- 30 g pastırma (air-dried spiced beef; bresaola is the closest substitute)
- 5 ml butter
- 1 tbsp milk
- salt and black pepper

METHOD:
1. Fry the pastırma in a pan for 1 minute.
2. Beat the eggs with the milk and add the seasoning.
3. Pour over the pastırma and scramble for 3 minutes.
4. Plate and serve with the butter.' where id = '3de1e0e6-e7be-4c73-9129-c5ca0af644e8';
update public.recipes set title_en = 'Crispy Fried Egg Sandwich', instructions_en = 'INGREDIENTS:
- 2 slices wholemeal bread
- 2 eggs
- 5 ml butter
- 1 leaf lettuce
- 1 slice tomato
- salt

METHOD:
1. Fry the eggs in the butter for 3 minutes.
2. Toast the bread slices lightly.
3. Lay the egg, lettuce and tomato on one slice.
4. Season with salt, close with the other slice and serve.' where id = '579c99c8-5802-4707-98e7-36fe6438d3d3';
update public.recipes set title_en = 'Beef Fillet in Tomato Sauce', instructions_en = 'INGREDIENTS:
- 150 g beef fillet
- 2 ripe tomato
- 1 tbsp tomato paste
- 1 small onion
- 10 ml olive oil
- salt

METHOD:
1. Fry the beef fillet in the olive oil for 4 minutes.
2. Add the onion and cook for 2 minutes more.
3. Add the tomato paste and tomatoes and simmer for 5 minutes.
4. Season with salt and serve.' where id = 'dc428047-7628-4933-820e-5748e0865857';
update public.recipes set title_en = 'Köfte in Tomato Sauce', instructions_en = 'INGREDIENTS:
- 200 g köfte mix (packet seasoning mix for Turkish meatballs)
- 2 ripe tomato
- 1 small onion
- 5 ml olive oil
- salt and black pepper

METHOD:
1. Shape the köfte mix into small balls and cook them in a pan for 5 minutes.
2. Fry the onion in olive oil in a separate pan for 2 minutes.
3. Add the tomatoes and simmer for 5 minutes.
4. Add the köfte to the sauce and cook for 2 minutes more.' where id = 'f1a55d77-c62c-4d80-9de1-1c8b1bb8a627';
update public.recipes set title_en = 'Simple Pasta in Tomato Sauce', instructions_en = 'INGREDIENTS:
- 100 g pasta
- 2 tbsp tomato paste
- 1 small onion
- 5 ml olive oil
- salt and black pepper

METHOD:
1. Boil the pasta in salted water according to the packet.
2. Fry the onion in the olive oil for 2 minutes, add the tomato paste and cook for 1 minute more.
3. Loosen the sauce with 100 ml of hot water.
4. Toss the drained pasta through the sauce, season and serve.' where id = 'cd1b5be6-f027-4811-a26b-e1a1c23bbe61';
update public.recipes set title_en = 'Tomato and Beyaz Peynir Plate', instructions_en = 'INGREDIENTS:
- 2 ripe tomato
- 60 g beyaz peynir (Turkish brined white cheese; feta works)
- 5 olives
- 5 ml olive oil
- a few fresh mint leaves

METHOD:
1. Arrange the tomato slices on a plate.
2. Set the beyaz peynir to one side.
3. Add the olives and mint.
4. Drizzle olive oil over and serve.' where id = 'fe2e091e-d258-4a56-a891-097e722572c4';
update public.recipes set title_en = 'Tomato Rice Pilaf', instructions_en = 'INGREDIENTS:
- 80 g rice
- 1 ripe tomato
- 1 small onion
- 1 tbsp butter
- 1 tbsp tomato paste
- salt

METHOD:
1. Fry the onion in the butter for 2 minutes.
2. Add the tomato paste and tomatoes and cook for 2 minutes more.
3. Add the rice and fry for 1 minute.
4. Add 200 ml of hot water and the salt, cover and cook for 12 minutes.' where id = '09e92bc4-5133-4776-b5cc-46d748b3a8cd';
update public.recipes set title_en = 'Simple Chicken with Tomatoes', instructions_en = 'INGREDIENTS:
- 200 g chicken breast
- 2 ripe tomato
- 1 green pepper
- 5 ml olive oil
- salt and black pepper

METHOD:
1. Fry the chicken in the olive oil for 4 minutes.
2. Add the pepper and sauté for 2 minutes.
3. Add the tomatoes and cook for 5 minutes until they release their juice.
4. Season and serve.' where id = '41b68050-bc5d-41c7-b3f2-0807a1c525ff';
update public.recipes set title_en = 'Fried Eggs with Tomato', instructions_en = 'INGREDIENTS:
- 2 eggs
- 1 large ripe tomato
- 5 ml olive oil
- salt and black pepper

METHOD:
1. Warm the olive oil in a pan.
2. Add the chopped tomato and sauté for 2 minutes.
3. Crack the eggs over the top and scatter the seasoning.
4. Cook for 3 minutes until the whites set and serve hot.' where id = '8e695e52-6f78-4f80-86b1-b436b28523d7';
update public.recipes set title_en = 'Frozen Chocolate Banana Slices', instructions_en = 'INGREDIENTS:
- 2 banana
- 40 g dark chocolate
- 15 g desiccated coconut
- 15 g walnuts

METHOD:
1. Melt the chocolate over a bain-marie.
2. Dip the frozen banana slices in the chocolate.
3. Coat them in desiccated coconut and walnuts.
4. Lay them on baking paper and freeze for 3 minutes more.' where id = 'f85fbb18-3b31-465c-8038-c0ef883487fa';
update public.recipes set title_en = 'Frozen Yogurt Bites', instructions_en = 'INGREDIENTS:
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 100 g fresh strawberries
- 1 tbsp honey
- 1 pinch vanilla

METHOD:
1. Mix the yogurt, strawberries, honey and vanilla together.
2. Drop small balls onto baking paper with an ice-cream scoop.
3. Freeze for 5 minutes.
4. Serve immediately.' where id = 'c6265b3a-94ed-4ff5-9de5-74705d390730';
update public.recipes set title_en = 'Apple Slices with Peanut Butter', instructions_en = 'INGREDIENTS:
- 1 medium apple
- 20 g natural peanut butter
- 1 pinch cinnamon

METHOD:
1. Slice the apple thinly.
2. Warm the peanut butter slightly so it runs.
3. Arrange the apple slices on a plate and drizzle the peanut butter over.
4. Scatter cinnamon over and eat straight away.' where id = 'be63a065-aebc-4f62-90ab-1fe8a19e275f';
update public.recipes set title_en = 'Beef and Courgette Stew', instructions_en = 'INGREDIENTS:
- 2 courgette (zucchini)
- 100 g ground beef
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- a few sprigs of fresh dill

METHOD:
1. Fry the ground beef in the olive oil for 4 minutes.
2. Add the onion and tomato paste and cook for 2 minutes more.
3. Add the courgette and 150 ml of hot water.
4. Cover and cook for 6 minutes, then serve with dill.' where id = '31e02a6c-3dd9-42f6-86f2-0e21b7fd1b9f';
update public.recipes set title_en = 'Beef and White Bean Stew', instructions_en = 'INGREDIENTS:
- 200 g cooked white beans
- 100 g diced beef
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- salt

METHOD:
1. Fry the beef in the olive oil for 4 minutes.
2. Add the onion and tomato paste and cook for 2 minutes more.
3. Add the beans and 200 ml of hot water.
4. Cover and simmer for 8 minutes, season with salt and serve.' where id = 'e2b01ed3-a467-4f2e-bf9d-e01f844ae31c';
update public.recipes set title_en = 'Beef and Chickpea Stew', instructions_en = 'INGREDIENTS:
- 200 g cooked chickpeas
- 100 g diced beef
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- salt

METHOD:
1. Fry the beef in the olive oil for 4 minutes.
2. Add the onion and tomato paste and cook for 2 minutes more.
3. Add the chickpeas and 200 ml of hot water.
4. Cover and simmer for 8 minutes, season with salt and serve.' where id = '92fa47af-0825-4c63-8a35-b30799b3e5b1';
update public.recipes set title_en = 'Beef and Chickpea Pilaf', instructions_en = 'INGREDIENTS:
- 80 g rice
- 100 g cooked chickpeas
- 100 g diced beef
- 1 small onion
- 1 tbsp butter
- salt

METHOD:
1. Fry the beef in the butter for 4 minutes.
2. Add the onion and cook for 2 minutes more.
3. Add the rice and chickpeas and fry for 1 minute.
4. Add 250 ml of hot water and the salt, cover and cook for 12 minutes.' where id = '7efe23df-862c-4986-aa7e-34052ee955bf';
update public.recipes set title_en = 'Beef and Leek Stew', instructions_en = 'INGREDIENTS:
- 1 large leek
- 100 g ground beef
- 1 small onion
- 1 tbsp butter
- 1 tbsp tomato paste
- salt

METHOD:
1. Fry the ground beef in the butter for 4 minutes.
2. Add the onion and tomato paste and cook for 2 minutes more.
3. Add the leek and 150 ml of hot water.
4. Cover and simmer for 8 minutes, season with salt and serve.' where id = '469ee18e-bc66-404f-b3b9-f8b58b10ac6a';
update public.recipes set title_en = 'Beef and Vegetable Soup', instructions_en = 'INGREDIENTS:
- 100 g diced beef
- 1 potato
- 1 carrot
- 1 small onion
- 500 ml beef stock
- salt

METHOD:
1. Put the beef in a pan with the stock and simmer for 8 minutes.
2. Add the onion, carrot and potato and cook for 5 minutes more.
3. Season with salt.
4. Serve.' where id = '5aba127a-cf84-4ddc-91b6-6a3028e46b66';
update public.recipes set title_en = 'Tarhana Soup with Beef', instructions_en = 'INGREDIENTS:
- 30 g tarhana (Turkish fermented soup base of wheat, yoghurt and vegetables; sold dried)
- 100 g ground beef
- 1 tbsp tomato paste
- 1 tbsp butter
- 500 ml water
- salt

METHOD:
1. Fry the ground beef in the butter for 4 minutes and add the tomato paste.
2. Slake the tarhana with 100 ml of cold water, add the remaining 400 ml and bring it to the boil.
3. Add the loosened tarhana to the pan with the beef.
4. Cook for 6 minutes more, season with salt and serve.' where id = '0509dfaa-cf63-40d9-8290-6f091bd28a18';
update public.recipes set title_en = 'Homemade Potato Crisps', instructions_en = 'INGREDIENTS:
- 2 potato
- 5 ml olive oil
- 1 tsp chilli flakes
- salt

METHOD:
1. Toss the potato slices with the olive oil, salt and spices.
2. Cook each side for 5 minutes in a non-stick pan.
3. Turn them now and then until crisp.
4. Serve hot.' where id = '5b77fd24-b9e5-49cf-ad54-2f776e45bec9';
update public.recipes set title_en = 'Homemade Protein Bars', instructions_en = 'INGREDIENTS:
- 50 g rolled oats
- 25 g vanilla whey protein powder
- 20 g natural peanut butter
- 15 g honey
- 10 g dark chocolate chips
- 60 ml milk

METHOD:
1. Combine all the dry ingredients in a bowl.
2. Add the peanut butter, honey and milk and work it into an even dough.
3. Press it into a non-stick tin and scatter the chocolate chips over the top.
4. Rest in the fridge for 1 hour, then cut into 4 bars to store.' where id = 'd46c5a04-cc09-4e56-a006-a75a9e98300a';
update public.recipes set title_en = 'Ezogelin Soup', instructions_en = 'INGREDIENTS:
- 60 g red lentils
- 30 g fine bulgur
- 1 tbsp tomato paste
- 1 small onion
- 1 tbsp butter
- 1 tsp dried mint

METHOD:
1. Fry the onion in the butter for 2 minutes and add the tomato paste.
2. Add the lentils, bulgur and 600 ml of water and bring to the boil.
3. Simmer over low heat for 10 minutes.
4. Season with mint and serve.' where id = 'ad98f215-fac6-4dcc-a7b7-41906f8862f4';
update public.recipes set title_en = 'Baked Salmon with Sweet Potato Mash', instructions_en = 'INGREDIENTS:
- 170 g salmon fillet
- 250 g sweet potato
- 80 g spinach
- 10 ml olive oil
- 1 clove garlic
- fresh dill, salt and black pepper

METHOD:
1. Boil the sweet potatoes in salted water for 12 minutes, drain and mash them.
2. Rub the salmon with dill, garlic and salt and bake at 180 degrees for 14 minutes.
3. Sauté the spinach in the olive oil for 2 minutes.
4. Bring the sweet potato mash, spinach and salmon together on the plate and serve.' where id = '6fe3d2ec-cbae-4325-9af2-36c442ddb89e';
update public.recipes set title_en = 'Baked Cinnamon Apples', instructions_en = 'INGREDIENTS:
- 2 medium apple
- 1 dessertspoon cinnamon
- 10 g honey
- 15 g raw walnuts
- 1 pinch nutmeg

METHOD:
1. Core the apples and cut them into 4 pieces.
2. Lay them on baking paper and drizzle the honey and cinnamon over.
3. Bake at 180 degrees for 15 minutes.
4. Serve hot with the walnut pieces and nutmeg.' where id = '79b6a605-3578-46b8-b3aa-45c9d5224c14';
update public.recipes set title_en = 'Baked Turkey with Brown Rice', instructions_en = 'INGREDIENTS:
- 200 g turkey breast fillet
- 90 g brown rice
- 100 g mushrooms
- 1 clove garlic
- 10 ml olive oil
- oregano, salt and black pepper

METHOD:
1. Cook the rice in plenty of water for 25 minutes.
2. Rub the turkey with thyme, garlic and the spices.
3. Transfer to a baking tray and bake at 200 degrees for 20 minutes.
4. Add the mushrooms for the last 6 minutes and cook them together.
5. Plate the rice and lay the turkey and mushrooms over it.' where id = 'b3c75b75-78ec-4cd6-8a8a-9b9b1c7d71f1';
update public.recipes set title_en = 'Baked Sea Bass with Couscous', instructions_en = 'INGREDIENTS:
- 180 g sea bass fillet
- 80 g couscous
- 1 lemon
- 1 clove garlic
- 10 ml olive oil
- fresh dill
- salt and black pepper

METHOD:
1. Set the sea bass on baking paper.
2. Top it with the garlic, dill, lemon slices and a little olive oil.
3. Bake in a preheated 180-degree oven for 15 minutes.
4. Steep the couscous in hot water for 5 minutes and fluff it with a fork.
5. Bring the couscous and sea bass together on the plate and serve.' where id = '15ae600f-6c57-491b-99b5-e2a6a926f0bf';
update public.recipes set title_en = 'Oven-Baked Salmon and Sweet Potato', instructions_en = 'INGREDIENTS:
- 170 g salmon fillet
- 200 g sweet potato
- 100 g broccoli
- 15 ml olive oil
- 1 clove garlic
- fresh dill, salt and black pepper

METHOD:
1. Toss the sweet potatoes with olive oil, salt and black pepper and bake at 200 degrees for 25 minutes.
2. Rub the salmon with dill and crushed garlic and add it to the tray for the last 12 minutes.
3. Steam the broccoli for 4 minutes.
4. Set the potato and broccoli beside the salmon and serve.' where id = '0f1fdd30-f916-4c85-964e-aa3e96a8f39b';
update public.recipes set title_en = 'Roasted Salmon and Sweet Potato', instructions_en = 'INGREDIENTS:
- 180 g salmon fillet
- 250 g sweet potato
- 120 g asparagus
- 1 clove garlic
- 15 ml extra virgin olive oil
- 1/2 lemon
- 1 sprig fresh thyme
- salt, black pepper and chilli flakes

METHOD:
1. Preheat the oven to 200 degrees and line a tray with baking paper.
2. Toss the sweet potato slices with half the olive oil, salt and chilli flakes and spread them in a single layer on one side of the tray; bake for 15 minutes.
3. Take the tray out and add the asparagus to the other side; set the salmon in the middle, skin-side down.
4. Rub the salmon with salt, black pepper and crushed garlic; lay the lemon slices and thyme sprig on top and drizzle the remaining oil over.
5. Return the tray to the oven and bake for 12-14 minutes more (the salmon should still look faintly pink in the middle).
6. Rest for 2 minutes, plate and serve hot.' where id = 'ec313347-045d-4edf-9c73-653df84e8591';
update public.recipes set title_en = 'Vegan Peanut Butter Banana Smoothie', instructions_en = 'INGREDIENTS:
- 1 frozen banana
- 300 ml oat milk
- 20 g natural peanut butter
- 15 g unsweetened cocoa powder
- 10 g plant protein powder
- 5 g date syrup
- 100 g ice

METHOD:
1. Put all the ingredients in a blender.
2. Blend on high for 60 seconds until it is a smooth drink.
3. Pour into a tall glass.
4. Dust a little cocoa powder over if you like and drink immediately.' where id = '265ad055-2146-494e-af57-271ad6154a66';
update public.recipes set title_en = 'Peanut Butter Banana Porridge', instructions_en = 'INGREDIENTS:
- 80 g rolled oats
- 250 ml milk
- 1 banana
- 30 g natural peanut butter
- 20 g chia seeds
- 15 g honey
- cinnamon

METHOD:
1. Cook the oats in the milk over low heat for 6-8 minutes until thick.
2. Transfer to a bowl and lay the sliced banana on top.
3. Swirl the peanut butter through with a spoon.
4. Finish with chia seeds, honey and cinnamon and serve hot.' where id = '061a039b-a898-4991-a058-33e23ac7538f';
update public.recipes set title_en = 'Peanut Butter Protein Porridge', instructions_en = 'INGREDIENTS:
- 60 g rolled oats
- 250 ml semi-skimmed milk
- 30 g vanilla whey protein powder
- 20 g natural peanut butter
- 1/2 banana
- 1 dessertspoon chia seeds
- cinnamon

METHOD:
1. Cook the oats in the milk over low heat for 6 minutes.
2. Take it off the heat and stir the protein powder in once it has cooled slightly.
3. Transfer to a bowl and top with the banana, peanut butter and chia seeds.
4. Scatter cinnamon over and serve hot.' where id = '01370365-605e-4ceb-8e99-c76ae07595bf';
update public.recipes set title_en = 'Peanut Butter Oat Porridge', instructions_en = 'INGREDIENTS:
- 50 g rolled oats
- 250 ml skimmed milk
- 1 tbsp natural peanut butter
- 1 ripe banana
- 10 g walnut halves
- 1 dessertspoon honey or maple syrup
- 1 a pinch of cinnamon
- 1 tsp chia seeds

METHOD:
1. Put the oats and milk in a small pan and bring to the boil over medium heat, stirring occasionally.
2. Once it boils, lower the heat and cook for 4-5 minutes more until creamy.
3. Take the pan off the heat, add the chia seeds and leave it to rest for 1 minute.
4. Transfer to a bowl; add the peanut butter while it is still warm so it melts in.
5. Scatter the sliced banana, walnut pieces and cinnamon, sweeten with honey and serve hot.' where id = '5fa526b5-3cdd-4abb-8ae6-a317870fba61';
update public.recipes set title_en = 'Pan-Fried Anchovies', instructions_en = 'INGREDIENTS:
- 200 g anchovies (fresh Black Sea anchovies; sardines work)
- 50 g cornflour (cornstarch)
- 10 ml sunflower oil
- 1/2 lemon
- salt
- black pepper

METHOD:
1. Season the anchovies with salt and black pepper.
2. Coat them in cornflour.
3. Fry in hot oil for 4 minutes until both sides are golden.
4. Serve with lemon.' where id = 'e9b728ed-f7f7-47eb-ba79-27d2921eb6a1';
update public.recipes set title_en = 'Mustard Chicken Salad', instructions_en = 'INGREDIENTS:
- 120 g cooked chicken breast
- 2 handfuls lettuce
- 1 tbsp strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 tsp mustard
- 5 ml olive oil
- salt

METHOD:
1. Whisk the yogurt, mustard, olive oil and salt together.
2. Put the lettuce in a bowl and lay the chicken over it.
3. Drizzle the dressing over.
4. Toss lightly and serve.' where id = 'c3e6db2d-8a34-4134-80d1-213707c2db12';
update public.recipes set title_en = 'Boiled Eggs and Tomato', instructions_en = 'INGREDIENTS:
- 2 eggs
- 1 tomato
- 5 olives
- 1 pinch black pepper
- 1 pinch salt
- a few sprigs of fresh parsley

METHOD:
1. Put the eggs in cold water and bring to the boil, then cook for 8 minutes more.
2. Cool them in cold water, peel and halve them.
3. Slice the tomato and arrange it on a plate with the olives.
4. Set the eggs on the plate and scatter salt, black pepper and parsley over.' where id = '4a7ce8ad-cc7e-4f69-ba67-3ee2827a4cbf';
update public.recipes set title_en = 'Quick Çiğ Köfte', instructions_en = 'INGREDIENTS:
- 100 g çiğ köfte mix (packet bulgur-and-spice mix; no raw meat in the modern version)
- 2 handfuls lettuce
- 1/2 lemon
- 1 slice bread

METHOD:
1. Knead the çiğ köfte mix according to the packet.
2. Shape it into small balls.
3. Wrap them in lettuce leaves.
4. Serve with lemon.' where id = 'c8145ef3-213a-44fe-8f6c-e6bd8e1c66e4';
update public.recipes set title_en = 'Pan-Fried Halloumi', instructions_en = 'INGREDIENTS:
- 100 g halloumi
- 5 ml olive oil
- 1 slice wholemeal bread
- 5 olives
- a few fresh mint leaves
- 1/2 lemon

METHOD:
1. Warm a pan with the olive oil.
2. Fry the halloumi slices for 2 minutes a side until golden.
3. Plate them alongside the bread, olives and mint.
4. Squeeze the lemon over and serve.' where id = '1365f62b-8998-4cb5-af9e-47b2d478c028';
update public.recipes set title_en = 'Turkey Lettuce Wrap', instructions_en = 'INGREDIENTS:
- 100 g turkey breast
- 4 large lettuce leaf
- 1 tbsp strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 tsp mustard
- 1/4 cucumber
- salt

METHOD:
1. Mix the yogurt and mustard together.
2. Lay the turkey, cucumber and dressing on a lettuce leaf.
3. Season with salt.
4. Roll the lettuce up tightly and serve.' where id = 'd3375cf6-45a4-491a-9003-ad76cb56fe6d';
update public.recipes set title_en = 'Quick Turkey Bulgur', instructions_en = 'INGREDIENTS:
- 80 g coarse bulgur
- 120 g turkey breast
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- salt

METHOD:
1. Fry the onion in the olive oil for 2 minutes.
2. Add the turkey and cook for 4 minutes until it changes colour.
3. Add the tomato paste, bulgur and 200 ml of hot water.
4. Cover, cook for 8 minutes and serve.' where id = 'ef148018-5d33-405f-b384-3c5bb3deb675';
update public.recipes set title_en = 'Turkey Köfte with Yogurt', instructions_en = 'INGREDIENTS:
- 150 g ground turkey
- 30 g breadcrumbs
- 200 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 1 small onion
- 5 ml olive oil
- salt

METHOD:
1. Knead the ground turkey, breadcrumbs, onion and salt together.
2. Shape into balls and cook in the olive oil for 6 minutes.
3. Turn them and cook for 4 minutes more.
4. Set them on the yogurt and serve.' where id = '14c3b11e-12c0-4df0-9aad-e46a187158ef';
update public.recipes set title_en = 'Turkey and Avocado Wrap', instructions_en = 'INGREDIENTS:
- 1 large wholemeal tortilla
- 120 g sliced turkey breast
- 1/2 avocado
- 1 handful rocket (arugula)
- 1 tomato
- 1 tbsp hummus
- 1 dessertspoon lemon juice

METHOD:
1. Warm the tortilla lightly in a pan.
2. Mash the avocado with the lemon juice and spread it on the tortilla.
3. Layer the hummus, turkey, rocket and tomato in turn.
4. Roll it tightly, cut it in half and serve immediately.' where id = '8228b6bf-ccd5-48a9-ac76-0b460b8705d9';
update public.recipes set title_en = 'Turkey Köfte with Grilled Courgette', instructions_en = 'INGREDIENTS:
- 180 g ground turkey
- 1 tbsp wholemeal breadcrumbs
- 1/4 onion
- 1 clove garlic
- 1 large courgette (zucchini)
- 10 ml olive oil
- oregano, cumin, salt and black pepper

METHOD:
1. Knead the ground turkey, breadcrumbs, onion, garlic and spices together and shape 6 köfte.
2. Cook the köfte in a non-stick pan for 4 minutes a side.
3. Grill the courgette slices for 3 minutes.
4. Plate the köfte with the courgette, drizzle with olive oil and serve.' where id = '0a65ccaa-a01c-4175-8449-d109e259df39';
update public.recipes set title_en = 'Turkey Salami Plate', instructions_en = 'INGREDIENTS:
- 80 g turkey salami
- 1 slice wholemeal bread
- 1 slice tomato
- 5 olives
- 30 g beyaz peynir (Turkish brined white cheese; feta works)
- a few fresh mint leaves

METHOD:
1. Arrange the turkey salami slices on a plate.
2. Set the beyaz peynir and olives to one side.
3. Add the tomato and bread.
4. Serve with mint.' where id = '929cec78-41c6-4e84-8e35-8d99640ee65b';
update public.recipes set title_en = 'Turkey Salami and Eggs', instructions_en = 'INGREDIENTS:
- 2 eggs
- 60 g turkey salami
- 5 ml olive oil
- 1 slice wholemeal bread
- a few sprigs of fresh parsley
- salt

METHOD:
1. Fry the salami slices in a pan for 1 minute.
2. Crack the eggs over the top and scatter the salt.
3. Take the pan off the heat once the eggs have set.
4. Serve with bread and parsley.' where id = 'ae78bbea-cfda-468e-908f-db8ae1d3b49e';
update public.recipes set title_en = 'Pasta with Turkey Sauce', instructions_en = 'INGREDIENTS:
- 100 g pasta
- 100 g turkey breast
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- salt

METHOD:
1. Boil the pasta in salted water and drain it.
2. Fry the onion in the olive oil for 2 minutes.
3. Add the turkey and cook for 4 minutes, add the tomato paste and simmer with 100 ml of water for 2 minutes.
4. Toss the pasta through the sauce and serve.' where id = 'b2ff317e-fb38-48ed-9412-88d86e852f62';
update public.recipes set title_en = 'Turkey Yogurt Wrap', instructions_en = 'INGREDIENTS:
- 1 lavash (thin Turkish flatbread; a large tortilla works)
- 100 g cooked turkey breast
- 100 g strained yogurt (Turkish süzme; Greek yogurt is the same thing)
- 2 leaves lettuce
- 1 slice tomato
- salt

METHOD:
1. Lay the lavash out flat.
2. Spread the yogurt over it and season with salt.
3. Lay out the lettuce, tomato and turkey.
4. Roll it up tightly, cut it in half and serve.' where id = '6a0ce3d2-89f6-4f36-9279-2a8fbcd7923a';
update public.recipes set title_en = 'Coconut Chia Pudding', instructions_en = 'INGREDIENTS:
- 25 g chia seeds
- 250 ml coconut milk
- 1 tbsp honey
- 20 g desiccated coconut
- 1 banana

METHOD:
1. Whisk the chia, milk and honey together and rest for 10 minutes.
2. Stir again and divide between bowls.
3. Add the banana slices and desiccated coconut.
4. Serve cold.' where id = 'ab7df82a-8a39-449a-b187-c66ede193752';
update public.recipes set title_en = 'Coconut Milk Pudding', instructions_en = 'INGREDIENTS:
- 250 ml milk
- 25 g rice flour
- 30 g sugar
- 20 g desiccated coconut
- 1 packet vanilla

METHOD:
1. Slake the rice flour with 50 ml of cold milk.
2. Bring the remaining milk to the boil and add the sugar and vanilla.
3. Add the rice flour mixture and stir for 6 minutes until it thickens.
4. Divide between bowls and scatter the coconut over the top.' where id = '56b3ce28-d009-47be-9ff1-fd5c8a6c32dc';
update public.recipes set title_en = 'Quick Semolina Halva', instructions_en = 'INGREDIENTS:
- 100 g semolina
- 50 g butter
- 60 g sugar
- 300 ml milk
- 15 g pine nuts

METHOD:
1. Toast the pine nuts in the butter for 1 minute.
2. Add the semolina and toast for 4 minutes until it turns golden.
3. Add the milk and sugar and stir until it thickens.
4. Take it off the heat, rest for 5 minutes, press into a mould and serve.' where id = '2fe3d9aa-ef47-4b8c-9694-d07190f0ac12';
update public.recipes set title_en = 'Quick Crêpes with Jam', instructions_en = 'INGREDIENTS:
- 2 eggs
- 60 g flour
- 150 ml milk
- 5 ml butter
- 2 tbsp jam

METHOD:
1. Whisk the eggs, flour and milk until smooth.
2. Pour a little batter into an oiled pan and cook thin crêpes (1-2 minutes each).
3. Fill the crêpes with jam and roll them up.
4. Plate and serve.' where id = '8052bba5-2a2a-4167-84f6-71d3743b9711';
update public.recipes set title_en = 'Quick White Bean Stew', instructions_en = 'INGREDIENTS:
- 200 g cooked white beans
- 1 small onion
- 1 tbsp tomato paste
- 5 ml olive oil
- 1 tsp chilli flakes
- salt

METHOD:
1. Fry the onion in the olive oil for 2 minutes.
2. Add the tomato paste and fry for 1 minute more.
3. Add the beans and 200 ml of hot water and simmer for 8 minutes.
4. Season with chilli flakes and salt and serve.' where id = 'c319deb7-b804-4533-af20-736064c529d3';
update public.recipes set title_en = 'Quick Lentil Köfte', instructions_en = 'INGREDIENTS:
- 200 g cooked red lentils
- 30 g fine bulgur
- 1 small onion
- 1 tsp olive oil
- a pinch of fresh parsley
- 1/2 lemon

METHOD:
1. Chop the onion very fine and sauté it in the olive oil for 2 minutes.
2. Put the hot lentils and bulgur in a bowl, add the sautéed onion and knead together.
3. Rest the mixture for 5 minutes and shape small köfte in your hand.
4. Scatter parsley over and serve with lemon.' where id = 'da31c81d-fd52-459a-a8f3-46f8d5a715b5';
update public.recipes set title_en = 'Quick Lokma', instructions_en = 'INGREDIENTS:
- 80 g flour
- 1 packet yeast
- 200 ml lukewarm water
- 50 g sugar
- 30 ml sunflower oil
- 1 tbsp honey

METHOD:
1. Mix the flour, yeast and water in a bowl and let it prove for 5 minutes.
2. Heat the oil and drop small spoonfuls of the batter in.
3. Fry for 4 minutes until golden.
4. Steep in the sugar and honey syrup and serve.' where id = '3c296846-e695-48c8-b4ff-8c89a1585d29';
update public.recipes set title_en = 'Quick Chicken Cutlets', instructions_en = 'INGREDIENTS:
- 200 g chicken cutlet
- 5 ml olive oil
- 1 clove garlic
- 1/2 lemon
- salt and black pepper

METHOD:
1. Marinate the cutlets in the olive oil, garlic, lemon and spices for 5 minutes.
2. Cook each side for 4 minutes in a hot griddle pan.
3. Cover and rest for 2 minutes.
4. Serve hot.' where id = '99c97c76-6ffa-44d5-b6b3-28e0f0861638';
update public.recipes set title_en = 'Quick Lentil Soup with Egg', instructions_en = 'INGREDIENTS:
- 1 small jar of cooked red lentils
- 1 eggs
- 1/2 lemon
- 1 tbsp butter
- 1 tsp chilli flakes
- 1 pinch salt

METHOD:
1. Put the lentils and their liquid in a pan and bring to the boil.
2. Beat the egg and add it to the pan in a thin stream, stirring constantly.
3. Add the salt and simmer for 2 minutes more.
4. Melt the butter and bloom the chilli flakes in it, pour it over the soup and serve with lemon.' where id = 'bf56330b-1533-4aac-8a28-1ea1d5e367ad';
update public.recipes set title_en = 'Spinach and Cheese Omelette', instructions_en = 'INGREDIENTS:
- 3 whole egg
- 1 handful baby spinach
- 30 g low-fat beyaz peynir (Turkish brined white cheese; light feta works)
- 5 ml olive oil
- salt, black pepper and fresh dill

METHOD:
1. Beat the eggs and add the salt and black pepper.
2. Warm the olive oil in a non-stick pan and sauté the spinach for 1 minute.
3. Pour in the egg mixture and cook over medium heat until the edges set.
4. Scatter the cheese and dill over, fold the omelette in half and serve hot.' where id = '3208f001-4786-4e84-b679-203ccc625390';
update public.recipes set title_en = 'Grilled Beef Fillet with Broccoli', instructions_en = 'INGREDIENTS:
- 200 g beef sirloin
- 200 g broccoli
- 15 g butter
- 2 cloves garlic
- 10 ml olive oil
- 1 sprig fresh rosemary
- salt and black pepper

METHOD:
1. Take the beef out of the fridge 30 minutes before cooking and bring it to room temperature.
2. Sear each side for 3 minutes over high heat in a cast-iron pan.
3. Lower the heat; add the butter, garlic and rosemary and baste the beef with the fat.
4. Sauté the broccoli in olive oil in a separate pan for 4 minutes.
5. Rest the beef for 5 minutes, slice it and serve with the broccoli.' where id = '2412acfb-f68c-47e9-8de0-90571cd2c809';
update public.recipes set title_en = 'Grilled Beef Fillet with Roasted Vegetables', instructions_en = 'INGREDIENTS:
- 180 g beef sirloin
- 1 aubergine (eggplant)
- 1 courgette (zucchini)
- 1 red pepper
- 10 ml olive oil
- 2 cloves garlic
- rosemary, salt and black pepper

METHOD:
1. Toss the vegetables with olive oil, crushed garlic and the spices.
2. Roast at 200 degrees for 18 minutes.
3. Bring the beef to room temperature and sear each side for 3 minutes in a cast-iron pan.
4. Rest for 5 minutes, slice and serve with the vegetables.' where id = '0a1cf981-c51a-4b61-9d9b-e9693c4a62d7';
update public.recipes set title_en = 'Grilled Turkey Rice Bowl', instructions_en = 'INGREDIENTS:
- 160 g turkey breast fillet
- 70 g brown rice
- 100 g grilled courgette (zucchini)
- 100 g roasted red pepper
- 5 ml olive oil
- 1 clove garlic
- oregano, salt and black pepper

METHOD:
1. Cook the rice in plenty of water for 25 minutes.
2. Marinate the turkey with garlic, thyme and the spices and grill each side for 3 minutes.
3. Grill the courgette and pepper for 4 minutes.
4. Combine the rice, vegetables and sliced turkey in a bowl and serve.' where id = 'acccd4e0-c701-499e-8292-f75a7e58e357';
update public.recipes set title_en = 'Grilled Shrimp and Rocket Salad', instructions_en = 'INGREDIENTS:
- 150 g peeled shrimp
- 50 g rocket (arugula)
- 1/2 avocado
- 10 cherry tomatoes
- 10 ml olive oil
- 2 cloves garlic
- 1 grated zest of one lemon
- chilli flakes

METHOD:
1. Marinate the shrimp with garlic, lemon zest and chilli flakes for 10 minutes.
2. Cook them in a dry non-stick pan for 3 minutes, turning.
3. Arrange the rocket, sliced avocado and cherry tomatoes on a plate.
4. Lay the shrimp over the top, drizzle with olive oil and serve.' where id = '60b70292-54c6-4f0f-8433-2d56e2b6c2a8';
update public.recipes set title_en = 'Grilled Sea Bass with Steamed Vegetables', instructions_en = 'INGREDIENTS:
- 180 g sea bass fillet
- 120 g broccoli
- 100 g carrot
- 80 g courgette (zucchini)
- 10 ml olive oil
- 1 lemon
- fresh dill, salt and black pepper

METHOD:
1. Marinate the sea bass with lemon slices and dill.
2. Steam the vegetables for 6 minutes.
3. Griddle the sea bass in a non-stick pan for 3 minutes a side.
4. Drizzle with olive oil and serve with the vegetables.' where id = 'c93acf1e-8896-41a5-9b38-d85a6786f361';
update public.recipes set title_en = 'Tuna Salad with Grilled Vegetables', instructions_en = 'INGREDIENTS:
- 120 g drained canned tuna
- 1 handful lettuce leaf
- 1/2 cucumber
- 1 tomato
- 50 g grilled courgette (zucchini)
- 30 g roasted red pepper
- 10 ml olive oil
- 1 dessertspoon lemon juice

METHOD:
1. Roughly chop the lettuce, cucumber and tomato into a wide bowl.
2. Slice the grilled vegetables and add them.
3. Spread the tuna over the salad.
4. Whisk the olive oil and lemon juice together, drizzle over the salad and serve.' where id = '24b0010a-1211-4d6a-b238-8a7e07197328';
update public.recipes set title_en = 'Grilled Salmon and Sweet Potato', instructions_en = 'INGREDIENTS:
- 150 g salmon
- 200 g sweet potato
- asparagus
- olive oil

METHOD:
1. Bake the sweet potatoes in the oven.
2. Cook the salmon in a pan or in the oven.
3. Sauté the asparagus.
4. Arrange everything on the plate.' where id = 'b3939d44-6c10-40b9-ac03-02728edb3828';
update public.recipes set title_en = 'Grilled Chicken Quinoa Bowl', instructions_en = 'INGREDIENTS:
- 180 g chicken breast fillet
- 60 g quinoa
- 1 handful baby spinach leaves
- 1/2 avocado
- 10 ml olive oil
- 1 dessertspoon lemon juice
- salt, black pepper and cumin

METHOD:
1. Boil the quinoa in three times its volume of water for 15 minutes and drain.
2. Marinate the chicken with salt, black pepper and cumin and cook each side for 3 minutes on a hot griddle.
3. Layer the quinoa, spinach and sliced avocado in a bowl.
4. Slice the chicken over the top, drizzle with the olive oil and lemon dressing and serve.' where id = 'ab7a79b3-fa9c-4976-bd6c-ff44b13f6ca1';
update public.recipes set title_en = 'Grilled Chicken Light Caesar Salad', instructions_en = 'INGREDIENTS:
- 150 g chicken breast fillet
- 1 large handful of lettuce
- 20 g parmesan cheese
- 20 g wholemeal croutons
- 1 tbsp fat-free yogurt
- 1 dessertspoon dijon mustard
- 5 ml olive oil
- salt, black pepper and garlic powder

METHOD:
1. Marinate the chicken with garlic powder, salt and black pepper and grill each side for 4 minutes.
2. Whisk the yogurt, mustard, olive oil and a pinch of salt into a light Caesar dressing.
3. Toss the lettuce through the dressing and add the parmesan and croutons.
4. Slice the rested chicken over the top and serve.' where id = '4de04113-29b9-49f8-9b7f-9048a096b5a6';
update public.recipes set title_en = 'Grilled Chicken Quinoa Salad', instructions_en = 'INGREDIENTS:
- 150 g chicken breast fillet
- 50 g quinoa
- 1 handful rocket (arugula)
- 1/2 cucumber
- 8 cherry tomatoes
- 30 g light beyaz peynir (Turkish brined white cheese; light feta works)
- 10 g sunflower seeds
- 15 ml extra virgin olive oil
- 1 tbsp lemon juice
- salt, black pepper and oregano

METHOD:
1. Rinse the quinoa under running water and cook it in 150 ml of boiling water over low heat for 15 minutes; once the water is absorbed, cover and rest for 5 minutes more.
2. Rub the chicken breast with salt, black pepper and thyme; cook each side for 4 minutes in a hot griddle pan and rest for 2 minutes.
3. Combine the cooked quinoa, rocket, cucumber, cherry tomatoes and cheese cubes in a wide salad bowl.
4. Cut the chicken into thick slices on the diagonal and lay them over the salad.
5. Whisk the olive oil and lemon juice in a small bowl and drizzle it over the salad.
6. Scatter the sunflower seeds and serve immediately.' where id = 'c8669e27-8430-4b97-b127-902e9d342e71';
update public.recipes set title_en = 'Cocoa Date Balls', instructions_en = 'INGREDIENTS:
- 8 dates
- 30 g almonds
- 1 tbsp unsweetened cocoa
- 15 g desiccated coconut
- 1 pinch salt

METHOD:
1. Blitz the dates and almonds in a food processor.
2. Add the salt and knead.
3. Roll into walnut-sized balls and coat them first in cocoa, then in desiccated coconut.
4. Chill for 5 minutes and serve.' where id = '5b7da9b2-8a49-41c4-b8de-f33fcc5c8df4';
update public.recipes set title_en = 'Cocoa Oat Porridge', instructions_en = 'INGREDIENTS:
- 50 g rolled oats
- 250 ml milk
- 1 tbsp unsweetened cocoa
- 1 tbsp honey
- 1 pinch cinnamon

METHOD:
1. Put the milk and oats in a pan and bring to the boil over medium heat.
2. Add the cocoa and stir it in without letting it clump.
3. Cook for 3 minutes more and transfer to a bowl.
4. Finish with honey and cinnamon and serve hot.' where id = '5792cbe9-8e95-412b-8dbd-b0efb16dd4ac';

commit;

