// Generates `test/support/pseudo_localizations.dart` — a wrapper around
// the generated [AppLocalizations] that runs every string through
// `pseudoLocalize` before handing it to the widget tree.
//
// Why a generated wrapper rather than a third ARB + locale:
//
//   • A pseudo ARB would produce another ~1300-method localisation class
//     that the release binary carries for a debug-only feature, and it
//     would need a real language code in `supportedLocales` that a real
//     device could resolve to.
//   • The wrapper lives under `test/`, so it costs the shipped app
//     nothing and cannot be reached by a user.
//   • Wrapping the RESULT rather than the ARB template also means ICU has
//     already run: pseudo mode can never break a plural or a placeholder,
//     it can only make the finished sentence longer.
//
// Run: dart run tool/gen_pseudo_localizations.dart
// Check (CI): dart run tool/gen_pseudo_localizations.dart --check

import 'dart:io';

const _source = 'lib/l10n/app_localizations.dart';
const _target = 'test/support/pseudo_localizations.dart';

/// `  String get someKey;`
final _getter = RegExp(r'^  String get (\w+);$', multiLine: true);

/// `  String someKey(int count, String name);`
final _method = RegExp(r'^  String (\w+)\(([^)]*)\);$', multiLine: true);

void main(List<String> args) {
  final check = args.contains('--check');
  final source = File(_source);
  if (!source.existsSync()) {
    stderr.writeln('missing $_source — run `flutter gen-l10n` first');
    exit(2);
  }
  final text = source.readAsStringSync();

  final getters = _getter.allMatches(text).map((m) => m.group(1)!).toList();
  final methods = _method
      .allMatches(text)
      .map((m) => (name: m.group(1)!, params: m.group(2)!))
      .toList();

  if (getters.isEmpty && methods.isEmpty) {
    stderr.writeln('parsed 0 members out of $_source — the generated '
        'shape changed and this tool needs updating');
    exit(2);
  }

  final buffer = StringBuffer(_header(getters.length + methods.length));
  for (final name in getters) {
    buffer.writeln('  @override');
    buffer.writeln('  String get $name => pseudoLocalize(_inner.$name);');
    buffer.writeln();
  }
  for (final method in methods) {
    final args = _argumentNames(method.params);
    buffer.writeln('  @override');
    buffer.writeln('  String ${method.name}(${method.params}) =>');
    buffer.writeln('      pseudoLocalize(_inner.${method.name}($args));');
    buffer.writeln();
  }
  buffer.writeln('  /// Number of members this wrapper covers. The test '
      'suite asserts');
  buffer.writeln('  /// it still matches the generated class, so a new ARB '
      'key cannot');
  buffer.writeln('  /// slip past pseudo mode unnoticed.');
  buffer.writeln('  static const int coveredMembers = '
      '${getters.length + methods.length};');
  buffer.writeln('}');

  final target = File(_target);
  // Emit, then hand it to `dart format` so the checked-in file is
  // byte-identical to what the repo's format gate expects. Comparing
  // unformatted output would make --check disagree with the formatter.
  final output = _formatted(buffer.toString());

  if (check) {
    final current = target.existsSync() ? target.readAsStringSync() : '';
    if (current != output) {
      stderr.writeln('$_target is stale — run '
          '`dart run tool/gen_pseudo_localizations.dart`');
      exit(1);
    }
    stdout.writeln('✓ $_target is up to date '
        '(${getters.length + methods.length} members)');
    return;
  }

  target.parent.createSync(recursive: true);
  target.writeAsStringSync(output);
  stdout.writeln('wrote $_target — ${getters.length} getters, '
      '${methods.length} parameterised messages');
}

/// Runs the source through `dart format` via a scratch file.
///
/// The scratch file lives inside the package, not in the system temp
/// directory: `dart format` resolves the language version from the
/// enclosing pubspec, and formatting outside the package picks a
/// different style — which made this tool and the repo's format gate
/// disagree about the same bytes.
String _formatted(String source) {
  final scratch = File('.dart_tool/pseudo_localizations_scratch.dart')
    ..createSync(recursive: true)
    ..writeAsStringSync(source);
  final result = Process.runSync('dart', ['format', scratch.path]);
  if (result.exitCode != 0) {
    stderr.writeln('dart format failed: ${result.stderr}');
    exit(2);
  }
  final formatted = scratch.readAsStringSync();
  scratch.deleteSync();
  return formatted;
}

/// Turns `int count, String name` into `count, name`.
String _argumentNames(String params) {
  if (params.trim().isEmpty) return '';
  return params
      .split(',')
      .map((p) => p.trim().split(RegExp(r'\s+')).last)
      .join(', ');
}

String _header(int members) => '''
// GENERATED by tool/gen_pseudo_localizations.dart — do not edit by hand.
//
// Wraps [AppLocalizations] so every string comes back bracketed and ~40%
// longer. Two bugs surface without paying a translator a word:
//
//   1. a screen that renders plain Turkish is reading a literal the
//      extraction missed;
//   2. a layout that only fits Turkish overflows here instead of in a
//      German store review.
//
// $members members covered.

import 'package:flutter/widgets.dart';
import 'package:sixpack_ai/core/utils/pseudo_locale.dart';
import 'package:sixpack_ai/l10n/app_localizations.dart';

/// Delegate that loads the real localisations and wraps them.
class PseudoLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const PseudoLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.delegate.isSupported(locale);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      PseudoAppLocalizations(await AppLocalizations.delegate.load(locale));

  @override
  bool shouldReload(PseudoLocalizationsDelegate old) => false;
}

/// The same delegate list the app uses, with the localisations delegate
/// swapped for the pseudo one.
List<LocalizationsDelegate<dynamic>> get pseudoLocalizationsDelegates => [
      const PseudoLocalizationsDelegate(),
      ...AppLocalizations.localizationsDelegates
          .where((d) => d != AppLocalizations.delegate),
    ];

class PseudoAppLocalizations extends AppLocalizations {
  PseudoAppLocalizations(this._inner) : super(_inner.localeName);

  final AppLocalizations _inner;

''';
