/// Roadmap Phase 7 · derive `recipes.diet_flags` from the structured
/// ingredient rows migration 014 created.
///
///     dart run tool/recipe_pipeline/classify_catalogue.dart \
///         --input  <recipes_with_ingredients.json> \
///         --sql    supabase/sql/phase07_recipe_diet_flags.sql \
///         --review docs/nutrition/DIET_CLASSIFICATION_REVIEW.md
///
/// `--input` is a JSON array of `{id, title, ingredients: [name, …]}`.
/// Like every other tool in this directory it writes files and never
/// touches the database: a dietary claim is exactly the kind of thing
/// that should be read by a person before it ships.
///
/// The review sheet leads with what was NOT classified, because that is
/// the interesting half — an unrecognised ingredient means a recipe
/// makes no claim, and the fix is a word in the classifier's term table.
library;

import 'dart:convert';
import 'dart:io';

import 'diet_classifier.dart';

void main(List<String> args) {
  final options = _parseArgs(args);
  final input = File(options['input'] ?? '');
  if (!input.existsSync()) {
    stderr.writeln('missing --input <recipes.json>');
    exit(2);
  }

  final rows = (jsonDecode(input.readAsStringSync()) as List)
      .cast<Map<String, dynamic>>();

  final sql = StringBuffer()
    ..writeln('-- Roadmap Phase 7 · derived dietary flags.')
    ..writeln('-- Generated by tool/recipe_pipeline/classify_catalogue.dart —')
    ..writeln('-- do not hand-edit; change the classifier and re-run.')
    ..writeln('--')
    ..writeln('-- `halal` never appears here. It cannot be derived from an')
    ..writeln('-- ingredient list and is authored; see the classifier.')
    ..writeln()
    ..writeln('begin;');

  final unclassified = <({String title, List<String> unknown})>[];
  final flagTally = <String, int>{};
  final unknownTally = <String, int>{};
  var classified = 0;

  for (final row in rows) {
    final id = row['id'] as String;
    final title = (row['title'] as String?) ?? '(untitled)';
    final names = (row['ingredients'] as List? ?? const [])
        .map((e) => e.toString())
        .toList();

    final flags = classifyDiet(names);
    if (flags.isEmpty) {
      final unknown = names
          .where((name) => classifyIngredient(name).isEmpty)
          .toList(growable: false);
      for (final name in unknown) {
        unknownTally[name] = (unknownTally[name] ?? 0) + 1;
      }
      unclassified.add((title: title, unknown: unknown));
      continue;
    }

    classified += 1;
    for (final flag in flags) {
      flagTally[flag] = (flagTally[flag] ?? 0) + 1;
    }
    final array = flags.map((f) => "'$f'").join(', ');
    sql
      ..writeln('-- ${title.replaceAll('\n', ' ')}')
      ..writeln('update public.recipes set diet_flags = ARRAY[$array]::text[] '
          "where id = '$id';");
  }

  sql
    ..writeln()
    ..writeln('commit;');

  final review = StringBuffer()
    ..writeln('# Diet classification — review sheet')
    ..writeln()
    ..writeln('Generated by `tool/recipe_pipeline/classify_catalogue.dart`.')
    ..writeln('Regenerate rather than edit.')
    ..writeln()
    ..writeln('A flag here is a claim made to somebody who may have a medical')
    ..writeln('or ethical reason to rely on it. The classifier only makes one')
    ..writeln('when it recognises **every** ingredient in the recipe; one')
    ..writeln('unknown word and the recipe stays silent. `halal` is never')
    ..writeln('derived — it depends on how an animal was slaughtered, which')
    ..writeln('no ingredient name records.')
    ..writeln()
    ..writeln('```')
    ..writeln('recipes read        ${rows.length}')
    ..writeln('classified          $classified')
    ..writeln('no claim made       ${unclassified.length}')
    ..writeln('```')
    ..writeln()
    ..writeln('## Flags derived')
    ..writeln()
    ..writeln('| flag | recipes |')
    ..writeln('| --- | --- |');
  final sortedFlags = flagTally.entries.toList()
    ..sort((a, b) => b.value.compareTo(a.value));
  for (final entry in sortedFlags) {
    review.writeln('| `${entry.key}` | ${entry.value} |');
  }

  review
    ..writeln()
    ..writeln('## Ingredients the classifier does not recognise')
    ..writeln()
    ..writeln('Each one silences every recipe that uses it. Adding a term to')
    ..writeln('`diet_classifier.dart` is the fix — unless the ingredient')
    ..writeln('genuinely varies by brand, in which case silence is correct.')
    ..writeln();
  if (unknownTally.isEmpty) {
    review.writeln('None.');
  } else {
    review
      ..writeln('| ingredient | recipes blocked |')
      ..writeln('| --- | --- |');
    final sortedUnknown = unknownTally.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    for (final entry in sortedUnknown) {
      review.writeln('| ${entry.key} | ${entry.value} |');
    }
  }

  review
    ..writeln()
    ..writeln('## Recipes making no claim')
    ..writeln();
  if (unclassified.isEmpty) {
    review.writeln('None.');
  } else {
    for (final entry in unclassified) {
      review.writeln('- **${entry.title}** — ${entry.unknown.join(', ')}');
    }
  }

  _write(options['sql'], sql.toString());
  _write(options['review'], review.toString());

  stdout
    ..writeln('recipes       ${rows.length}')
    ..writeln('classified    $classified')
    ..writeln('no claim      ${unclassified.length}');
  for (final entry in sortedFlags) {
    stdout.writeln('  ${entry.key.padRight(14)} ${entry.value}');
  }
  for (final entry in unknownTally.entries) {
    stdout.writeln('  ? unrecognised: ${entry.key} (${entry.value} recipes)');
  }
}

void _write(String? path, String contents) {
  if (path == null || path.isEmpty) return;
  final file = File(path);
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(contents);
  stdout.writeln('wrote $path');
}

Map<String, String> _parseArgs(List<String> args) {
  final out = <String, String>{};
  for (var i = 0; i < args.length; i++) {
    if (!args[i].startsWith('--')) continue;
    final key = args[i].substring(2);
    if (i + 1 < args.length && !args[i + 1].startsWith('--')) {
      out[key] = args[i + 1];
      i += 1;
    } else {
      out[key] = 'true';
    }
  }
  return out;
}
