/// Roadmap Phase 7 · one-off: read the authored recipe catalogue, split
/// every `MALZEMELER:` block, and emit the SQL that fills
/// `public.recipe_ingredients`.
///
///     dart run tool/recipe_pipeline/parse_catalogue.dart \
///         --input  <catalogue.json> \
///         --sql    supabase/sql/phase07_recipe_ingredients.sql \
///         --review docs/nutrition/INGREDIENT_PARSE_REVIEW.md
///
/// `--input` is a JSON array of `{id, title, instructions}`, dumped from
/// Supabase. The tool never talks to the database itself: everything it
/// produces is a file a human can read before anything is applied, which
/// is the same rule §7.2 of the plan sets for the generation pipeline.
///
/// Exits non-zero when any recipe fails to parse cleanly, so this can be
/// re-run as a check after a content edit.
library;

import 'dart:convert';
import 'dart:io';

import 'ingredient_parser.dart';

void main(List<String> args) {
  final options = _parseArgs(args);
  final input = File(options['input'] ?? '');
  if (!input.existsSync()) {
    stderr.writeln('missing --input <catalogue.json>');
    exit(2);
  }

  final rows = (jsonDecode(input.readAsStringSync()) as List)
      .cast<Map<String, dynamic>>();

  final sql = StringBuffer();
  final review = StringBuffer();
  var cleanRecipes = 0;
  var totalIngredients = 0;
  var lowConfidence = 0;
  final dirty = <({String title, String id, ParsedRecipeBody body})>[];
  final unitTally = <String, int>{};
  var noQuantity = 0;

  sql
    ..writeln('-- Roadmap Phase 7 · structured ingredients for the authored')
    ..writeln(
        '-- catalogue. Generated by tool/recipe_pipeline/parse_catalogue.dart —')
    ..writeln('-- do not hand-edit; fix the parser or the recipe and re-run.')
    ..writeln('--')
    ..writeln('-- Idempotent: every recipe it touches is cleared first, so')
    ..writeln(
        '-- re-running after a content edit resyncs rather than duplicates.')
    ..writeln()
    ..writeln('begin;');

  for (final row in rows) {
    final id = row['id'] as String;
    final title = (row['title'] as String?) ?? '(untitled)';
    final body = parseRecipeBody((row['instructions'] as String?) ?? '');

    if (body.isClean) {
      cleanRecipes += 1;
    } else {
      dirty.add((title: title, id: id, body: body));
    }
    totalIngredients += body.ingredients.length;

    if (body.ingredients.isEmpty) continue;

    sql
      ..writeln()
      ..writeln('-- ${_sqlComment(title)}')
      ..writeln(
          "delete from public.recipe_ingredients where recipe_id = '$id';")
      ..writeln('insert into public.recipe_ingredients')
      ..writeln('  (recipe_id, position, quantity, unit, name_tr, note_tr)')
      ..writeln('values');

    final values = <String>[];
    for (final ingredient in body.ingredients) {
      if (!ingredient.confident) lowConfidence += 1;
      if (ingredient.quantity == null) noQuantity += 1;
      if (ingredient.unit != null) {
        unitTally[ingredient.unit!] = (unitTally[ingredient.unit!] ?? 0) + 1;
      }
      values.add(
        "  ('$id', ${ingredient.position}, ${_num(ingredient.quantity)}, "
        '${_text(ingredient.unit)}, ${_text(ingredient.nameTr)}, '
        '${_text(ingredient.noteTr)})',
      );
    }
    sql.writeln('${values.join(',\n')};');
  }

  sql
    ..writeln()
    ..writeln('commit;');

  review
    ..writeln('# Ingredient parse — review sheet')
    ..writeln()
    ..writeln('Generated by `tool/recipe_pipeline/parse_catalogue.dart`.')
    ..writeln(
        'Regenerate rather than edit; this file is a report, not a source.')
    ..writeln()
    ..writeln('```')
    ..writeln('recipes read              ${rows.length}')
    ..writeln('parsed clean              $cleanRecipes')
    ..writeln('needing a human           ${dirty.length}')
    ..writeln('ingredient rows           $totalIngredients')
    ..writeln('rows flagged low-confidence  $lowConfidence')
    ..writeln(
        'rows with no quantity     $noQuantity  (Tuz, Karabiber — expected)')
    ..writeln('```')
    ..writeln()
    ..writeln('## Units found')
    ..writeln()
    ..writeln(
        'Every unit below is in `kKnownUnits`. A unit the parser does not')
    ..writeln('know is not silently dropped — it stays part of the ingredient')
    ..writeln('name, which shows up here as a name starting with a word that')
    ..writeln('should have been a unit.')
    ..writeln()
    ..writeln('| unit | rows |')
    ..writeln('| --- | --- |');
  final sortedUnits = unitTally.entries.toList()
    ..sort((a, b) => b.value.compareTo(a.value));
  for (final entry in sortedUnits) {
    review.writeln('| `${entry.key}` | ${entry.value} |');
  }

  review
    ..writeln()
    ..writeln('## Recipes needing a human')
    ..writeln();
  if (dirty.isEmpty) {
    review.writeln('None. Every recipe split cleanly.');
  } else {
    for (final entry in dirty) {
      review
        ..writeln('### ${entry.title}')
        ..writeln()
        ..writeln('`${entry.id}`')
        ..writeln();
      for (final problem in entry.body.problems) {
        review.writeln('- $problem');
      }
      review.writeln();
      for (final ingredient in entry.body.ingredients) {
        final flag = ingredient.confident ? '' : '  ← **review**';
        review.writeln(
          '- `${ingredient.quantity ?? "—"} ${ingredient.unit ?? ""}`'
          ' ${ingredient.nameTr}$flag',
        );
      }
      review.writeln();
    }
  }

  _write(options['sql'], sql.toString());
  _write(options['review'], review.toString());

  stdout
    ..writeln('recipes           ${rows.length}')
    ..writeln('clean             $cleanRecipes')
    ..writeln('need a human      ${dirty.length}')
    ..writeln('ingredient rows   $totalIngredients')
    ..writeln('low confidence    $lowConfidence');
  for (final entry in dirty) {
    stdout.writeln('  ! ${entry.title}: ${entry.body.problems.join("; ")}');
  }
  if (dirty.isNotEmpty) exit(1);
}

void _write(String? path, String contents) {
  if (path == null || path.isEmpty) return;
  final file = File(path);
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(contents);
  stdout.writeln('wrote $path');
}

String _num(num? value) {
  if (value == null) return 'null';
  if (value == value.roundToDouble()) return value.round().toString();
  // Three places is enough for 1/3 and never enough to imply precision
  // the author did not write.
  return value.toStringAsFixed(3);
}

String _text(String? value) {
  if (value == null || value.isEmpty) return 'null';
  return "'${value.replaceAll("'", "''")}'";
}

String _sqlComment(String value) => value.replaceAll('\n', ' ');

Map<String, String> _parseArgs(List<String> args) {
  final out = <String, String>{};
  for (var i = 0; i < args.length; i++) {
    if (!args[i].startsWith('--')) continue;
    final key = args[i].substring(2);
    if (i + 1 < args.length && !args[i + 1].startsWith('--')) {
      out[key] = args[i + 1];
      i += 1;
    } else {
      out[key] = 'true';
    }
  }
  return out;
}
