-- FormAI — where a recipe comes from, and who can eat it
--
-- Roadmap Phase 7 · `PHASE_07_NUTRITION_I18N_PLAN.md` §4.3.
--
-- Phase 6 shipped an English app with a Turkish pantry. Translating the
-- 292 recipes fixes the language and not the problem: a perfect English
-- translation of `Yumurtalı Sucuklu Tava` is still a recipe an American
-- user cannot shop for. §5 of the plan authors new content for that, and
-- these three columns are what it selects on.
--
-- `locale_scope` ORDERS, IT DOES NOT FILTER
--
-- This is the load-bearing decision in the migration and the one most
-- likely to be misread by a later query. `locale_scope = {'en'}` means
-- "lead with this for English readers", not "hide this from everyone
-- else". Hiding by locale halves the catalogue for every user, and users
-- notice — a Turkish user browsing should still be able to find a
-- protein pancake, and an English user should still find menemen.
--
-- An empty array means "no preference", which is the correct default and
-- why the column is `not null default '{}'` rather than nullable.
--
-- `pork_free` IS NOT `halal`
--
-- They are separate columns' worth of meaning inside one array, and
-- conflating them is the kind of error that makes an app untrustworthy
-- in a market. Halal requires the animal to have been slaughtered a
-- particular way; that is not a property of the word "dana kıyma" and
-- cannot be derived from an ingredient list. So `pork_free` is derived
-- and `halal` is authored — `tool/recipe_pipeline/diet_classifier.dart`
-- never sets the latter, deliberately.
--
-- The audit behind the derived `pork_free`, since the plan asks for one
-- rather than an assumption: all 297 distinct ingredient names in the
-- live catalogue were classified. `sucuk` and `pastırma` are beef in
-- Turkey; the only cured slice is `hindi salam`, which is turkey. None
-- is pork.

alter table public.recipes
  add column if not exists cuisine      text,
  add column if not exists diet_flags   text[] not null default '{}',
  add column if not exists locale_scope text[] not null default '{}';

comment on column public.recipes.cuisine is
  'Roadmap Phase 7 · culinary origin: turkish, mediterranean, american, '
  'asian, mexican, indian, levantine, generic. Free text rather than an '
  'enum so a new cuisine does not need a migration.';

comment on column public.recipes.diet_flags is
  'Roadmap Phase 7 · vegan, vegetarian, halal, gluten_free, dairy_free, '
  'pork_free. Derived from the ingredient list EXCEPT halal, which '
  'cannot be derived and is authored. An empty array means no claim is '
  'made, which is what an unrecognised ingredient produces — never a '
  'guess.';

comment on column public.recipes.locale_scope is
  'Roadmap Phase 7 · languages this recipe LEADS for. Empty = no '
  'preference. This orders results; it must never filter them. Hiding '
  'recipes by locale halves the catalogue for everyone.';

-- GIN on `diet_flags` because the query is containment
-- (`diet_flags @> ARRAY['vegan']`), same shape as `tag_tokens`.
create index if not exists recipes_diet_flags_gin
  on public.recipes using gin (diet_flags);

-- `cuisine` gets a plain btree: it is queried by equality and by
-- grouping, never by containment.
create index if not exists recipes_cuisine_idx
  on public.recipes (cuisine);

-- No index on `locale_scope`. It is read on rows already selected, to
-- order them — never as a predicate, which is the whole point above.

-- ─── backfill: origin ───────────────────────────────────────────────
--
-- Every existing row is Turkish, authored in Turkish, for a Turkish
-- market. `locale_scope` stays empty: these recipes lead for nobody in
-- particular and are shown to everybody, which is exactly right until
-- there is something else to lead with.

update public.recipes
set cuisine = 'turkish'
where cuisine is null;

-- ─── backfill: diet ─────────────────────────────────────────────────
--
-- Derived rows arrive from `supabase/sql/phase07_recipe_diet_flags.sql`,
-- generated by the classifier and reviewed as a file before it is
-- applied. It is not inlined here because a 292-row CASE expression is
-- not reviewable and because the classifier is the thing under test —
-- duplicating its rules in SQL would give them a second, divergent home.
