import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// Phase 59C · release signing credentials.
//
// `key.properties` lives at `android/key.properties` (gitignored — see
// `android/.gitignore`). It declares `storeFile`, `storePassword`,
// `keyAlias`, `keyPassword`. The matching `upload-keystore.jks` lives at
// `android/app/upload-keystore.jks` so `storeFile=upload-keystore.jks`
// resolves correctly through `file(...)` (which is module-relative inside
// this build script).
//
// When the properties file is missing (CI without secrets / dev machines
// without an upload key), the release build falls back to debug signing
// further down so `flutter run --release` still works.
val keystorePropertiesFile = rootProject.file("key.properties")
val keystoreProperties = Properties().apply {
    if (keystorePropertiesFile.exists()) {
        FileInputStream(keystorePropertiesFile).use { load(it) }
    }
}

android {
    namespace = "com.emredogan.formai"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        // Required by flutter_local_notifications (uses java.time APIs that
        // need to be desugared for minSdk < 26). Pairs with the
        // coreLibraryDesugaring dependency added below.
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.emredogan.formai"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        // Phase 77 · pinned to API 24 because newer ML Kit / MediaPipe
        // releases (`google_mlkit_pose_detection` 0.14+ and the
        // `mlkit_vision_mediapipe` native libs it pulls in) require
        // 24+. The pre-77 default was Flutter's, which can resolve to
        // 21 and produced JNI `NoSuchFieldError` crashes when the
        // older Android runtime tried to bind to fields the newer
        // library introduced.
        minSdk = 24
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        multiDexEnabled = true
    }

    signingConfigs {
        create("release") {
            // Reads from `keystoreProperties` populated above. When the
            // properties file is absent, the four setters below stay at
            // their defaults (null) and `buildTypes.release` falls back to
            // the debug config so dev `flutter run --release` keeps working.
            if (keystorePropertiesFile.exists()) {
                keyAlias = keystoreProperties["keyAlias"] as String?
                keyPassword = keystoreProperties["keyPassword"] as String?
                // `storeFile` is resolved relative to the module directory
                // (android/app), matching where `upload-keystore.jks` was
                // generated by the Phase 59C bootstrap.
                storeFile = (keystoreProperties["storeFile"] as String?)
                    ?.let { file(it) }
                storePassword = keystoreProperties["storePassword"] as String?
            }
        }
    }

    buildTypes {
        release {
            // Phase 59C · use the production upload key when `key.properties`
            // is present; otherwise fall back to debug so dev machines and
            // CI runners without the secret can still produce a release
            // artifact (the resulting APK won't be Play-Store-uploadable
            // but `flutter run --release` works for local profiling).
            signingConfig = if (keystorePropertiesFile.exists()) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }

            // Phase 78 · the Flutter Gradle Plugin auto-applies
            // `isShrinkResources = true` to the release build type
            // (see flutter_tools/.../FlutterPlugin.kt). Phase 77
            // overrode `isMinifyEnabled = false` here, which produced
            // the configure-time error "Removing unused resources
            // requires unused code shrinking to be turned on". We
            // align with the framework default (minify on) so the
            // Phase 77 ProGuard keep rules for ML Kit + MediaPipe
            // actually get exercised on release builds.
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }
}

flutter {
    source = "../.."
}

// Phase 81 · the Phase 79 `configurations.all { resolutionStrategy.force(...) }`
// block that pinned `pose-detection` and `pose-detection-accurate` to
// 17.0.1-beta7 has been removed. The Flutter wrapper `google_mlkit_pose_detection`
// 0.14.1 actually declares `implementation("com.google.mlkit:pose-detection:18.0.0-beta5")`
// in its own `android/build.gradle` (verifiable in pub-cache), so the
// Phase 79 force was a downgrade — the wrapper's compiled Java code
// expected 18.x class signatures (including `com.google.mlkit.vision.common.Detector`)
// that 17.x didn't have, producing the `NoClassDefFoundError` on workout-screen
// open. Letting the wrapper's transitive resolution stand restores the
// 18.0.0-beta5 line everything was built against.

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
}
